### ISSUE TITLE
Facebook und Webseite bei Social Media Profilen

### ISSUE THREAD

**Issue by Nachtmensch87** [codeispoetry/sunflower#101]
Bei den zu hinterlegenden Social Media Profilen fehlt aktuell noch Facebook in der Liste. Gut wäre auch noch die Möglichkeit, an dieser Stelle zu einer anderen Webseite verlinken zu können (zum Beispiel auf die Seite des Kreisverbandes bei Kandidat*innen). Als Symbol könnte man dort ja ein Globus verwenden.

**Comment by codeispoetry** [comment]
Danke für das Ticket. Faceook ist nun auch drin - wie konnte das nur vergessen werden!!

Globus bzw. Webseite geht leider nicht so einfach, weil das in  block_core_social_link_services() nicht enthalten ist. Dieser Bereich ist eh für Social Media Profile reserviert, für Kreisverband oder ähnliches ist das Top-Menu vorgesehen, wahlweise eines der beiden Footer.
