### ISSUE TITLE
Menü Schatten

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#106]
Könntest du bitte noch mal im Menü den Schatten prüfen bzw anpassen:

- [x] Menüleiste: box-shadow: 0 1px 20px rgba(0,0,0,.08)

- [ ] **Dropdown-Feld:** da stimmt irgendwas nicht. Habe folgendes ausprobiert, das sah ganz gut aus:

.dropdown-menu[data-bs-popper] {
    left: 0;
    margin-top: 0.125rem; **das muss weg**
}
.dropdown-menu {
    border: 0;
    **margin-top: 20px; anstatt border-top: 20px solid transparent;**
    box-shadow: 0px 1px 20px rgba(0, 0, 0, 0.1); **(bitte auch anpassen)**
}

**Comment by codeispoetry** [comment]
Klappt das Menü bei margin-top statt border-top auch noch auf?

**Comment by designerin** [comment]
ah ok.. verstehe. es klappt schon auf aber verschwindet auf dem weg weil der cursor über den leeren Bereich muss.. es bleicht nur wenn man den Menüpunkt zuvor anklickt

**Comment by codeispoetry** [comment]
Was ist denn optisch anders, wenn man margin statt border verwendet? (Ich hab da nicht so 1 genaues Auge)

**Comment by designerin** [comment]
die Ecken bleiben oben abgerundet und man kann einen schöneren Schatten setzen, der Schatten sieht im Moment etwas seltsam aus und wenn man ihn verändert bleibt die Border oben ausgespart.

Mein Alternativvorschlag fürs Dropdown:
Dann lass uns einfach nur 5px border top verwenden 
und den Schatten so: box-shadow: 0px 1px 20px rgba(0, 0, 0, 0.1)

was meinst du?

**Comment by codeispoetry** [comment]
Ich habe jetzt noch mal was versucht,  um einen Abstand einzubauen, der das Menü nicht zuklappen lässt. Evtl. ist jetzt irgendwas am Schatten kaputt. Schreib mir das einfach, dass kann ich das einzeln reparieren.

**Comment by designerin** [comment]
super mit den abgerundeten ecken oben im Dropdown jetzt ;)

Kann man machen, dass der unterste Menüpunkt dann keine Bottom-Boder mehr hat? Ich glaube da passiert was komisches mit dem Radius, oder was meinst du wo das her kommt?
<img width="179" alt="grafik" src="https://user-images.githubusercontent.com/78264333/109986590-2fca6080-7d06-11eb-9ff5-90be990da031.png">

Der Schatten ist nicht optimal … aber ich schätze das ist nicht so einfach zu lösen.. nach unten ist der Schatten irgendwie zu lang und zu stark.. 
0px 1px 20px rgba(0, 0, 0, 0.1) fänd ich grundsätzlich schön, sieht dann oben wieder komisch aus.. daher können wir es auch erst mal so lassen.

**Comment by codeispoetry** [comment]
Unten gibt es keinen Strich mehr. Daher closed.
