### ISSUE TITLE
Farben

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#108]
- [x] Blue 500 und Blue 600 haben den gleichen Farbcode: 4097c2. Was soll welcher bekommen?
- [x] Es gibt eine Farbe "Text". Können wir ihr auch einen passenden Namen geben? Grau-100 oder so?
- [x] gleiches gilt für die Farbe "Text".

**Comment by designerin** [comment]
- [ ] Blue 500: #4cb4e7

- [ ] Blue 600: #4097c2

- [ ] Für #363636 Name "Text" ersetzen durch "Black 500"

- [ ] Für #eff2ed Name "Hintergrund" ersetzen durch "Grey 100"
- [ ] Fehlt noch: Green 800b #224634
