### ISSUE TITLE
Respect custom button style

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#111]

**Comment by Nachtmensch87** [comment]
Hinweis: Davon ist auch der Block Trenner betroffen, wenn man einen abweichenden Style auswählt (z.B Punkte)

**Comment by codeispoetry** [comment]
Dankeschön. Bei mir werden die Punkte beim Trenner angezeigt,  bei Dir nicht?

**Comment by Nachtmensch87** [comment]
> Dankeschön. Bei mir werden die Punkte beim Trenner angezeigt,  bei Dir nicht?

Doch doch, sorry. Aber die eingestellte Farbe wird nicht beachtet (war zumindest bisher so).

**Comment by codeispoetry** [comment]
danke. ist ab 0.12.3 drin
