### ISSUE TITLE
Vorstandsseite gestalten

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#113]

**Comment by codeispoetry** [comment]
https://sunflower-theme.de/demo/partei/vorstand/#

**Comment by designerin** [comment]
Super! Das sieht doch schon fast perfekt aus :)

- [ ] Nur das Bild bitte etwas höher (300px) und Breite wie der weiße Textblock darunter. Da ist gerade ncoh bisschen was verschoben. 

<img width="459" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110126761-0b818900-7dc5-11eb-94be-a342603eec2e.png">

- [ ] Und könntest du bitte den Abstand oberhalb der Bilderreihe zur Headline "Vorstand" wieder angleichen wie bei "Aktuelles" 
- [ ] Meinst du wir sollten unter der Headline "Vorstand" wieder eine kleine Subheadline vorsehen, wie bei "Aktuelles"?

**Comment by codeispoetry** [comment]
Eine Subline gibt es bei Seiten nicht.

**Comment by designerin** [comment]
ok super, dann passt es für mich so. Danke dir!
