### ISSUE TITLE
Termine

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#115]
- [x] Hier lieber ohne das Icon arbeiten und nur schreiben "Zur Online-Teilnahme (Webinar)"

<img width="355" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110016638-90b56100-7d25-11eb-8ed2-04ea845c2407.png">

<img width="806" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110016736-ad519900-7d25-11eb-8363-83225a21b897.png">

**Comment by designerin** [comment]
<img width="672" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110017632-b727cc00-7d26-11eb-80fc-0d47e6ea92f7.png">

- [ ] könnten wir bei den Terminen neben den Social Media Icons noch einen Link "zurück zur Übersicht" einfügen?
- [ ] Und was hältst du von einer Navigation (Vorheriger / Nächster Termin) unten? Wie auch bei den Blog-Beiträgen? Wenn zu aufwendig, muss es nicht sein.

**Comment by codeispoetry** [comment]
Das zurück zur Übersicht ukann ich erst in einem zukünfitgen Release ein. Deshalb tagge ich es entsprechend und schließe das Ticket hier.
