### ISSUE TITLE
Breite des Seiteninhalts Bestimmen

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#117]
<img width="322" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110150862-067e0300-7de0-11eb-93ed-7462ce8adf32.png">

Haben diese beiden Funktionen im Backend auswirkungen auf die Darstellung? Ich habe getestet und bei Unterseiten wird so und so kein Titel angezeigt und die Breite verändert sich auch nicht.

Grundsätzlich wäre sinnvoll, wenn man zwischen schmal (Wie bei Blogeinträgen) und breit (wie auf der Startseite mit 3 Spalten etc.) wählen könnte. Oder?

**Comment by designerin** [comment]
Hat sich erledigt :)

**Comment by codeispoetry** [comment]
ist

**Comment by codeispoetry** [comment]
Diese Einstellung galt bislang nur für Seiten, sollte aber auch auf Beiträge möglich sein. Wenn man einen Beitrag mit einem Coverbild starten will, sollte es keinen Titel geben.

**Comment by codeispoetry** [comment]
das mit dem breit und schmal nehme ich erst mal raus. das kann ggf. in einer folgeversion kommen
