### ISSUE TITLE
Startseite Abstand seitlich / Blöcke unterschiedlich breit

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#119]
- [ ] vielleicht liegt es auch an was anderem, aber ich glaube der 

class="wp-block-group__inner-container"
braucht noch ein max-width: 1176px
oder?

Die Blöcke auf der Startseite sind aktuell unterschiedlich breit (manche ragen über das Raster hinaus.) 
Kannst du das bitte noch mal prüfen?

Auch bei kleineren Bildschirmen & Tablets fällt das stark auf. Könnte man auch da die Breite so einstellen wie aktuell beim "Herzlich Willkommen" Text ganz oben? Sodass mehr Abstand nach rechts und links bleibt?

Also bitte noch mal für alle Formate prüfen und anpassen, wenn das geht

<img width="1028" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110214832-b4ec7b80-7ea6-11eb-9467-c15231883f70.png">

**Comment by designerin** [comment]
- [ ] und beim Abschnitt "Willkommenstext" bräuchten wir noch einen Spacer von 60px

**Comment by designerin** [comment]
- [ ] und leider ist in der Mobilvariante hier der Abstand den untereinander stehenden Spalten wieder verloren gegangen 
<img width="362" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110214993-af436580-7ea7-11eb-8513-3b82b1d6a9ce.png">

**Comment by codeispoetry** [comment]
Die Blöcke sind nun gleich breit, einer war nicht in einer Gruppe. Der Rest wird in einem neuen Ticket #135 bearbeitet.
