### ISSUE TITLE
Abbildungen auf Ipad

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#120]
<img width="1034" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110214700-224bdc80-7ea6-11eb-9a8e-96520524eb31.png">

die Bilder bekommen ein blödes Fprmat auf dem Ipad. eingestellt ist max Hähe 140px. können wir das auf 200px umstellen?

**Comment by codeispoetry** [comment]
ist angeasst. ggf. kannst du da noch mal neue Bilder hochladen, die von Beginn an auch gleich groß sind
