### ISSUE TITLE
Bildersammlung

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#123]

**Comment by designerin** [comment]
Platzhalterbild Personen

**Comment by codeispoetry** [comment]
Kannst Du gerne online austauschen. Einfach auf Bild ersetzen gehen

**Comment by designerin** [comment]
Ok mach ich, das war mehr ein Ticket für mich selbst, dass ich noch eine platzhaltergrafik erstellen muss, dann setze ich sie ein sobald ich sie fertig habe :)

**Comment by codeispoetry** [comment]
Ich schließ das hier vorläufig mal, damit die Ticketseite aufgeräumt ist. Aktuelle werden Beispielbilder ja nicht nachgefragt.
