### ISSUE TITLE
Fuktion links Bild rechts Text kaputt

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#124]
<img width="608" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110244774-ab274e80-7f60-11eb-8f16-bbf52a06d984.png">

diese Funktion links Bild rechts Text ist glaube ich durch die Personen-Sache kaputt gegangen. Die sollte aber schon besser wie ursprünglich funktionieren, oder? Dann würde ich die Personen-Darstellung lieber anders lösen.

Was meinst du?

Ansonsten können wir das Personen-Ding gerne auch anders lösen (wie auf Seite 2 in meinem PDF-Layout) und ähnlich arbeiten wie bei "unsere Themen" auf der Startseite. Vielleicht ist das einfacher?

<img width="647" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110245420-546f4400-7f63-11eb-9cc7-6119820fe73f.png">

**Comment by Nachtmensch87** [comment]
Das bezieht sich sicher auf den Block 'Medien und Text'. Ist mir auch aufgefallen, dass dieser nicht mehr nebeneinander dargestellt wird, sondern stets untereinander. Erst Bild, dann Text. 

An sich finde ich die Darstellung sogar ganz gut. So lässt sich gut mit Bildern und Text arbeiten. Wäre es nicht möglich, sowas als custom block hinzuzufügen?

**Comment by codeispoetry** [comment]
Angedacht war von mir, dass der Block "Medien + Text"grundsätzlich untereinander ist. Wer etwas nebeneinander haben möchte, kann ja gut Spalten verwenden.

**Comment by codeispoetry** [comment]
Ich habe es jetzt so umgebaut, dass der ursprüngliche Block erhalten bleibt und wenn man den Klassennamen person vergibt, wird es untereinandre dargestellt. Wenn man Person über die Vorlagen einbindet, ist dass dann automatisch dabei.

**Comment by Nachtmensch87** [comment]
Ich denke, das ist noch nicht optimal gelöst. Durch die Klasse Person wird die Darstellung des Blocks zwar so geändert wie es zuvor war, jedoch ist der Umgang mit dem Bild anders. Aktuell wird das Bild einfach nur gestreckt, was dann natürlich nicht so schön aussieht.

In der Vorlage Person ist die Klasse Person nicht automatisch enthalten.

![PXL_20210312_101519088.jpg](https://user-images.githubusercontent.com/10704700/110926557-d45f2a80-8324-11eb-826e-1b266c2f5881.jpg)

**Comment by codeispoetry** [comment]
Ist in 0.12.2 behoben
