### ISSUE TITLE
Kontaktformular

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#125]
Bei Gelegenheit könnten wir noch das Kontaktformular auf ähnliche Art umgestalten: (hat für mich aber keine Prio)
https://sunflower-theme.de/demo/kontakt/

<img width="1228" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110245968-ea0bd300-7f65-11eb-833e-730a6a43d4d6.png">

**Comment by codeispoetry** [comment]
habe es als for future release getagged und schließe es einstweilen

**Comment by codeispoetry** [comment]
https://sunflower-theme.de/demo/kontakt/
