### ISSUE TITLE
Absatz Abstände

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#126]
<img width="1226" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110246288-5c30e780-7f67-11eb-8dc7-2e352bb09939.png">

prinzipiell fände ich schön, wenn bei Absätzen oberhalb der Überschriften mehr Abstand wäre (so wie im Screenshot zB). Ich vermute aber, dass man da nicht so gut ran kommt, außer wieder zu viele Auswirkungen an vielen Ecken und Enden zu haben, oder? (sowas wie Margin-top 3rem bei Headlines zB) oder?

- [x] aber könnten wir bitte dem horizontalen Trennstrich hier noch margin 3rem geben?
class="wp-block-separator"

**Comment by designerin** [comment]
<img width="208" alt="grafik" src="https://user-images.githubusercontent.com/78264333/110517633-65f35000-810b-11eb-8f0a-c4edefd8a795.png">

Diesen hier, wird wohl auch gerne verwendet

**Comment by codeispoetry** [comment]
Der Abstand fürs Trennzeichen wird ab 11.7 enthalten sein
