### ISSUE TITLE
Beitragsbild rutscht über Menü 

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#127]
http://6154482933256.hostingkunde.de/ortsverbaende/ov-dillingen/

Schau mal, das ist mir noch aufgefallen.. können wir da was machen oder ist da ein Fehler in der Anwendung?

**Comment by codeispoetry** [comment]
wird in 11.6 verbessert sein

**Comment by Nachtmensch87** [comment]
Nach wie vor noch vorhanden. Wird ein Beitragsbild verwendet und **kein** Titel, dann überdeckt das Bild die Menüeinträge vollständig (fängt knapp unterhalb des Grün an).

**Comment by codeispoetry** [comment]
Ah, danke für den Hinweis. War bisher nur für Beiträge, bei Seiten gab es einen Fehler. ist in 0.12.4 behoben
