### ISSUE TITLE
Zeilenumbruch in mobilen Ansichten bei Nicht-Seitentiteln

### ISSUE THREAD

**Issue by Nachtmensch87** [codeispoetry/sunflower#134]
Beim Seitentitel wurde eine Funktion implementiert, sodass mittels `&shy;`
ein Zeilenumbruch definiert und eine Bindestrich gesetzt werden kann.

Ist es auch möglich, diesen Zeilenumbruch für Wörter zu definieren, die im Block Überschriften definiert wurden?

**Comment by codeispoetry** [comment]
Du kannst ``&shy;`` überall verwenden, wo Du möchtest. Das ist normales HTML, hat auch nichts mit Sunflower zu tun.

**Comment by Nachtmensch87** [comment]
Danke für den Hinweis. Ist ein wenig Tricky in Wordpress. Im Seitentitel kann ich `&shy;` einfach im Gutenberg-Editor eingeben und es funktioniert automatisch.

In den anderen Blocks funktioniert es nicht zwingend ohne weiteres. Ich kann aber die Überschrift anlegen, dann unter Optionen 'in HTML bearbeiten' auswählen und es dann einfügen und danach wieder visuell bearbeiten (oder direkt ein HTML Code Block nehmen). Oder ich bearbeite es visuell, und füge über ALT+0173 das Trennzeichen ein. Über AltGr+ - hatte es nicht funktioniert.

Gebe ich `&shy;`nur visuell ein, dann wird es als Text gerendert und wenn man es danach in HTML bearbeitet, steht davor zusätzlich auch ein `&amp;`

Vielleicht kann man das ja noch in der Dokumentation ergänzen:)
```

**Comment by codeispoetry** [comment]
Danke für sie Rückmeldung. Ich kopiers in die Doku.

**Comment by codeispoetry** [comment]
Ich hab es in die Doku aufgenommen: https://sunflower-theme.de/documentation/faq/#manche-begriffe-sind-auf-handys-zu-lang
