### ISSUE TITLE
Seiten ohne Headline

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#141]
Können wir hier noch etwas mehr Abstand oben zum Menü einbauen?

60px wären top

https://sunflower-theme.de/demo/lesung-mit-robert-habeck/
https://sunflower-theme.de/demo/critical-mass/

Anschließend kannst du gerne die Headlines auch wieder einblenden. Das war ja nur für den Test, denk ich

**Comment by codeispoetry** [comment]
Das sollten wir den Nutzer*innen überlassen. Wer keinen Titel anzeigen möchte, muss dann den Abstand selbst einbauen. Wenn man nämlich oben ein Bild haben möchte, darf da kein Abstand hin.

**Comment by codeispoetry** [comment]
Wenn Du das genauso siehst, kannst Du das Ticket gerne schließen

**Comment by designerin** [comment]
da gebe ich dir Recht, dann passt das so für mich :)
