### ISSUE TITLE
Kontaktformular wird ohne Inhalt übermittelt

### ISSUE THREAD

**Issue by Nachtmensch87** [codeispoetry/sunflower#147]
Es wird eine Mail an die in WP hinterlegte E-Mail Adresse gesendet, jedoch sieht man nur den Namen und die Mail-Adresse aus dem Formular. Der eigentliche Nachrichteninhalt wird nicht übermittelt.

**Comment by codeispoetry** [comment]
in 0.14.0 behoben

**Comment by Nachtmensch87** [comment]
Kann ich leider noch nicht bestätigen. Nach Update auf 14.1 wird der Inhalt nach wie vor nicht übertragen.

**Comment by codeispoetry** [comment]
Hast Du einen Link für mich? Bei mir im Test funktioniert es. Ggf. musst Du Deine Kontaktseite mit Shift-Reload laden, damit die den aktuellen Quelltext erhälst.

**Comment by Nachtmensch87** [comment]
Funktioniert:) Das Neueinbinden des Blocks hat das Problem gelöst. Den Cache hatte ich schon gelöscht.
