### ISSUE TITLE
Korrekturen

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#148]
- [x] ist eigentlich die Headline standardmäßig ausgeblendet? Die fehlt an vielen Stellen bei den bereits existierenden sunflower-Seiten
- [x] bei Termin- & Beitragsübersichten hat sich wieder ein Abstand rein gemogelt unterhalb des Textausschnitts 
- [x] Auch auf den Beitragsseiten ist der Abstand zwischen Text und Social Media Icons zu groß geworden.. Icons sollten mittig sitzen oder tendenziell näher am Text
<img width="473" alt="grafik" src="https://user-images.githubusercontent.com/78264333/111386398-7deb4680-86ac-11eb-9e1a-1702fcdb57d7.png">

- [x] Fahrradseite: letzter Absatz/Block wird auf smartphone rechts und links abgeschnitten
- [ ] Die Blöcke auf der Startseite sind auf meinem Tablet noch unterschiedlich breit. Alle sollen schmal sein, Der Text soll nicht bis zum Bildschirmrand laufen.

**Comment by codeispoetry** [comment]
Wenn damit alles passt, kannst Du das Ticket gerne schließen
