### ISSUE TITLE
Header + Footeranpassung

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#149]
**Header**
- [x] Suche Kasten ersetzen durch Lupen-Symbol (Font Awesome, 14px, weiß, 70% opacity) –  mit Link zu einer "Suche" Seite – geht das?
- [x] mittleren grünen Balken: 30px höher (Gesamthöhe 120px)
- [x]  1. Logozeile Text "Grüne Musterstadt" auf 25px vergrößern
- [x] weißen Menü-Balken 6px höher (bitte prüfen, dass die grüne Linie wieder an der Unterkante sitzt
- [ ] Dropdown-Pfeil ersetzen durch Fontawesome Symbol, Farbe #ACACAC, Größe 12px angle-down 

- [ ] Mobilvariante andere Sonnenblumen-Position (Siehe Screenshot – geht das?) ich will vermeiden, dass die Sonnenblume wie aktuell vom Text verdrängt und winzig klein wird.

**Widget-Area:**
- [x]  Komplette Schrift auf 90% opacity
- [x]  Headlines Widgets: letter-spacing 0.3px

**Footer:**
- [x] weißer Strich: opacity 60%
- [x] Schrift auch 90% opacity
- [x] social icons Kreis 40x40px, 80%opacity

Hier eine Abbildung zur Veranschaulichung für den angepassten Header + Mobil

<img width="913" alt="grafik" src="https://user-images.githubusercontent.com/78264333/111477850-d152a880-872f-11eb-88b4-3582238e5648.png">

**Comment by Nachtmensch87** [comment]
Auch wenn ich damit eigentlich nichts zu tun habe - durch die geänderte Positionierung des Headers wird dieser ja schon ein gutes Stück größer. So einen hohen Header-Bereich finde ich schon im Urwahl Theme als sehr störend (Mobilansicht). Gehen ggfs beide Varianten? Über eine zusätzliche Klasse? Je nach verwendeter Anzahl an Zeichen kann man dann entscheiden?

**Comment by codeispoetry** [comment]
Zu der Frage mit dem Logo gibt es ein neues Ticket #156 
Der Dropdown-Pfeil wird in #157 bearbeitet

Der Rest ist fertig.

**Comment by codeispoetry** [comment]
@designerin Du kannst dieses Ticket schließen, wenn alles passt
