### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#150]
Einfügen des eigenen KV Logos scheint nicht möglich.
Der einzige Ort an dem das Logo in der Form des Logogenerators momentan verwendet wird scheint im footer zu sein.

![grafik](https://user-images.githubusercontent.com/63392812/111511839-644f0b00-874f-11eb-8a4d-0a517955c9fe.png)

**Comment by b90g** [comment]
gleiches giilt auch führs hintergrund- & headerbild, ich glaube entweder dokumntieren dass es nichts macht oder wenns geht ausblenden

**Comment by codeispoetry** [comment]
Danke für das Ticket. Eine Änderung des Logos ist vom Design her nicht vorgehen. Oben ist nur Platz für die Sonnenblume und ein Schriftzug im Logo unten ist so klein, dass er nicht mehr gelesen werden kann.
