### ISSUE TITLE
Anker werden nicht richtig angefahren

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#155]
https://dev.g-tk.de/datenschutz/#instagram

Die Überschrift landet genau am Browserrand bzw unter der Menüleiste:

![grafik](https://user-images.githubusercontent.com/63392812/111587818-fba17600-87c2-11eb-9195-4eb4882681b5.png)

**Comment by codeispoetry** [comment]
in 0.14.0 behoben
