### ISSUE TITLE
Logo in Mobilvariante

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#156]

**Comment by designerin** [comment]
wir lassen die Blume jetzt erst mal links. Aber wir brauchen für mobil noch mal andere Schriftgrößen und Abstände:

- [ ] Sonnenblume Abstand zum Text nach rechts aktuell 0.25rem auf 0.75rem erhöhen
- [ ] Sonnenblume sollte minimum 50px und maximal 55px groß sein
- [ ] Text 1. Logozeile 22px
- [ ] Text Logo Subline 17px und weniger Zeilenabstand (1.3)
- [ ] und dafür wieder 3px mehr Abstand zwischen 1. Logozeile und Subline
- [ ] Sonnenblume im Sticky-Header etwas nach rechts rücken (0.5rem)

sollte dann ungefähr so aussehen:
<img width="423" alt="grafik" src="https://user-images.githubusercontent.com/78264333/111880405-b2604a80-89ab-11eb-87e4-44449c782304.png">

ich hoffe, damit haben wirs und alle sind glücklich :)

**Comment by codeispoetry** [comment]
erledigt. Ticket kann gerne geschlossen werden, wenn es passt
