### ISSUE TITLE
Designfixes

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#16]
- [x] Buttons etwas kleiner (zB. 42px)
- [x] Border Radius 8px
- [x] Text allgemein nicht ganz schwarz, sondern (#363636)
- [x] Bei den Schlagworten/ Kategorien bei den Beiträgen hat es irgendwas zerschossen glaub ich..

**Comment by codeispoetry** [comment]
Das mit den kleineren Buttons habe ich über die Schriftgröße gelöst, die ist jetzt wieder 1rem, war zuvor wie überall sonst 1.125em.

**Comment by designerin** [comment]
Sehr gut, danke dir! sorry, ich hab mich missverständlich ausgedrückt. 
Die Buttons bitte ohne Radius.
Ich meinte bei den Bildern den Radius reduzieren. Lass uns 10px machen.
Werde mich in Zukunft um eindeutig formulierte Anpassungswünsche bemühen ;)

**Comment by codeispoetry** [comment]
- [ ] Buttons ohne Radius
- [ ] Bilderecken 10Px Radius

**Comment by codeispoetry** [comment]
Ich habe beides umgesetzt. Wenn das so passt, kannst Du das Ticket gerne schließen.

**Comment by designerin** [comment]
Bei mir werden die Bilderecken aktuell noch mit 15px angezeigt

**Comment by codeispoetry** [comment]
Sorry, ja. War noch nicht deployed (=von meiner lokalen Entwicklung auf den Server übertragen).
Jetzt aber

**Comment by designerin** [comment]
ja, jetzt passts :)
