### ISSUE TITLE
Kleine Anpassungen Startseite

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#163]
leider sind mir doch noch ein paar Kleinigkeiten aufgefallen:

- [x] Bei den Schlagworten kein Komma, sondern mit 2 Leerzeichen trennen: #Kommunalwahl  #Naturschutzgebiet  #Wenge Radverkehr (auch auf allen anderen Seiten)
- [x] # und Komma nicht black, sondern #363636 (auch auf allen anderen Seiten)

**grüner XL-Button auf der Startseite bei den Beiträgen:**
- [x] der macht responsiv zum Teil Probleme. Daher lassen wir das "Alle Beiträge" weg. nur noch das "ZUM BLOGARCHIV" mittig setzen
- [x] Hover wieder auf #3C8025 (ist verloren gegangen)
- [x] lässt es sich machen, dass der Button sich wie ein Beitrag als letztes einreiht? Aktuell entstehen manchmal große Lücken, weil er sich am untersten Beitrag orientiert. (vermute das ist schwierig.. sonst lassen wir es so.)

- [ ] **Die Headlines H1** haben jetzt alle 80px abstand nach unten, oder? Ich kann damit leben, aber bei "Werde aktiv" und "Nächste Termine" ist es eigentlich zu viel. Könnten wir hier auf 40px reduzieren? Wenn nicht, dann lassen wirs so.

- [x] Bei "unser Programm für Musterstadt" habe ich den Platzhaltertext mal geändert und den Textblock mittig ausgerichtet. (war an oberkante ausgerichtet) nur falls das zum Erstellen der Blöcke relevant ist.)

<img width="488" alt="grafik" src="https://user-images.githubusercontent.com/78264333/111904507-9dd19000-8a47-11eb-9f1f-c6f997181bee.png">
 

Auf der Testseite "Schneller-Radweg":
- [ ] Die H2 hat zu viel Abstand nach unten. 40px sind ausreichend.

**Comment by codeispoetry** [comment]
Die H2 hat zu viel Abstand nach unten. 40px sind ausreichend. -> dann ändert sich das auch auf unserer Musterseite. Trotzdem machen?

**Comment by codeispoetry** [comment]
Das mit dem Button ist ein eigenes Ticket #167

**Comment by codeispoetry** [comment]
Die Headlines H1 haben jetzt alle 80px abstand nach unten, oder? Ich kann damit leben, aber bei "Werde aktiv" und "Nächste Termine" ist es eigentlich zu viel. Könnten wir hier auf 40px reduzieren? Wenn nicht, dann lassen wirs so.

Enteweder gebe ich das allen oder keinem.

**Comment by codeispoetry** [comment]
Soweit erledigt. kann geschlossen werden

**Comment by designerin** [comment]
ok, dann bitte den Abstand von H1 von 80 auf 70 reduzieren. Dann kannst du das Ticket schließen, danke dir
