### ISSUE TITLE
Unable to run npm install - fontawesome

### ISSUE THREAD

**Issue by Soean** [codeispoetry/sunflower#164]
I would like to contribute to this theme, but If I try to run `npm install` I get this error:

`Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com"`

**Comment by codeispoetry** [comment]
Thank you for contributing. 

Ich habe das Projekt frisch geclont und konnte npm ausführen, Fontawsesome wurde korrekt eingebunden. Tritt der Fehler bei Dir immer noch auf? Führst Du npm in irgendeinem besonderen Kontext aus?

**Comment by Soean** [comment]
Bei mir war lokal noch eine abgelaufene fontawesome Lizenz hinterlegt und eine fortawesome:registry config. Habe es entfernt und nun funktioniert es.
