### ISSUE TITLE
Vorstand-Seite

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#165]
- [x] da stimmt noch was nicht mit den Bildern (die Ecken unten nicht abrunden)
- [x] das Layout ist jetzt schmaler, dadurch passt das für desktop irgendwie nicht mehr richtig... hast du eine Idee, was wir da machen können? 

Könnte man folgendes nur für Desktop verändern: (mobil passt eigentlich) 
Mein Vorschlag wäre:
- [x] Name in H5 (25px)
- [x] Beschreibung und mailadresse in 16px
- [x] Bildhöhe nur 250px
- [ ] Abstand zwischen den Spalten lässt sich vermutlich nur Global verändern? Ansonsten gerne auf 1.5em reduzieren.

**Comment by codeispoetry** [comment]
Wir können statt 3 nur zwei Personen nebeneinander setzen. Das passt auch inhaltlich besser. Machen wir das so?

**Comment by designerin** [comment]
sehr gut, ich glaube so machen wirs :)

**Comment by codeispoetry** [comment]
Abstand geht leider nur global

**Comment by codeispoetry** [comment]
Soweit erledigt. Kann geschlossen werden.

**Comment by designerin** [comment]
Oh mann... entschuldige bitte!! Dein Vorschlag mit den 2 nebeneinander war eigentlich schon die Lösung – bitte dies wieder rückgängig machen  – das hätte sich auf die 3 nebeneinander bezogen.

 Name in H5 (25px) -> Wieder H4
Beschreibung und mailadresse in 16px -> wieder normaler Bodytext
Bildhöhe nur 250px -> wieder 300px

tut mir sehr leid, das war ein missverständnis.

**Comment by codeispoetry** [comment]
erledigt
