### ISSUE TITLE
Einstellungen im Sunflower-Menü werden nicht beibehalten

### ISSUE THREAD

**Issue by Nachtmensch87** [codeispoetry/sunflower#166]
Wenn ich in den Sunflower Einstellungen in einem beliebigen Bereich Einstellungen ändere und speichere, werden die Einstellungen in den anderen Bereichen zurückgesetzt.

Ich trage z.B. Social Media Links ein und speichere und etwaige Kalender-URLs oder die Mail-Adresse sind dann nicht mehr vorhanden.

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Ist behoben. Einstellungen zu Social Media und Terminen müssen neu eingetragen werden. Sorry.
