### ISSUE TITLE
Fehler bei Aktivierung

### ISSUE THREAD

**Issue by Soean** [codeispoetry/sunflower#169]
Nach der Aktivierung des Themes bekomme ich eine PHP Warnung:
`Warning: array_merge(): Expected parameter 1 to be an array, null given in .../functions/activation.php on line 13`

Hier sollte geprüft werden, ob es diese option gibt, bevor darauf zugegriffen wird.

```php
$options = get_option('theme_mods_urwahl3000'); 
$sidebars_widgets = array_merge($options['sidebars_widgets']['data']['infospalte'], $options['sidebars_widgets']['data']['fussleist'] );
```

**Comment by codeispoetry** [comment]
Ist schon behoben. Mach mal git pull

**Comment by Soean** [comment]
Hier sehe ich noch keine Änderung:
https://github.com/codeispoetry/sunflower/blob/3807d9d72706e3b9c5e0f765e0732ad9477e8aeb/functions/activation.php#L12-L13

**Comment by codeispoetry** [comment]
Ah, sorry. Passt. Schau ich mir an. Ich habs verwechselt. Danke.
