### ISSUE TITLE
Abstände von Überschriften zum Menürand bzw letzem Block zur Fußzeile

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#173]
sind zu gering, momentan behelfe ich mir damit, dass ich leere absätze einfüge:

![grafik](https://user-images.githubusercontent.com/63392812/112038703-7bbd3800-8b43-11eb-949e-e5ab5c03f91b.png)

und ohne:

![grafik](https://user-images.githubusercontent.com/63392812/112038819-9b546080-8b43-11eb-893c-be8ebd0988af.png)

und unten mit:

![grafik](https://user-images.githubusercontent.com/63392812/112038889-ac9d6d00-8b43-11eb-9dbe-ff0497db5503.png)

vs Ohne;

![grafik](https://user-images.githubusercontent.com/63392812/112038951-be7f1000-8b43-11eb-986b-f7a4100d4942.png)

**Comment by b90g** [comment]
vielleicht soll das aber auch so sein und mein ästhetisches empfinden ist nicht das was die mehrheit gut findet (:

**Comment by codeispoetry** [comment]
Wenn der Haken bei "gestyltes Layout" gestzt ist, musst Du dich um die Abstände selbst kümmern.
Nimm den Haken raus, dann sind die Abstände wieder da.
(ich nehme das zum Anlass, den Namen "Gestyltes Layout" zu ändern
