### ISSUE TITLE
Links im Ausklappmenü klappen nur das menü aus

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#174]
![grafik](https://user-images.githubusercontent.com/63392812/112044965-9b0b9380-8b4a-11eb-8f4d-70e2c3c3ceb4.png)

ich hab mir hier damit beholfen, dass ich darunter einen Link erstellt habe der über blick heißt.

Ich weiß nicht was gängige webdesign praxis ist und kann mich auch ans neuere gewöhnen.

**Comment by codeispoetry** [comment]
ist in 0.14.8 behoben bzw. eingebaut

**Comment by Nachtmensch87** [comment]
@codeispoetry In der Mobilvariante klappt das Menü nun nicht mehr auf.

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Dann muss ich diese Änderung leider wieder rückgängig machen, den mobil kann ich nicht unterscheiden, ob man das Menü öffnen will oder wo anders hin will. 
Damit klappen auch weiterhin Menüpunkte in der obersten Ebene nur das Untermenü auf und führen nicht woanders hin. Das wird so bleiben.
