### ISSUE TITLE
Mastodon

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#175]
bei den kandidatinnenspalten ist es mir in der metadatenzeile nicht gelungen `fa fa-mastodon` zu verwenden: https://dev.g-tk.de/unsere-kandidatinnen/ (willi junga) mach ich was falsch?

**Comment by Soean** [comment]
Mit `fab` sollte es funktionieren: `<i class="fab fa-mastodon"></i>`
