### ISSUE TITLE
Anpassung Schriftgröße

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#177]
Nachdem ich noch ein paar Seiten in der Anwendung gesehen habe würde ich gerne noch mal die Schriftgrößen etwas anpassen.

- [x] H1 auf 45px reduzieren
- [x] H2 auf 31px reduzieren
- [x] H3 umwandeln in PT Sans bold,  27px,  #46962b

**Comment by codeispoetry** [comment]
H1 hat bisher 40px, H2 30px. 
Die Änderungen wären jeweils Vergrößerungen, keine Reduzierungen. Stimmt das so, @designerin ?

**Comment by designerin** [comment]
Moment, dann lass das bitte erst mal. Das muss ich noch mal prüfen.-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 24.03.21, 23:09 schrieb Thomas Rose ***@***.***>:

   
  H1 hat bisher 40px, H2 30px. Die Änderungen wären jeweils Vergrößerungen, keine Reduzierungen. Stimmt das so, @designerin ?

**Comment by designerin** [comment]
also das ist seltsam mit den Headline-Größen. 
Kannst du das bitte noch mal prüfen? Dargestellt wird immer H1 47px und H2 34px

<img width="308" alt="grafik" src="https://user-images.githubusercontent.com/78264333/112520299-8b36be00-8d9b-11eb-8e0c-afbff715f9fd.png">

**Comment by codeispoetry** [comment]
Ah sorry, ich hab an der falschen Stelle geguckt. Ist geändert.

**Comment by designerin** [comment]
- [ ] die H3 in Farbe #46962b – ist das nicht möglich, oder nicht sinnvoll? (das war die gedachte Unterscheidung zwischen H3 und H4. aktuell sind sie gleich. Ich habe mich nicht mehr getraut die H4 anzurühren, da sie an so vielen Stellen schon verbaut ist. 

Bitte auch noch mal für mobil anpassen:

- [ ] H1 36px
- [ ] H2 27px

**Comment by codeispoetry** [comment]
das mit der farbe ist mir durchgerutscht. sorry.

**Comment by codeispoetry** [comment]
erledigt.

**Comment by designerin** [comment]
vielen Dank jetzt passt es :) 

Nur bitte an dieser Stelle auf der Startseite die H4 beibehalten, also nicht grün. 

<img width="372" alt="grafik" src="https://user-images.githubusercontent.com/78264333/112857922-a6624000-90b1-11eb-9940-e084cd0f8563.png">

**Comment by codeispoetry** [comment]
erledigt.
