### ISSUE TITLE
Hover Effekt Termine

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#178]
Bei den Terminkacheln ist mir der Hover Effekt bisschen zu krass. Ich orientiere mich an einer dezenteren Lösung aus unserer "Gestaltungs-Vorlage"....

Können wir den grünen Hovereffekt und Text weiß entfernen und ersetzen durch sowas wie:

- [x] box-shadow: 0 1px 15px rgba(0, 0, 0, 0.15);
- [x] margin-top: -0.1rem;
- [x] margin oder padding-bottom: 0.1rem;

geht das? soll eben so aussehen, als würde die Kachel sich leicht abheben.. wenn du einen anderen Vorschlag für eine technische Umsetzung hast gerne – man kann ja so effekte auch verzögert darstellen (siehe gruene.de)

Bei allen anderen Elementen finde ich den grünen Hover-Effekt gut und er soll so bleiben.

**Comment by codeispoetry** [comment]
ist eingebaut. wenn es passt, kannst du das ticket gerne schließen

**Comment by designerin** [comment]
vielen Dank, gefällt mir sehr gut. Nur ist mir der Effekt doch noch etwas zu sachte. kannst du es bitte noch mal anpassen? Sorry...

margin-top: -0.2rem;
margin-bottom: 0.2rem;
transition: all 0.2s ease-out;

wenn das gemacht ist darfst du das ticket schließen.

**Comment by designerin** [comment]
- [ ] eine Sache noch zum Thema Hover: 
beim Blog Masonry wäre noch ein Hover in der Headline sehr fein..
Hover dunkelgrün #3C8025

<img width="357" alt="grafik" src="https://user-images.githubusercontent.com/78264333/112519851-0e0b4900-8d9b-11eb-8ca2-9c9610c92f4b.png">
