### ISSUE TITLE
Seitenleiste

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#18]
- [x] Suche
- [x] Kategorien
- [x] Neueste Beiträge
- [x] Schlagworte
- [x] Archiv
- [x] Folge uns auf

Zu sehen auf https://wordpress.tom-rose.de/demo/?p=83

**Comment by codeispoetry** [comment]
Größe und Farben passen wahrscheinlich noch nicht. Du hattest 15pt (Point) angegeben, ich kann leider nur mit Pixeln px arbeiten. Kannst mir gerne hier anmerken, wo welche Größe bzw. Farbe nicht passt.

**Comment by codeispoetry** [comment]
Bei Archiv kann ich den Pfeil leider nicht farblch unterlegen, der kommt vom Browser.

**Comment by designerin** [comment]
- [ ] Headlines in 1.3em
- [ ] Headlines in Farbe #363636
- [ ] Hintergrund in #EFF2ED
- [ ] die horizontalen Linien gerne in blassgrau #AFAFAF
- [ ] 265px Breite für den Inhalt der Seitenleiste sollte reichen.

**Comment by codeispoetry** [comment]
>  265px Breite für den Inhalt der Seitenleiste sollte reichen.

Ich verwende das Bootstrap-Grid. Das hat 12 Spalten, die sind entsprechend breit, je nach dem wie viel Platz man hat. Pixelgenau kann ich die nicht setzn. Die Seitenleiste ist 4 Spalten breit, mache ich sie auf 3, wird es schon sehr dünn.

**Comment by designerin** [comment]
sorry, die 1.3em für die Headline stimmen nicht.

**Comment by designerin** [comment]
ok, dann lassen wir die Breite der Seitenleiste so.

**Comment by designerin** [comment]
Die Headlinefarbe #363636 in der Seitenleiste ist aktuell noch nicht sichtbar.

**Comment by codeispoetry** [comment]
Alles erst mal erledigt. Wenn es passt, kannst Du das Ticket gerne schließen

**Comment by designerin** [comment]
Ich glaube das mit der Seitenleiste rechts funktioniert so nicht -.- tut mir leid. 
dafür haben die meisten hier viel zu viele Kategorien und so. Das wir einfach viel zu lang. Und sieht auch einfach nicht schön aus.

Wir werden besser nur unten eine „Widget Area“ machen – wie auch auf meinen Entwürfen für die Startseite. 4 Spalten. Hier soll dann alles rein, was aktuell schon in der Seitenleiste der bestehenden Seiten ist – dann geht das auch nicht verloren. Der Einfachheit halber machen wir dann auch nur eine Version "Widget Area" und nicht wie neulich von mir überlegt mehrere. 

- [ ] Widget Area unten (über dem Footer Menü)
- [ ] 4 Spalten

Farbigkeiten für Hintergrund und Text werden noch geändert. Dazu schicke ich dir noch ein Update

Sorry für den Zusatzaufwand
