### ISSUE TITLE
Bilder Radius, Mediengalerien

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#180]
- [x] border radius 10px bei allen Bildern (auch zB hier bei den beiden Bildern: https://sunflower-theme.de/demo/typographie/)
- [x] könnte man für Bildergalerien einstellen, dass die beiden Bilder mobil untereinander rutschen? Und dass man Bilder durch anklicken vergrößert angezeigt bekommt und die Galerie durchklicken kann? (ist hier zb. auch so: https://demo.urwahl3000.de/bilder-galerien/)

**Comment by codeispoetry** [comment]
das mit dem Durchklicken durch die Gallery ist ein eigenes Ticket #181, das erst nach 1.0.0 kommt.
