### ISSUE TITLE
CSS-Klassen, die Hintergrundfarbe festlegen, sollten auch eine passende Schriftfarbe festlegen. 

### ISSUE THREAD

**Issue by GiteKat** [codeispoetry/sunflower#182]
Beispiel _has-green-550-background-color_: Hintergrund ändert sich zu #3C8025, Schriftfarbe bleibt #363636;
Text ist schlecht lesbar, Textfarbe sollte in diesem Fall automatisch #fff sein.

**Comment by codeispoetry** [comment]
@designerin sollen wir eine default Farbe für jeden Hintergrund setzen? Aber dann müsste es ja auch default Werte für den Hintergrund geben, wenn man die Vordergrundfarbe wechselt.

Ich tendiere eher dazu, die Farbwahl komplett ind die Hände der Nutzenden zu legen ubd keine Farben vorzugeben. Wer den Hintergrund ändert, muss dann auch an die Vordergrundfarbe denken. Wie siehst Du das?

**Comment by GiteKat** [comment]
Ergänzend sei noch erwähnt, dass man mit WordPress in dem genannten Beispiel zwar theoretisch sehr leicht die Schriftfarbe selbst auf weiß ändern könnte, dann jedoch der eigene Text nicht mehr im Editor lesbar ist (weiß auf weiß), da WordPress zwar die Schriftfarbe übernimmt, nicht jedoch die Hintergrundfarbe aus der CSS-Klasse.

**Comment by codeispoetry** [comment]
danke für die Beschreibung. Die Hintergrundfarbe wird bei mir im Test auch angepasst. Wenn mal also Hintergrund z.B. auf grün setzt, wird er auch im Backend-Editor angepasst. Ist das bei Dir nicht so? Welche Version von sunflower hast Du?

**Comment by GiteKat** [comment]
sunflower Version: 1.0.0-beta-1 Das Problem sind Blöcke, bei denen WordPress keine Option bietet, die Hintergrundfarbe zu ändern (z.B. „Spalten“). Um darin einen Bereich mit Hintergrundfarbe zu erhalten, haben wir dem Block über „Erweitert“ > „Zusätzliche CSS-Klasse(n)“ die Klasse „has-green-550-background-color“ gegeben. Ich mail Dir ein konkretes Beispiel – vielleicht kennst Du einen eleganteren/einfacheren Weg.

**Comment by designerin** [comment]
konntet ihr hierfür eine Lösung finden? Ich schätze fast hier brauchen wir ein zusätzliches Feature, dass man Farben für einzelne Spalten im Editor anpassen kann und das entsprechend dort auch dargestellt werden kann? 

Würde auch sagen dass die Farbwahl komplett bei den Nutzer*innen liegen soll/darf – aber wenn man den Text im Editor nicht mehr sehen kann ist das natürlich schlecht.

**Comment by codeispoetry** [comment]
die Version 1.0.0-beta-3 müsste das behoben haben. Da werden die background-colors auch im im Backend angezeigt, wenn man sie als Klasse per Hand angibt.

**Comment by GiteKat** [comment]
Vielen Dank, passt!
