### ISSUE TITLE
Block 'neueste Beiträge' - sporadisch keine Änderungen möglich

### ISSUE THREAD

**Issue by Nachtmensch87** [codeispoetry/sunflower#189]
Nicht so wichtig, aber in dem Block 'neueste Beiträge' sind sporadisch keine Änderungen mehr möglich, nachdem die Seite einmal veröffentlicht wurde. Der Fehler tritt aber komischerweise nicht immer auf.

Es steht dann in dem Block: In diesem Block ist ein Fehler aufgetreten und es ist keine Vorschau möglich.

Ergänzend dazu wird in der Konsole auch folgender Text (zu allen Sunflower-Blöcken) ausgegeben:

The block "sunflower/latest-posts" is registered with an invalid category "sunflower-blocks".

**Comment by Nachtmensch87** [comment]
Ergänzung: Wenn ich eine Anzahl von maximal anzuzeigenden Beiträgen definiere, stimmt die chronologische Sortierung nicht mehr. Es wirkt dann sehr willkürlich.

**Comment by codeispoetry** [comment]
Hallo. Danke für den Bugreport. Ich kann das leider noch nicht reproduzieren. Der Fehler trat bei mir bisher nicht auf. Den Text auf der Konsole habe ich im Auge, das ist derzeit noch kein schlimmer Fehler. Wie ich die Meldung loswerde, weiß ich derzeit noch nicht. 

Die chronologische Sortierung stimmt bei mir, auch wenn ich eine maximale Anzahl angebe. In der linken Spalte die neusten, dann geht es in der rechts Spalte weiter. Es wird also spaltenweise sortiert. Das liegt daran, weil die Beiträge unterschiedlich hoch sind bzw. sein können, wegen der Vorschaubilder.

**Comment by Nachtmensch87** [comment]
Dann kannst du das Ticket hier schließen. Bezüglich der Sortierung weiß ich dann auch Bescheid. Danke!
