### ISSUE TITLE
Blog Stadard Post

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#19]
- [x] mehr Space zwischen Blog-Text und Seitenleiste
- [x] mehr Space zum Header Menü
- [x] mehr Space zwischen Beitragsbild und Text darüber und darunter
- [x] Beitragsbild dann so breit wie der Text und mit Radius 10px

**Comment by codeispoetry** [comment]
Alles erst mal erledigt. Wenn es passt, kannst Du das Ticket gerne schließen
