### ISSUE TITLE
Linien im Pullquote werden nicht angezeigt

### ISSUE THREAD

**Issue by Nachtmensch87** [codeispoetry/sunflower#190]
Linien des Pullquote-Blocks werden nicht angezeigt (bzw. nur im Editor)

**Comment by codeispoetry** [comment]
Hallo @designerin Wie soll denn der Block Pull-Quote formatiert sein?
Hier siehst Du ein Beispiel: https://sunflower-theme.de/demo/beispiel-seite/

**Comment by codeispoetry** [comment]
@designerin wenn das so passt, kannst Du das Ticket gerne schließen. Die Striche im Editor habe ich entfernt, weil sie derzeich auch im Frontend nicht angezeigt werden.

**Comment by designerin** [comment]
ich würde die Schriftgröße 
- [ ] auf 30px reduzieren
- [ ] für mobil auf 26px. Dann passt das
