### ISSUE TITLE
Links in Beiträgen werden nicht hervorgehoben

### ISSUE THREAD

**Issue by Nachtmensch87** [codeispoetry/sunflower#191]
Links in Beiträgen werden nicht hervorgehoben

**Comment by codeispoetry** [comment]
@designerin ist das so gewollt?

**Comment by codeispoetry** [comment]
Ich habe den Fehler gefunden. MIt einem Commit mit der Message "add latest posts to startpage" wurde das eingeführt. Aber das war dann leider global, und nicht nur für die latest posts auf der Startseite. Mit 1.0.2 wird das behoben sein.

**Comment by designerin** [comment]
https://sunflower-theme.de/demo/category/aktuelles/

hier wird jetzt der komplette Vorschautext als Link dargestellt. Kannst du ihn bitte wieder auf schwarz #363636 setzen?

**Comment by codeispoetry** [comment]
Ist in 1.0.3 behoben
