### ISSUE TITLE
https://www.sunflower-theme.de/ nicht aufrufbar

### ISSUE THREAD

**Issue by GiteKat** [codeispoetry/sunflower#194]
Bei einem Aufruf der Projekt-Website mit der Subdomain www erscheint ein Zertifikatsfehler:
[https://www.sunflower-theme.de/](https://www.sunflower-theme.de/)

**Comment by codeispoetry** [comment]
Hast du 1 Screenshot für mich mit dem genauen Fehler? Bei mir funktionierts.

**Comment by codeispoetry** [comment]
Danke, konnte den Fehler nachstellen, Screenshot brauche ich nicht mehr, ich guck mir das an

**Comment by codeispoetry** [comment]
Der Fehler mit dem Zertifikat scheint behoben, zumindest kommt er bei mir nicht mehr. Ich hoffe, dass das nicht nur an meinem Cache liegt. Wenn es auch bei Dir geht, kannst Du das Ticket gerne schließen.

**Comment by GiteKat** [comment]
Passt, Danke Dir!
