### ISSUE TITLE
Suche lässt sich nicht mehr ausblenden

### ISSUE THREAD

**Issue by GiteKat** [codeispoetry/sunflower#195]
Die Suche in der oberen Menüleiste lässt sich in Version: 1.0.2 nicht mehr, wie in der Dokumentation beschrieben, ausblenden:

```
.search {
    display: none;
}
```

[https://sunflower-theme.de/documentation/customcss/](https://sunflower-theme.de/documentation/customcss/)

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Ich habe das in der Doku ausgebssert. Der Code muss lauten
``
#topmenu-container .search, #topmenu-container .show-search {
    display: none !important;
}
``
