### ISSUE TITLE
feature: Zum Blog-Archiv nach Katgeorien ermöglichen

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#196]
Wenn Beiträge nach Katgeorien eingebunden sind führt "ZUM BLOG-ARCHIV" nicht nur zu den Beiträgen der Kategorie sondern zu allen Beiträgen.

**Comment by b90g** [comment]
[note self: https://helpdesk.verdigado.com/#ticket/zoom/20671 ]

**Comment by codeispoetry** [comment]
ist in 1.0.3 behoben

**Comment by b90g** [comment]
https://gruene-nf.de/gruene-vor-ort/pellworm/
hier scheint der link zum archiv nicht zu funktionieren auch andere Ortsverbände nicht,
- [x] kategorien geprüft.
- [x] Permalinkstruktur toogle durchgeführt

**Comment by codeispoetry** [comment]
Was ist denn an der entsprechenden Stelle im Backend eingetragen?

**Comment by b90g** [comment]
![Screenshot_2021-05-26 Seite bearbeiten ‹ BÜNDNIS 90 DIE GRÜNEN — WordPress](https://user-images.githubusercontent.com/63392812/119658905-f3526080-be2d-11eb-9a97-8b1baa92493a.png)


allerdings sehe ich gerade auch, dass einige redirekt plugins (403,404) aktiviert sind, ich frag mal nach ob das problem auch ohne plugins auftritt.

**Comment by b90g** [comment]
```
ich hab nun noch mal so gut wie alle Plug Ins deaktiviert und das Widget noch mal entfernt und neu eingefügt (das hatte zwischenzeitig mal geholfen, jetzt klappte es aber wieder nicht - obwohl ich seit der Änderung nichts an der Seite gemacht habe)
```

kam auf meine plugin anfrage zurück

**Comment by codeispoetry** [comment]
Ist an der stelle im Blockeditor im Backend vielleicht ein unsichtbares Leerzeichen? Könnte ich da mal Admin-Zugang bekommen?

**Comment by codeispoetry** [comment]
Die Kategorie "Pellworm" ist im Backend eingetragen, aber die gibt es gar nicht.

**Comment by codeispoetry** [comment]
Ich habe den Fehler behoben mit der  Version 1.1.7
