### ISSUE TITLE
Wiederholende Termine beim Kalenderimport

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#198]
Vgl: 
https://wolke.netzbegruenung.de/apps/calendar/p/4xoN5X9HqxXD8cGo
VS
https://gruene-treptow-koepenick.de/sunflower_event/

Teilweise fehlen auch reguläre Termine kann aber nicht nachvollziehen woher das verhalten kommt.

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Das mit den wiederkehrenden Termine liegt daran, dass solch ein wiederkehrender Termin im ics-File auch nur einmal erscheint, nicht aber jeder einzelne Termin dieser Serie. Dieses Verhalten muss ich im Import erst einmal nachbauen....

Welche regulären Temrine fehlen denn? Hast Du da ein Beispiel für mich?

**Comment by b90g** [comment]
der dritte mittwoch eines monats gibts einen politischen stammtisch, jeden donnerstag trifft sich die grüne jugend ost (siehe kalender im ersten beitrag, da kannst du glaube ich auhc ein ICS file bekommen zum testen :) )

**Comment by codeispoetry** [comment]
Danke. Das sind wiederkehrende Termine. Du sorachst auch von regulären Terminen

**Comment by codeispoetry** [comment]
Ab der Version 1.0.6. werden auch wiederkehrende Termine importiert. Bechte dazu bitte https://sunflower-theme.de/documentation/events/#anzahl-der-sich-wiederholenden-termine-beim-import-festlegen
