### ISSUE TITLE
Sunneblumengrafik durch SVG ersetzen

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#199]
Auf manchen Endgeräten sehen die Grafiken verschwommen oder unscharf aus.

**Comment by codeispoetry** [comment]
Hast du einen Link, welche Grafik du meinst? Das Logo im Header und Footer sind ja schon svg

**Comment by b90g** [comment]
Ich hätte das vielleicht prüfen sollen bevor ich ne Issue aufmache.. Ich frag nach ob eine andere Grafik damit gemeint war und schließe die Issue erst mal
