### ISSUE TITLE
Beiträge Übersicht

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#20]
- [x] können wir an dieser Stelle die Social Media Icons ausblenden? Schlagworte etc rutschen dann ganz nach links.
- [x] Links generell nicht unterstreichen. Farbe Grün passt
- [x] kleiner Pfeil bei "weiterlesen" weg 
- [x] "weiterlesen" hover-colour grün
- [x] "weiterlesen" rechtsbündig setzen (geht das)?
- [x] Autor*in in der Übersicht ausblenden (auf der jeweiligen Beitragsseite darf er erscheinen)
- [x] Wörter Anzahl 30

**Comment by codeispoetry** [comment]
Alles erst mal erledigt. Wenn es passt, kannst Du das Ticket gerne schließen

**Comment by designerin** [comment]
- [ ] Schlagworte und Weiterlesen etwas hoch rutschen
- [ ] Schlagworte kleiner, in 15 px

**Comment by codeispoetry** [comment]
Ich hab den Schlagworten die Klasse _small_ gegeben, statt ihnen direkt eine Schriftgröße zuzuweisen. Dann bleiben wir über viele Stellen vermutlich gleich.

**Comment by designerin** [comment]
Sehr gut, die Schrift passt.

- [ ] "Weiterlesen" bitte mehr Abstand zum unteren Rand
- [ ] oberste Headline auf der Übersichtsseite  "Aktuelles" gleicher Abstand zur Menüleiste wie auf den anderen Seiten
