### ISSUE TITLE
ICS import älterer Kalendereinträge

### ISSUE THREAD

**Issue by danijoo** [codeispoetry/sunflower#203]
Aktuell scheint der ICS import nur Events die in der Zukunft liegen zu importieren.  Es wäre schön, wenn man zumindest einmalig zb. durch setzen einer Checkbox auch alle vergangenen Termine importieren könnte, zb um sie später in Wordpress als Vorlage zu verwenden.

**Comment by codeispoetry** [comment]
danke für das Issue. Ich bin unschlüssig, ob das mehrere Personen benötigen. Du kannst es für Dich ja mal damit einbauen:
In der Datei *functions/icalimport.php* Zeile 30 ersetzen
`` $events = $ical->eventsFromRange('2017-03-01 12:00:00', '2023-04-31 17:00:00'); ``
