### ISSUE TITLE
ICS Import - Fehlender Eintrag.

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#204]
gleichen daten wie in #198 Termin am 8. Mai 2021 wird nicht dargestellt, auch via händischem reimport & cache löschen

Danach habe ich die veranstaltung umbenannt und nochmal neu importier, sie existert zwar aber wird falsch geparst oder so

https://gruene-treptow-koepenick.de/sunflower_event/mvv-bezirkswahlprogramm-2/

**Comment by codeispoetry** [comment]
note to myself: Import link https://wolke.netzbegruenung.de/remote.php/dav/public-calendars/4xoN5X9HqxXD8cGo/?export

**Comment by codeispoetry** [comment]
Bitte grade mal auf 1.0.8. up, darin müsste der Fehler behoben sein

**Comment by b90g** [comment]
https://gruene-treptow-koepenick.de/sunflower_event/ - Jain, die Termine werden angezeigt sind aber nicht mehr anklickbar Hoppla 404

**Comment by b90g** [comment]
Ausserdem ist ein eintägiger Termin aufeinmal 2 tägig.

**Comment by codeispoetry** [comment]
gehe mal in den Einstellunge bei Permalinks auf eine beliebige andere Permalinkstruktur. Speichern. Und danm wiede rauf die zurück, die du hattst.

**Comment by codeispoetry** [comment]
> Ausserdem ist ein eintägiger Termin aufeinmal 2 tägig.

Welcher denn?

**Comment by b90g** [comment]
resolved

**Comment by b90g** [comment]
der Termin für heute 19 Uhr ist wieder weg :(

Termin ist " Monthly on the third Wednesday "

https://wolke.netzbegruenung.de/apps/calendar/p/4xoN5X9HqxXD8cGo/dayGridMonth/now
https://gruene-treptow-koepenick.de/termine/

- [x] toggle permalink struktur
- [x] reimport

**Comment by codeispoetry** [comment]
Besteht das Problem noch?

**Comment by b90g** [comment]
Ja, der politische Stammtisch (19. Mai widerkehrender Termin 3 Mittwochd des MOnats) fehlt leider immer noch.

**Comment by codeispoetry** [comment]
Mit der Version 1.1.4. müsste der Fehler behoben sein

**Comment by b90g** [comment]
sieht gut aus.
