### ISSUE TITLE
unterseiten shortcode

### ISSUE THREAD

**Issue by quabolasse** [codeispoetry/sunflower#205]
Urwahl3000 stellt den shortcode 'unterseiten' bereit, den wir zur Auflistung unserer Vorstandsmitglieder, Landtagsabgeordneten, Mitarbeiter verwenden (https://gruene-rd-eck.de). Gibt es dafür einen empfohlen Ersatz? Oder eine Alternative?

Vielen Dank,
Lasse

**Comment by codeispoetry** [comment]
Hallo Lasse,

vielen Dank für das Issue. Es gibt die Block-Vorlage "Vorstand", hier siehtst Du sie in Aktion
https://sunflower-theme.de/demo/partei/vorstand/

Blockvorlagen findest Du im der Blockauswahl in einem eigene Reiter.
Hilft Dir das weiter?
