### ISSUE TITLE
Beiträge und Termine - Facebook teilen

### ISSUE THREAD

**Issue by Nachtmensch87** [codeispoetry/sunflower#206]
Es können keine Beiträge über den Facebook Button geteilt werden. Es wird ein Fehler von Facebook ausgewiesen. 
Bei den Terminen funktioniert das Teilen prinzipiell, der Link wird aber falsch übergeben.

P.S. Ich weiß nicht, ob das eine Angelegenheit von Facebook ist, aber: Wenn ich in Facebook einen Link bzw Beitrag teile (https://www.gruene-gifhorn.de/2021/03/24/wie-sieht-die-tierhaltung-der-zukunft-aus-und-welche-rechte-haben-tiere/), wird das Beitragsbild angezeigt. Mit Sunflower wird das Bild nicht angezeigt.

**Comment by codeispoetry** [comment]
Der zweite Teil ist ab 1.0.11 enthalten, das sind OpenGraph-Tags, die sunflower nun auch auspielt.
Auch die Termine müssten rchtig verlinkt sein.

Welcher Fehler wird denn von Facebook ausgewiesen? Ich kann das leider nicht selbst testen, weil ich kein Facebook-Konto habe.
