### ISSUE TITLE
Typografie divers

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#21]
- [x] H1 Arvo Gruen Regular, 52px
- [x] H2 Arvo Gruen Regular, 30px
- [x] H3 PT Sans Bold, 30px
- [x] H4 PT Sans Regular, 30px
- [x] H5 PT Sans Bold, 22px
- [x] H6 Arvo Gruen Regular 17px
- [x] Tags & Kategorien  PT Sans Regular, 15px 
- [x] Bildunterschrift  PT Sans Regular, 15px
- [x] Blockquote wie H2 nur eingerückt
- [x] Fließtext PT Sans Regular, 19px
- [x] Achtung: es gibt eine andere PT Sans mit Leerzeichen (aktuell verwendet: PTSans) bitte die mit Leerzeichen verwenden (da sieht der Bold Schnitt sehr anders aus)

Ich schicke dir noch mal ein PDF mit zum besseren Verständnis
Wenn du an manchem Punkten anderer Meinung bist oder verbesserungsvorschläge hast, sag gerne bescheid

**Comment by codeispoetry** [comment]
Kannst Du Dir alles hier anschauen
https://wordpress.tom-rose.de/demo/?p=177

**Comment by designerin** [comment]
durch die neue Headline Zuweisung haben sich natürlich ein paar Fehlerchen eingeschlichen.
zB:
- [ ] Beim Logo im Header erste Textzeile wieder auf ArvoGruen stellen. 

Für den Headerbereich wird es sicher noch Anpassungen geben. dazu melde ich mich noch mal gesammelt

**Comment by codeispoetry** [comment]
Kann das Ticket geschlossen werden?
