### ISSUE TITLE
Image captions featured image

### ISSUE THREAD

**Issue by danijoo** [codeispoetry/sunflower#210]
Wir benutzen im alten Theme sehr oft die Image Caption um Copyright Informationen für die Featured Images zu setzen. Es wäre schön wenn das neue Theme das auch unterstützen würde.

**Comment by codeispoetry** [comment]
@designerin wo soll diese Information hinkommen und wie soll sie ausshen?

**Comment by danijoo** [comment]
Ich habe es jetzt erstmal unten rechts ins eck gesetzt. vielleicht könnt ihr ja darauf aufbauend was schönes designen oder es übernehmen: [https://imgur.com/460sHB9l.png](https://imgur.com/460sHB9l.png)

**Comment by designerin** [comment]
hi @danijoo, Danke für die Anregung. Ich glaube du hast einen flaschen Link gesetzt.  Kannst du mir noch mal dein Beispiel zeigen? Dann kann ich sehen ob wir das so übernehmen oder noch etwas anpassen würden.

**Comment by danijoo** [comment]
Hi @designerin 

Bei mir funktioniert der link. Habe das Bild trotzdem nochmal angehängt. Die Image caption befindet sich klein rechts unter dem Bild (Name, CC-BY-SA in diesem Falle) 

![460sHB9l](https://user-images.githubusercontent.com/4690162/115027317-d8520f80-9ec3-11eb-9375-62065d4490fd.jpeg)

**Comment by designerin** [comment]
Bildunterschrift soll so aussehen:

- [ ] rechts unter dem Bild
- [ ] 15px, Farbe wie Fließtext
- [ ] margin-right:0.3em
- [ ] margin-top:0.5em

Bei gallery (.wp-block-gallery .blocks-gallery-item figcaption)
passt es schon fast:

- [ ] zusätzlich noch: margin-right:0.3em


genau so dann bitte für 

- [ ] normale Bilder in Beiträgen und auf Seiten
- [ ] Beitragsbilder auf der Beitragsseite
- [ ] wenn möglich auch für Cover

**Comment by danijoo** [comment]
Hab's soweit angepasst:

> * [x]  rechts unter dem Bild
> * [x]  15px, Farbe wie Fließtext
> * [x]  margin-right:0.3em
> * [x]  margin-top:0.5em
> * [x]  zusätzlich noch: margin-right:0.3em
> 
> genau so dann bitte für
> * [x]  normale Bilder in Beiträgen und auf Seiten
> * [x]  Beitragsbilder auf der Beitragsseite
> * [ ]  wenn möglich auch für Cover

Cover ist schwierig. Der Block kommt wohl noch direkt von wordpress und sieht keine captions vor?

**Comment by codeispoetry** [comment]
Hallo @danijoo , danke für die Änderungen in Deinem repo. Könntst Du einen pull-request stellen, damit ich es übernehmen kann?

**Comment by codeispoetry** [comment]
@designerin 
Passt das so:
- https://sunflower-theme.de/demo/neckarstrasse-wird-fahrradstrasse/
- https://sunflower-theme.de/demo/critical-mass/
@danijoo, danke für den PR.

**Comment by designerin** [comment]
da hängt noch ein 5px padding nach oben drin, das müsste noch raus wenn das geht. (ist aktuell zu weit weg vom Bild)
und bei den Galeriebildern muss bitte noch  margin-right:0.3em dazu.
ansonsten passt es so.

**Comment by danijoo** [comment]
> da hängt noch ein 5px padding nach oben drin, das müsste noch raus wenn das geht. (ist aktuell zu weit weg vom Bild)
> und bei den Galeriebildern muss bitte noch margin-right:0.3em dazu.
> ansonsten passt es so.

padding ist raus und gallery müsste jetzt auch wie geplant aussehen in der PR.
