### ISSUE TITLE
Ausklappmenüs Mobile

### ISSUE THREAD

**Issue by mnbvghw** [codeispoetry/sunflower#211]
Ich finde es seit 1.10 schwer auf dem Handy die Untermenüpunkte in der Menüleiste aufzuklappen. Geht es nur mir so?

**Comment by codeispoetry** [comment]
Der klickbare Bereich um den Pfeil geht bis zum rechten Rand, man muss ihn nicht genau treffen.

**Comment by designerin** [comment]
bei mirklappt das menü nicht mehr auf mobile. (auf der demoseite)

**Comment by designerin** [comment]
Wir könnten das Menü mobil auch erst mal komplett geöffnet darstellen ohne dropdown-funktion.

**Comment by codeispoetry** [comment]
Es berichtet sonst niemand von diesem Fehler.

**Comment by digicommons** [comment]
> Der klickbare Bereich um den Pfeil geht bis zum rechten Rand, man muss ihn nicht genau treffen.

Da der Pfeil relativ nah am Menütext ist, passiert es mir öfter, dass ich durch einen Fehlklick auf die jeweilige Unterseite gelange, anstatt das Drop-Down aufzuklappen. Erst nach einigen Versuchen habe ich rausgefunden, dass der klickbare Bereich bis zum rechten Rand geht.
Wäre es evtl. möglich, den Pfeil in der mobilen Ansicht auf die rechte Seite zu rücken? Das wäre imho intuitiver.

**Comment by codeispoetry** [comment]
@designerin Sollen wir den Pfeil nach rechts rücken?

**Comment by designerin** [comment]
Ja, den Pfeil gerne nach rechts, in Farbe #201D1B und vergrößern auf font-size: 18px.

**Comment by strombert** [comment]
Ich will mich hier auch anschließen - > Dass Untermenü hab ich jetzt nach langem probieren erst aufbekommen als ich hier gelesen habe dass man rechts danaben klicken muss. Entweder den Pfeil vergrößern oder eine andere Lösung :/

**Comment by codeispoetry** [comment]
Der Pfeil ist ab Version 1.1.0. deutlicher zu sehen
