### ISSUE TITLE
Absätze werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#212]
ich habe an vielen Stellen mit einem zusätzlichen Absatz gearbeitet. Dieser wir nicht mehr angezeigt. Das ist eigentlich auch für Nutzer die einfachste Möglichkeit um manuell Abstände einzufügen. Kannst du das bitte wieder aktivieren?

**Comment by codeispoetry** [comment]
Kannst du mir eine konkrete Stelle nennen bitte?

**Comment by designerin** [comment]
https://sunflower-theme.de/demo/typographie/

hier  zB. ist aber an allen Stellen wo ein zusätzlicher absatz im editor gesetzt wird.

**Comment by codeispoetry** [comment]
Leere Absätze sollen auch gar nicht angezeigt werden. Für Abstände gibt es den Block Abstandshalter. Es wundert mich, dass die jemals angezeigt wurden.

**Comment by designerin** [comment]
ok, weiß ich nicht aber wurde so angezeigt.

kannst du dafür dann den normalen Absatz dann bitte vergrößern? auf 2rem. 

Finde das mit den Abständen insgesamt noch problematisch wenn ich mir die bestehenden Seiten so anschaue.. oft ist alles total zusammengeklatscht und ohne Abstände. Das gefällt mir überhaupt nicht.

Idealerweise müssten alle Headlines von grund auf einen margin-top und margin-bottom von 1em bekommen. Dann würde das schon viel besser aussehen. Und vielleicht auch Bilder. Damit das nicht alles zusammenklatscht wenn sich jemand nicht die Mühe macht überall manuell Abstandhalter einzusetzen.. oder? Ich weiß das ist jetzt noch mal Arbeit – für mich auch. aber so können wir das auf keinen Fall lassen.

kannst du das mal irgendwie testen? und wir schauen dann wo es auswirkungen hat, die nicht gewünscht sind?

**Comment by designerin** [comment]
vllt können wir dazu die Woche noch mal sprechen.
