### ISSUE TITLE
Suchergebnisse: Design

### ISSUE THREAD

**Issue by danijoo** [codeispoetry/sunflower#213]
Hi,

Die Seite mit den Suchergebnissen weicht ziemlich vom restlichen design ab. Z.b.:
- Bild hat keine Runden Ecken
- Excerpt Text ist Grün und Unterstrichen
- Bilder werden zt. nicht richtig zentriert dargestellt.

Sichtbar u.a. hier: https://sunflower-theme.de/demo?s=Neckar

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Wird in 1.0.11 enthalten sein
