### ISSUE TITLE
Unterschiedliche Breite von Absatz und Blog-Übersicht

### ISSUE THREAD

**Issue by andra03** [codeispoetry/sunflower#214]
Normale Seite (ohne "Layout selbst gestalten")
Block: Titel 
Block: Absätze 
Block: Spalten
Block "Neueste BEiträge einer Kategorie"

Der letzte Block ist breiter als die anderen. 
Warum?

 
![image](https://user-images.githubusercontent.com/74626015/115119523-0c533080-9fa9-11eb-8c47-63ee4db1159a.png)

**Comment by codeispoetry** [comment]
Danke. Hast du einen Link für mich, wo ich das mal ansehen kann?

**Comment by andra03** [comment]
Klar: https://gruene-bergamlaim-trudering-riem.de/berg-am-laim/antraege-der-gruenen-im-ba-14/
Hast du das Login noch?

**Comment by codeispoetry** [comment]
Anders als die anderen Sektionen ist das eine Gruppe.
Wenn Du die anderen Sektionen auch jeweils in eine Gruppe packst, sind alle gleich breit.

https://sunflower-theme.de/documentation/homepage/#sektionen-erstellen

Ich befürchte, da muss ich mir noch mal eine Lösung überlegen, weil wir nicht erwarten können, dass jmd. Gruppen anlegt...

**Comment by andra03** [comment]
Gruppen anzulegen ist eine höchst kniffelige Angelegenheit und braucht gutes Mausgefühlt. Außerdem ist es wirklich nicht die offensichtlichste Lösung. Wenn du was anderes weißt, wäre es gut. Danke!
