### ISSUE TITLE
2 Spaltig 

### ISSUE THREAD

**Issue by JanLauchringen** [codeispoetry/sunflower#215]
Hallo Liebes Team,
ist ein 2 Spaltiges Layout (zuschaltbar) mit Seitenleiste für Widgets geplant?

**Comment by designerin** [comment]
hallo, eigentlich ist es nicht geplant. Aber scheinbar gibt es sehr viele Nutzer für die das Schwierigkeiten macht. Daher würde ich gerne eine Lösung finden, diese zu beheben.

Es gibt eine Widget Area am Seitenende. Wir haben uns dafür entschieden, diese nach unten zu stellen, da man so mehr Freiheit für die Gestaltung der Seiten mit den Blöcken hat. 

Kannst du mir sagen, welche Widgets hier deiner Meinung nach nicht funktionieren, oder ist das Problem, dass sie am Seitenende erst kommen und dadurch nicht präsent genug sind?
