### ISSUE TITLE
Personenblöcke abstand mobile

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#216]

**Comment by andra03** [comment]
Und Desktop auch.

**Comment by codeispoetry** [comment]
Die Vorlage der kommenden Version 1.1 wird die Abstände enthalten. Die werden allerdings nicht automatisch übernommen, wenn man die Blöcke schon nutzt.

Dazu bitte bei den Spalten als zusätzliches CSS ein ``mb-md-4`` hinzufügen. Dann passt es mit den Abständen.

**Comment by b90g** [comment]
![Screenshot 2021-08-10 at 09-56-54 Screenshot_2021-08-10_09-55-08 png (PNG Image, 3840 × 2160 pixels)](https://user-images.githubusercontent.com/63392812/128830720-0e77b534-685d-4eb1-a1d3-14cdc627ebf3.png)
Desktop

![Screenshot 2021-08-10 at 09-57-09 Screenshot_2021-08-10_09-55-08 png (PNG Image, 3840 × 2160 pixels)](https://user-images.githubusercontent.com/63392812/128830739-66a451c5-9ac2-4c30-bc76-392d491c8db0.png)
mobil nebeneinander (erste zeile)

![Screenshot 2021-08-10 at 09-57-23 Screenshot_2021-08-10_09-55-18 png (PNG Image, 3840 × 2160 pixels)](https://user-images.githubusercontent.com/63392812/128830779-2e06b2ba-6778-4f4b-8b52-191f76f9c924.png)
mobil erste zu zweite zeile.

wäre schön wenn die einheitlich wären, aber kein muss.
