### ISSUE TITLE
Metadaten-Mini-Editor kann im Chrome nicht im Visuell-Modus 

### ISSUE THREAD

**Issue by andra03** [codeispoetry/sunflower#218]
In den Visuell-Tab lässt sich nichts reinschreiben / pasten. Und wenn ich vom Text-Tab was eingebe und in den visuell-Tab wechsle, ist nichts zu sehen. 
Chrome geht nicht. Edge schon.

**Comment by codeispoetry** [comment]
Besteht das Problem noch? Ich befürchte, das ist kein Issue für _sunflower_, sondern für _WordPress_ an sich
