### ISSUE TITLE
Beitragsseite

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#22]
- [x] Kann man die Text und Bildbreite auf der Beitragsseite schmaler machen? ca. 800px fänd ich hier gut. (je nachdem was mit dem Grid geht)
- [x] Abstand zwischen Datum und Beitragsbild vergrößern
- [x] Könnte man bei der Dachzeile den Buchstabenabstand noch etwas vergrößern?

**Comment by codeispoetry** [comment]
- [ ] col-12 aber col-md-10 col-lg-8
