### ISSUE TITLE
Termine-Menüeintrag funzt seit 1.0.12 nicht mehr

### ISSUE THREAD

**Issue by andra03** [codeispoetry/sunflower#220]
Vorhin ging es noch, den Termin-Menü-Eintrag gemäß Doku einzurichten. jetzt kommt ein Hoppla. 
Liegt es an 1.0.12 oder an der Uhrzeit?

Viele Grüße
Alexandra

**Comment by codeispoetry** [comment]
Es liegt wohl lieder am Update. Du musst in den Einstellungen den Permalink irgenwohin ändern (egal wohin) und dann wieder zurück ändern. Dann müsste es gehen

**Comment by andra03** [comment]
Workaround works
