### ISSUE TITLE
Blogübersichten Darstellungsfehler

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#222]
<img width="1219" alt="grafik" src="https://user-images.githubusercontent.com/78264333/115281575-760a4080-a149-11eb-8f6c-c46545e5ea3c.png">

hier ist ein Abstand, der da nicht sein sollte (padding bottom 35px)

**Comment by codeispoetry** [comment]
Wie ist die URL

**Comment by designerin** [comment]
https://gruene-bergamlaim-trudering-riem.de/trudering-riem/riemer-park/
hier zb
