### ISSUE TITLE
Terminübersichten nach Kategorien

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#224]
Hab ich nicht gefunden, geht das nicht? Kommt das noch?

(anfrage aus Chat, ich konnte nichts dazu sagen)

**Comment by Drakemaster** [comment]
Wenn du auf einer Seite [wpcalendar] einfügst, bekommst du so eine Übersicht:
https://sunflower-theme.de/demo/termine/

**Comment by codeispoetry** [comment]
Gibt es ja schon: https://sunflower-theme.de/demo/termine/

**Comment by b90g** [comment]
insgesamt ja, aber in dem fall wollten sie für jeden OV eine terminseite anlegen die direkt auf  eine bestmmte kategorie zeigt.

**Comment by codeispoetry** [comment]
Ab Version 1.1.0 wird ein # an die URL gehängt, damit kann man direkt auf eine Event-Kategorie verlinken
