### ISSUE TITLE
Beitragsseite lässt sich nicht bearbeiten

### ISSUE THREAD

**Issue by OlavTeichert** [codeispoetry/sunflower#225]
Hallo, bei mir lässt sich die Beitragsseite nicht bearbeiten. Zwar erscheinen die Beiträge, aber darüber erscheint der Titel der Homepage. Ich möchte aber eine eigene andere Titelüberschrift vergeben, so wie auf Eurer Demoseite "Aktuelles". Besten Dank

![Bildschirmfoto 2021-04-21 um 13 56 33](https://user-images.githubusercontent.com/82946877/115549895-7de0f680-a2a9-11eb-9bd9-10dedcb2d44f.png)

**Comment by Drakemaster** [comment]
Dieses Theme arbeitet mit Blöcken. Nimm eine leere Seite und füg einen Beitragsblock hinzu.
![block](https://user-images.githubusercontent.com/34986665/115622243-e2c33d80-a2f7-11eb-9e98-fdb7ebf14f49.PNG)
