### ISSUE TITLE
Block-Abstand sehr gering

### ISSUE THREAD

**Issue by Drakemaster** [codeispoetry/sunflower#227]
Wenn man unter einen Beitrags-Block einen Termin-Block setzt, sind die Objekte sehr eng aufeinander.
![Abstand](https://user-images.githubusercontent.com/34986665/115623875-10a98180-a2fa-11eb-9e7d-4807f9e4770c.PNG)

**Comment by benjdi** [comment]
Wenn du das als Startseite nutzen willst, dann probier mal den Knopf "Layout selber gestalten" im Seitenmenu aus.
Dann werden größere Abstände eingefügt(jedoch an manchen Stelle auch Abstände verkleinert und der Titel wird versteckt).

![Screenshot 2021-04-23 122803](https://user-images.githubusercontent.com/83068490/115858559-66cc1100-a42f-11eb-8db9-57513ade82fb.png)
