### ISSUE TITLE
Links auf Bildern sind nicht klickbar

### ISSUE THREAD

**Issue by andra03** [codeispoetry/sunflower#228]
Hinterlege ein Bild mit einem Link, 
nicht klickbar --> Schade. 

Letzer Versuch hier sichtbar bzw. nicht sichtbar: Gelber Block mit PRessestimmen. https://schneller-radweg-muenchen-ebersberg.de/

Viele Grüße, Alexandra

**Comment by codeispoetry** [comment]
Im test hat es bei mir funktioniert. Ich vergesse manchmal, nach dem LInk setzen, in dem Popup-Menü auf dieses runde Pfeilchen zu klicken, damit der Link tatsächlich gespeichert wird. Hast Du auf dieses Pfeilchen geklickt?

**Comment by codeispoetry** [comment]
Ich schließe des Ticket einstweilen. Wenn noch was ist, melde Dich bitte.
