### ISSUE TITLE
tabs hinzufügen

### ISSUE THREAD

**Issue by catheien** [codeispoetry/sunflower#229]
ich möchte gerne tabs einfügen, um etwa Kontaktdaten oder eine Liste von Beiträgen einfügen zu können

**Comment by codeispoetry** [comment]
Das wird es frühestens in der nächsten Hauptversion 2.0 geben, wann das sein wird, ist derzeit unklar. Ich habe das Ticket gelabeld und schließe es einstweilen.

**Comment by codeispoetry** [comment]
Dazu gibt es schon ein Ticket #84
