### ISSUE TITLE
BUG: Kontaktformular: In Mutlisites nur als Superadmin

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#230]
In Multisite installationen lässt sich der Block Kontaktformular nur dann fehlerfrei einrichten wenn  es ein "Superamin" macht

Sonst sieht es im SiteAdmin so aus: https://wordpress02.gcms.verdigado.net/testseite-willi-april/kontakt/

Wenn ich als Netzwerk-Admin drauf gehe kann ich den block wiederherstellen und anschließend wird er auch orrekt dagestellt

Eine Email-Adresse für das Formular ist in den sunflower-einstellungen eingetragen

**Comment by codeispoetry** [comment]
Hint: https://github.com/WordPress/gutenberg/issues/15137

**Comment by codeispoetry** [comment]
https://sunflower-theme.de/documentation/faq/#in-multisite-funktioniert-das-kontaktformular-nicht
