### ISSUE TITLE
YouTube-Komponenten mit erweitertem Datenschutzmodus

### ISSUE THREAD

**Issue by OlavTeichert** [codeispoetry/sunflower#231]
Hallo zusammen,
das Einbetten von Youtube unter erweitertem Datenschutzmodus habe ich nicht hinbekommen.
Vielen Dank und viele Grüße.

**Comment by codeispoetry** [comment]
Das Theme ist dafür nicht der richtige Ort. Vielleicht gibt es hier Hilfe: https://chatbegruenung.de/channel/sunflower-wordpress
