### ISSUE TITLE
Standard-Einstellungen für Termine

### ISSUE THREAD

**Issue by digicommons** [codeispoetry/sunflower#232]
Im Kal3000-Terminkalender im Theme Urwahl3000 gibt es die Möglichkeit, unter Termine->Einstellungen Standard-Werte für Termine festzulegen. Das ist besonders bei Koordinaten und Adressen hilfreich, wenn diese regelmäßig gleich bleiben.

![image](https://user-images.githubusercontent.com/43313518/116489832-2be63500-a896-11eb-816c-48c7f6142f2e.png)

Wäre eine ähnliche Funktion auch in Sunflower denkbar/möglich?

**Comment by codeispoetry** [comment]
Derzeit wird der letzte Ort gemerkt und beim nächsten Mal wieder angezeigt.

Die gewünscht Funktion kommt ggf. im nächste Hauptrelease. Ich tagge das mal entsprechend.

**Comment by codeispoetry** [comment]
Das Ticket wird einstweilen geschlossen, ist aber passend getaggt, damit es nicht vergessen wird

**Comment by codeispoetry** [comment]
Das Problem ist, dass ich entweder die letzte gemerkte Einstellung anzeigen kann *oder* die Voreinstellung. Deshalb kann ich beides nicht gleichzeitig umsetzen. Ich würde es bei dem aktuellen Feature "Merke letzte Einstellung" belassen.
