### ISSUE TITLE
Custom Favicon

### ISSUE THREAD

**Issue by digicommons** [codeispoetry/sunflower#233]
Im Theme-Customizer fehlt die Option, ein eigenes Favicon festzulegen. Habe ich die Option anderswo übersehen oder werden eigene Favicons noch nicht unterstützt?

**Comment by codeispoetry** [comment]
Als Favicon wird die Sonnenblume gesetzt. Ein eignes Favicon kann über ein Childtheme eingebunden werden.

**Comment by digicommons** [comment]
Alles klar, danke für die Erklärung.

Ich kann mir vorstellen, dass das Thema Childtheme öfter auftauchen wird. Ist es denn möglich, Anleitungen/Unterkapitel zum Theme-Handbuch per Git beizusteuern oder handhabt ihr das lieber zentral?

**Comment by codeispoetry** [comment]
Gerne per git ein pullrequest.
