### ISSUE TITLE
Termin-Schlagworte/Kategorien in Termin-Editor festlegen

### ISSUE THREAD

**Issue by digicommons** [codeispoetry/sunflower#234]
Schlagworte können bei Terminen (soweit ich sehen kann) derzeit nur per QuickEdit festgelegt werden. Für einen schnellen Workflow wäre es hilfreich, wenn Schlagworte auch in der Seitenleiste im Termin-/Block-Editor ausgewählt/erstellt werden könnten.

(Optionales enhancement: Kategorie als Standard-Wert in globalen Termineinstellungen festlegen (siehe #232)

**Comment by codeispoetry** [comment]
Ab Version 1.1.0 kann man das machen
