### ISSUE TITLE
Termine: Strukturierte Daten mit Schema.org-Markup

### ISSUE THREAD

**Issue by digicommons** [codeispoetry/sunflower#235]
Termin-Daten werden im Quellcode bisher nur als einfacher Text dargestellt. Eine zusätzliche Darstellung der Termin-Daten im Schema.org-Markup sollte die Indexierung durch Suchmaschinen erleichtern.

**Comment by codeispoetry** [comment]
Das planen wir für das nächste Hauptrelease. Das kann aber noch einige Zeit dauern.

**Comment by codeispoetry** [comment]
Das Ticket wird hier zwar geschlossen, ist aber im Project Feature-Requests sichtbar, weil es entsprechend getaggt ist.

**Comment by codeispoetry** [comment]
Ab Version 1.1.3. sind auch strukturierte Daten im json-ld-Format bei Events enthalten

**Comment by digicommons** [comment]
Wunderbar, funktioniert einwandfrei. Vielen Dank für die schnelle Implementierung!
