### ISSUE TITLE
Senkrechte Bilder

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#238]
Bei Bildern die Hochkant sind wird in dem Betröge Block das Bild in der größtmöglichen Form dargestellt.. also wenn das bild 10000 Pixel lang wäre und 5 pixel breit habe ich den eindruck dass der Block das Bild so lange stretchen würde bis es die breite erreicht hätte egal wie lang es ist.

**Comment by designerin** [comment]
Idealerweise würden natürlich die Nutzer*innen keine proportional so hochformatigen Bilder als Beitragsbilder verwenden, da sie einfach nicht geeignet sind. (hochformat für web ist in den allermeisten Fällen schwierig) Aber ich verstehe das Problem für Anwender*innen, die das Bildmaterial nicht entsprechend vorbereiten können.

Es war als Vorteil gedacht, dass man hier einen Spielraum hat aber ich verstehe und sehe dass das vielerorts Probleme macht. Alles was über ein quadratisches Format hinausgeht sieht nicht gut aus.

Meint ihr es wäre besser die Bilder auf ein fixes Format einzuspiegeln?

Mein Vorschlag:
generell empfohlene Dateigröße/Format: 900x600px (bzw idealerweise 1.800x1.200px für Retina)

Beitragsübersicht Bild wird zugeschnitten auf 576x380px
Beitragsbild im Beitrag selbst wird zugeschnitten auf: 876x580px

Bilder proportional einspiegeln in dieses Format, wird dann zwangsweise seitlich oder oben und unten abgeschnitten was proportional übersteht.

@codeispoetry: was meinst du? könnte man das als **zusätzliche Einstellungsmöglichkeit** in der Art "Bilder zuschneiden auf Idealformat" anbieten, sodass Nutzer wählen können ob es zugeschnitten wird oder wie aktuell in "voller Länge" gezeigt wird?

**Comment by b90g** [comment]
Klingt super. Auch möglich wäre ein blur-Effekt auf die Seiten zu legen wie es bei Instagram oder so passiert. damit das Bild zwar ganz drauf ist und leider auch kleiner wird, aber das Format des Beitragsvorschaubilds nicht üebermäßig gezogen wird?

**Comment by codeispoetry** [comment]
Ist Dir damit geholfen, dass Du ein custom-css einfügst:
``.latest-posts .post-thumbnail{
overflow:hidden;
height:200px;}
`.latest-posts .post-thumbnail img{
margin-top:-50%;
}
``

**Comment by b90g** [comment]
mir nicht, weil ich keine änderungen am theme vornehmen möchte, aber ich gebe das gerne mal an die leute weiter die deswegen angefragt haben.
