### ISSUE TITLE
/termine 404 bei englischer Spracheinstellung

### ISSUE THREAD

**Issue by danijoo** [codeispoetry/sunflower#240]
- Theme Version: 1.0.12
- Sprache der Website (Einstellungen-Allgemein-Sprache): Deutsch
- Sprache des Adminaccounts: Englisch

Bei uns funktionierten die `/termine` links nicht. Allerdings waren Termine unter dem slug `/events` erreichbar. Ich konnte folgenden Fehler reproduzieren:

- Stelle ich meinen admin account auf Deutsch, und regeneriere die Permalinks wie in der Anleitung beschrieben, funktionieren `/termine`
- Stelle ich meine Sprache wieder auf Englisch zurück, funktioniert es anfangs.
- Sobald ich aber die Permalinks ändere, wird der slug `/termine` wieder durch `/events` ersetzt, das theme erwartet aber immer noch dass `/termine` vorhanden ist, wodurch alle links im `404` enden
- Stelle ich nun wieder auf Deutsch um und regeneriere Links, geht wieder alles
- Das ganze ist nicht nur für den eingeloggten account "broken". Die Links gehen für niemanden sobald man von einen englischen Profil die Permalinks ändert. 

Meine Vermutung ist das die slugs abhängig von der Sprache des Admins übersetzt werden (termine vs. events). Das sollte nicht sein. Links sollten unabhängig der Profileinstellung eines Seitenbereibers sein und (wenn überhaupt) von der Sprache der Website (Einstellungen->Allgemein->Sprache) abhängen. Da sich `category` mit der Spracheinstellung nicht ändert, erwarte ich das auch für `/termine`.

**Comment by codeispoetry** [comment]
Danke für den auführlichen Bugreport. Ich hielt das zunächst für ein Feature, dass es im Englischen dann events heißt. 
Weil das Theme fast ausschließlich auf Deutsch verwendet wird, würde ich den Slug hard coden in termine. Was hälst Du von dieser Lösung?

**Comment by codeispoetry** [comment]
Der Slug wird ab Version 1.1.3. nicht mehr übersetzt sondern heißt immer "termine".
