### ISSUE TITLE
Social Media Buttons on top please!

### ISSUE THREAD

**Issue by ffmer32** [codeispoetry/sunflower#242]
Hallo, Social Media ist fast wichtiger als die Webseite, deshalb sollten die Buttons OEBEN auf der webseite sein und schnell per Symbol zugänglich. So wie es bei der urwahl händisch möglich war. 
Gruß

**Comment by codeispoetry** [comment]
Die Position am unteren Rand folgt der Regel, dass es sinnvoll ist, zuerst einen Beitrag zu lesen, bevor man ihn teilt.

Wen Du die Postion ändern willst, kannst Du das über ein Childtheme lösen. Du musst an der gewünschten Stelle ein
`` sunflower_the_social_media_sharers(); `` einfügen.
