### ISSUE TITLE
Button Blog-Archiv

### ISSUE THREAD

**Issue by mnbvghw** [codeispoetry/sunflower#243]
Der Link zum Blog Archiv unter den aktuellen Artikeln auf der Startseite wird in der Mobile Ansicht nicht angezeigt. In der Desktop Ansicht schon. Ist das gewollt?

**Comment by codeispoetry** [comment]
Ups. Danke dür den Hinweis. Ändere ich asap

**Comment by codeispoetry** [comment]
In Version 1.1.2 ist der Fehler behoben
