### ISSUE TITLE
API Access

### ISSUE THREAD

**Issue by danijoo** [codeispoetry/sunflower#246]
Derzeit sperrt das Theme durch codeispoetry/sunflower@5251a057c980a25cd352cc5c570c3014df4d3591 generell den Zugang zur Webapi für nicht angemeldete Benutzer.

Dadurch funktionieren viele Plugins nicht mehr, die darauf aufbauen (WP Analytics, Contact Form, ..). Auch News Apps nutzen die API zt. Warum wird das durch das Theme gesperrt?

**Comment by codeispoetry** [comment]
Aus Sicherheitagründen. Ich kann da einen Schalter einbauen, dann kann man es selbst beeinflussen.

**Comment by danijoo** [comment]
Ich sehe den Sicherheitsaspekt nicht wirklich (Die Daten der API sind ja auch anders öffentlich einsehbar).
Wie wäre es statt dessen ein Plugin in die Liste der suggested Plugins zu übernehmen das das löst?

**Comment by codeispoetry** [comment]
Ja, Du hast recht. Das ist auch nicht Aufgabe des Themes. Das kommt also komplett raus. Kannst gerne einen PR stellen. Ansonsten mach ich es die nächsten Tage.

**Comment by codeispoetry** [comment]
ab Version 1.1.5 (heute abend) wird die API zugänglich sein.
