### ISSUE TITLE
Block in Akkordion

### ISSUE THREAD

**Issue by catheien** [codeispoetry/sunflower#247]
Gestaltungstechnisch wäre es schön, Blöcke ins Akkordion packen zu können. Bisher ist meines Wissens nur Text möglich. Viele Dank!

**Comment by codeispoetry** [comment]
In der nächsten Version wird es eine Styleanpassung für das Plugin Accordion Blocks geben. Dann kannst Du dieses Plugin nutzen und es ist passend gestyled.

**Comment by codeispoetry** [comment]
Die Styles für das Plugin Accordion sind nun auch eingebraut. https://sunflower-theme.de/documentation/accordion/
