### ISSUE TITLE
„Zum Blog-Archiv“ mit Permalink

### ISSUE THREAD

**Issue by gumby-man** [codeispoetry/sunflower#248]
Der Link „Zum Blog-Archiv“ im Block „Neueste Beiträge (Sunflower)“ berücksichtigt die Permalink-Konfiguration nicht, sondern ist stets „?post_type=post“. Erwarten würde ich eine „/archiv/“-URL wie inzwischen auch bei den Terminen.

Dieses Issue bezieht sich auf eine [Meldung in Chatbegruenung](https://chatbegruenung.de/channel/sunflower-wordpress?msg=ztQgQv33MEssqmDKp).

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Dafür bietet WordPress leider keine sprechende URL an, zumindest ist mir das bei meiner Recherche nicht unter die Augen gekommen. Aktuelle sehe ich deshalb dafür leider keine Lösung.

**Comment by gumby-man** [comment]
Ich hatte ja auf [get_post_type_archive_link()](https://developer.wordpress.org/reference/functions/get_post_type_archive_link/) getippt, aber das liefert tatsächlich nichts zurück. **Ich bin in Theme-Programmierung nicht daheim**, ich stolpere in der Funktions-Doku über das „False if the post type ... does not have an archive“ und frage mich, da es „archives.php“ ja gibt und „?post_type=post“ ja funktioniert, ob man vielleicht den Post-Type erneut registrieren muss inkl. gewünschten Slug („archiv“)?

Entschuldige dass ich auch nur doof frage und im Nebel stochere, ich will auch gerne selbst mal – im Open-Source-Gedanken – versuchen, das Problem zu lösen. Das wird aber dauern und ich habe dieses Theme nicht geschrieben oder kein anderes (nur Child-Themes bislang). Dennoch sehe ich das als zu lösendes Problem (Größenordnung unschön, nicht wichtig).

**Comment by mroesele** [comment]
So könnte es klappen: `get_permalink( get_option( 'page_for_posts' ) );`

Das ist die ID der Seite, die man unter Einstellungen > Lesen als "Beitragsseite" eingestellt hat.

**Comment by codeispoetry** [comment]
Was passiert, wenn man diese Einstellung nicht vorgenommen hat?

**Comment by gumby-man** [comment]
Bzw. anders herum, wie muss so eine Seite erstellt werden? Bei der Startseite steht dazu ja was in der Doku, gibt es eine Vorlage.

**Comment by mroesele** [comment]
Ich hab das grad getestet. So lange man nicht explizit eine Beitragsseite wählt, gibt `get_option( 'page_for_posts' );` einfach `0` zurück. Sonst die ID der gewählten Page.
![Bildschirmfoto 2021-05-19 um 13 39 07](https://user-images.githubusercontent.com/11442625/118806845-d951d480-b8a7-11eb-9a6c-7c18ec085d56.png)

**Comment by mroesele** [comment]
Da müsste man also noch ein paar Bedingungen abfragen, die Arbeit hat aber schon jemand erledigt:

`get_post_type_archive_link( 'post' );`

[Dokumentation der Funktion get_post_type_archive_link](https://developer.wordpress.org/reference/functions/get_post_type_archive_link/)

Das gab mir im Test in jedem Fall eine brauchbare URL zurück. Danach greift halt die [Template Hierachy](https://developer.wordpress.org/themes/basics/template-hierarchy/)  - je nachdem ob eine front-page.php, eine home.php oder eine index.php existiert, wird je nach Einstellung das entsprechende Template aufgerufen.

**Comment by codeispoetry** [comment]
Aber dann kommt man ja auf einer anderen Seite raus als bisher. Und man muss erst eine Seite eintragen.

**Comment by mroesele** [comment]
Ja richtig. Dann hätte das Blog-Archiv auch automatisch einen Permalink. 
Bisher ( https://sunflower-theme.de/demo?post_type=post ) befindet man sich ja im Blog-Archiv weiterhin auf der Startseite, nur mit anderem Output.

Aber bevor ich hier klug daherrede klone ich lieber bei Gelegenheit das Repo und schau mir das im Detail an. Muss in den nächsten Tagen eh einen Relaunch unserer KV-Website mit Sunflower erproben.

**Comment by gumby-man** [comment]
Also auch mein Test sagt: Wenn eich eine neue Seite anlege und als „Beitragsseite“ konfiguriere, dann kann ich diese aufrufen und erhalte eine Liste der Posts. Eigentlich ist bis auf Titel (als HTML-TITLE) und Permalink scheinbar egal, was diese neue Seite beinhaltet. Also grundsätzlich wäre es für mich als Lösung schon hinreichend, wenn der „Zum Blog-Archiv“-Link auf diese Seite zeigt – sofern sie konfiguriert ist natürlich.

Etwas schade ist schon, dass ich damit dann auch Seiten-Titel und Untertitel nochmal als Banner („page-header“) über den Beiträgen habe, das ist so erstmal redundant zum Seiten-Header („site-header“), aber da kann ich mir mein Child irgendwie zuhilfe nehmen...

**Comment by gumby-man** [comment]
Und jetzt habe ich zum Test mal „get_post_type_archive_link()“ in der „latest-posts.php“ reingepatched und die liefert mir sogleich das gewünschte Ergebnis. Müsste natürlich eine Abfrage rein, ob „Beitragsseite“ konfiguriert ist oder nicht (also ob „get_post_type_archive_link“ was geliefert hat), aber im Prinzip sehe ich das als gangbare Lösung. Und müsste vielleicht zusätzlich noch in die Doku.

**Comment by ErwinBehner** [comment]
Sorry, dass ich mich erst jetzt in die Diskussion einschalte. Bei JKB gibt es tatsächlich eine „/archiv/“-Seite. Diese wurde durch eine page-archiv.php im Theme realisiert.

**Comment by codeispoetry** [comment]
https://chatbegruenung.de/channel/sunflower-wordpress?msg=CkNzg7tNWjXKJaxbZ
