### ISSUE TITLE
Unterstützung für Urwahl3000-Shortcodes

### ISSUE THREAD

**Issue by gumby-man** [codeispoetry/sunflower#249]
Um einen reibungslosen Übergang von Urwahl3000-Seiten zu ermöglichen sollten die Shortcodes unterstützt werden:

- [Unterseiten](https://demo.urwahl3000.de/templates/)
- [Tabs](https://demo.urwahl3000.de/shortcodes/tabs/)
- [Termine](https://demo.urwahl3000.de/shortcodes/termine/)
- [Icons mit Font Awesome](https://demo.urwahl3000.de/shortcodes/icons-mit-font-awesome/)

**Comment by gumby-man** [comment]
Ach ja, dies ist nicht als Ersatz für eine Tabs-Block gedacht, sondern als Workaround für die Übernahme bestehender Inhalte.

vgl. [zusätzlicher Tabs-Block #84](https://github.com/codeispoetry/sunflower/issues/84)

**Comment by davidfuhr** [comment]
Ich habe hier ein Plugin angefangen, dass die Shortcodes implementiert. Ich denke das ist nicht unbedingt Aufgabe des Sunflower-Themes alte Shortcodes zu unterstützen.

https://github.com/davidfuhr/urwahl3000-shortcodes

Bisher habe ich nur den Support für die Unterseiten implementiert. Ich brauche aktuell nicht mehr.
