### ISSUE TITLE
iCal-Import: Problem bei Beschreibung mit HTML-Formatierung

### ISSUE THREAD

**Issue by mittelrheintal** [codeispoetry/sunflower#250]
Hallo,

vielen Dank für euer Theme!

Wir möchten gerne unseren Google-Kalender via privater URL per iCal einbinden. Das funktioniert auch super bis auf einen Aspekt:

Die Beschreibung wird im Google-Kalender automatisch HTML formiert und im Feed so gespeichert (Zeilenumbrücke mit <p> usw.).

Beim Import durch das Theme wird dieser formatierte Code ignoriert und im Frontend als Plaintext ausgegeben - das sieht dann nicht besonders schön aus. Ich vermute da einen Bug.

Danke Euch und LG
Franziskus

**Comment by davidfuhr** [comment]
Wenn ich das richtig verstehe sollte im DESCRIPTION-Feld kein HTML stehen dürfen (siehe bspw. https://stackoverflow.com/questions/854036/html-in-ical-attachment). Daher verhält sich der Importer wahrscheinlich korrekt.

HTML im Feed ist außerdem ein mögliches Sicherheitsproblem weil Javascript oder externe Inhalte eingeschleuste werden könnten.

Eine Möglichkeit wäre den Importer selbst anzupassen, dass HTML importiert wird (mit den o.g. Sicherheitsproblemen). Eine andere wäre das HTML zu entfernen und nur den Text zu übernehmen. Ich habe für eine Installation für eine einmalige Datenübernahme vom alten Kalender den Importer angepasst und das HTML importiert (ich konnte es ja danach kontrollieren). Für einen fortlaufenden Import sehe ich das jedoch sicherheitsmäßig etwas kritisch.

**Comment by codeispoetry** [comment]
Es ist leider so, wie @davidfuhr schreibt. Deshalb kann ich den Importer zurzeit leider nicht anpassen.
