### ISSUE TITLE
Paginierung funktioniert bei Terminen nicht

### ISSUE THREAD

**Issue by davidfuhr** [codeispoetry/sunflower#254]
Bei der Terminseite wird zwar der Link "Ältere Beiträge" unter den Terminen angezeigt, man kann auch drauf klicken, die URL ändert sich dann auch mit dem Page-Parameter, aber es werden immer die gleichen Termine angezeigt.

Einfach testen kann man das, wenn man bspw. den Kalender von https://www.google.com/calendar/ical/spielplan.1.bundesliga%40gmail.com/public/basic.ics importiert.

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Termine sollten gar keine Seitennavigation haben, deshalb habe ich den Link dazu entfernt.
