### ISSUE TITLE
Mastodon Verifizierung

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#255]
https://github.com/codeispoetry/sunflower/blob/c7a7ca04d468587bb0b65fd62bee570025876664/functions/options/social-media.php#L221

Bei Mastodon ist noch ein `rel="me"` notwendig um eine Verifizierung zu ermöglichen.

`<a rel="me" href="https://gruene.social/@gruene_tk">Mastodon</a>` ist was Mastodon dazu vorschlägt.

**Comment by codeispoetry** [comment]
Ist eingebaut. Kommt ab Version 1.1.5 (heute Abend)
