### ISSUE TITLE
Feature Request: Datum in der Terminübersicht

### ISSUE THREAD

**Issue by andra03** [codeispoetry/sunflower#256]
Hi Tom, es wäre schön, wenn wir in der Liste der Termine eine Spalte hätten mit dem Termin des Termins. Aktuell ist es schwer den Termin zu identifzieren, wenn z. B. alle "OV-Treffen" heißen. Und vergangene Termine irgendwie zu markieren wäre auch cool. 

Viele Grüße
Alexandra

**Comment by codeispoetry** [comment]
Das wird es in der Version 1.2 geben. Danke für die Idee.
