### ISSUE TITLE
Termine werden nicht angezeigt

### ISSUE THREAD

**Issue by tmaterna** [codeispoetry/sunflower#257]
Wir haben migriert. Auch unsere Termine. Allerdings wird nur ein Termin angezeigt. Auch ein neu angelegter Termin wird nicht angezeigt, egal was gemacht wird. Bitte fixen.

**Comment by codeispoetry** [comment]
Hallo. Ich brauch mehr Infos. Ein Link zB.

**Comment by tmaterna** [comment]
Es ist irgendwie unlogisch. Wenn man ganztägig bei Terminanlage aussucht wird nichts / falsch angezeigt. Erst wenn man noch zusätzlich eine Uhrzeit angibt, wird die VA als ganztägig angezeigt…

**Comment by b90g** [comment]
https://gruene-suew.de/

( https://chatbegruenung.de/channel/sunflower-wordpress?msg=EC446hRMZsLMEWcLS )

**Comment by codeispoetry** [comment]
Besteht das Problem noch? Wenn ja, wie genau?

**Comment by ErwinBehner** [comment]
Der Termin war als "Ganztages"-Ereignis also ohne Uhrzeit angelegt worden. Nach Eingabe einer Uhrzeit hatte es dann wohl funktioniert.
