### ISSUE TITLE
&shy; Umsetzung fehlerhaft

### ISSUE THREAD

**Issue by tmaterna** [codeispoetry/sunflower#258]
Bei Verwendung von &shy; ­ wird auf mobile Device ordentlich getrennt, in der Desktopansicht ergibt sich ein unschönes Leerzeichen. #bittefixen

**Comment by codeispoetry** [comment]
Bitte poste ein Link, wo der Fehler auftritt.

**Comment by tmaterna** [comment]
Gefunden und behoben
