### ISSUE TITLE
Terminbox überlagert Teile des Termintextes

### ISSUE THREAD

**Issue by fbthb** [codeispoetry/sunflower#259]
Die grüne Termin-Metabox ragt in er Desktop-Ansicht, wenn man sie mit allen Infos befüllt (Adresse, Veranstalter, ...) bis in den Text des Termins hinein und überlagert in den ersten drei Zeilen den rechten Rand des Textfeldes.

**Comment by codeispoetry** [comment]
Danke. Hast du 1 Link für mich?

**Comment by fbthb** [comment]
z.B. hier: https://fabian-ehmann.de/termine/konstituierende-sitzung/

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Ist ab Version 1.1.5 (heute Abend) behoben.
