### ISSUE TITLE
ICS Export broken

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#260]
https://gruene-winsen.de/?sunflower_event=klimafreundlich-und-zukunftsfaehig-bauen-was-ist-drin-2&format=ics

soll ich abfragen ob start und enddatum gesetzt wurde?...

**Comment by b90g** [comment]
noteself: https://helpdesk.verdigado.com/#ticket/zoom/21920

**Comment by codeispoetry** [comment]
Ich konnte den Fehler einigermaßen nachstellen. Es müsste mit 1.1.5 (heute Abend) behoben sein.

**Comment by b90g** [comment]
https://gruene-winsen.de/?sunflower_event=digitales-meeting-des-ortsverbandes-2&format=ics - Thunderbird bietet mir beim Import UTC als zeitzone an. - wird das von der seite festgelegt oder kommt das aus dem theme export?

**Comment by metalolf** [comment]
Bei mehrzeiligen Einträgen der Adresse (Name, Straße, Nr, PLZ, Ort usw.) wird nur die erste Zeile in den LOCATION-Tag geschrieben.
Getestet mit der Demo-Seite z.B. [hier](https://sunflower-theme.de/demo/termine/termin-mit-einem-beitragsbild/)

Ich würde Zeilensprung durch _Komma_ plus _Leerzeichen_ ersetzen.

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Wird in der nächsten Version behoben sein

**Comment by codeispoetry** [comment]
Der Fehler ist in Version 1.2 behoben.
