### ISSUE TITLE
Feature Request: Termine in Kalenderansicht

### ISSUE THREAD

**Issue by davidfuhr** [codeispoetry/sunflower#261]
Die Terminübersicht wird bei uns als nicht besonders übersichtlich empfunden. Daher kam der Wunsch nach einer "klassischen" Kalenderansicht (wie bspw. bei https://www.mueller-moritz.de/calendar/).

Würdest du einen PR mit einem Kalender-Block mergen?

Als Basis würde ich vermutlich https://github.com/ylli2000/bootstrap-4-calendar oder https://github.com/Serhioromano/bootstrap-calendar nehmen. Oder hast du andere Vorschläge oder Präferenzen?

PS: Generell finde ich es etwas suboptimal die Terminfunktion im Template zu implementieren. Dadurch baut man halt wieder Features, die es anderswo schon gibt. Der (meiner Meinung nach) großartige WP Event Organiser hat so eine Funktion (http://demo.wp-event-organiser.com/calendar/) und viele andere die "Sunflower Events" nicht hat. Meiner Meinung nach wäre es sinnvoller im Theme bspw. Templates für den Event Organiser bereitzustellen und den für Termine zu empfehlen... aber der Drops ist ja wohl leider schon gelutscht...

**Comment by codeispoetry** [comment]
Mergen würde ich eine Kalenderansicht vermutlich schon.
Aber ihr könnt natürlich auch ein Plugin verwenden, warum nutzt ihr nicht Euer favorisiertes Plugin?

**Comment by Jako** [comment]
Ich würde https://fullcalendar.io/ als Frontend Script vorschlagen. Die freie Version ist für die meisten Zwecke ausreichend und das Script braucht weder Bootstrap noch jQuery.

**Comment by davidfuhr** [comment]
Bootstrap und jQuery ist ja eh schon da. Von daher ist das ja kein exta Overhead.

Den FullCalendar hatte ich mir auch angeschaut, ich hatte allerdings auf die Schnelle eben keinen Theme-Support für Bootstrap gefunden weswegen ich von mehr Aufwand beim Angleichen an das Sunflower-Theme ausging. Hast du damit Erfahrungen?

**Comment by Jako** [comment]
Hmm, es gibt das hier: https://fullcalendar.io/docs/bootstrap-theme
und eine Demo: https://fullcalendar.io/docs/bootstrap-theme-demo

**Comment by davidfuhr** [comment]
@codeispoetry Ein anderes Plugin müsste ich komplett stylen und ich denke das ist mehr Aufwand als eine Kalender-Ansicht in das Sunflower-Theme zu integrieren. 

@Jako  Oh, danke für den Link. Da habe ich wohl zu oberflächlich gesucht 😄 

Ich habe jetzt einen PR mit Fullcalendar gestellt. Ich freue mich auf Feedback :)
