### ISSUE TITLE
Der Menüpunkt "Formulare" fehlt bei mir

### ISSUE THREAD

**Issue by stormraider77** [codeispoetry/sunflower#262]
Hallo zusammen,

ich habe die aktuellste Version von Wordpress und dem Sunflower-Theme, aber im Gegensatz zur Testversion fehlt bei mir der Menüpunkt "Formulare", sodass ich kein Kontaktformular anlegen kann. 

Da ich bislang der Einzige mit dem Problem bin, will ich nicht ausschließen, dass irgendetwas an der Konfiguration falsch ist. 

Ich bin vom alten Wordpress Theme "Urwahl 3000" gewechselt – nach Handbuch. Ein weiterer Fehler, der für mich nicht dramatisch ist, aber vielleicht einen Tipp für die Ursache gibt: Die vorgegebenen Bilder lassen sich bei mir nicht in die Mediathek importieren.

Soweit erst einmal. Vielen Dank für Eure Arbeit, das Theme gefällt mir sehr gut und kommt auch bei anderen ausgezeichnet an ;-D

**Comment by codeispoetry** [comment]
Der Menüpunkt "Formulare" erescheint nur, wenn man das Plugin "Contact-Form 7" installiert. Für ein einfaches Kontaktformular braucht man das aber nicht, dafür gibt es eine Block.
