### ISSUE TITLE
Text: "Keine Termine" schwer lesbar

### ISSUE THREAD

**Issue by mnbvghw** [codeispoetry/sunflower#264]
Ich finde den Text, "keine nächsten Termine" schwer lesbar, bzw sieht nicht schön aus. Kann man den weiß machen?

![Screenshot_2021-05-21-11-03-24-369_org.mozilla.firefox_beta.jpg](https://user-images.githubusercontent.com/53110522/119112408-57d38100-ba24-11eb-97bb-cb02050aae9f.jpg)

**Comment by codeispoetry** [comment]
Hallo @designerin , hast Du dafür eine Lösung?

**Comment by designerin** [comment]
Hallo @codeispoetry  ich würde es gerne so lösen. Habe es mal mit Blöcken auf der Demoseite gebaut, um es zu visualisieren. 

https://sunflower-theme.de/demo/darstellung-termine-block/?preview_id=442&preview_nonce=4e18a0a0b3&preview=true

Das wäre mit einem Overlay von 30% Deckkraft in schwarz und dann der Text weiß, für die Zeile "keine Veranstaltungen geplant" würde ich dann die H4 nehmen, dann kommt das auch noch mal besser raus.

<img width="450" alt="grafik" src="https://user-images.githubusercontent.com/78264333/119692044-5d2d3300-be4b-11eb-85f9-d57b71f3069e.png">

**Comment by codeispoetry** [comment]
@designerin Du kannst das gerne auf der Startseite am passenden Block ändern. Ich übernehme das dann in den nächsten Release. Der gilt dann aber nur für neue Seiten. An bestehenden Seiten kann ich nichts mehr ändern, weil dsa ein redaktioneller Inhalt ist. Sag bitte Bescheid, wenn es auf der Startsteit geändert ist

**Comment by designerin** [comment]
@codeispoetry Den Termine Block kann ich ja leider nicht ändern.. der ist ja als Sunflower-Block schon vorgebaut. oder wie komme ich da ran?

**Comment by codeispoetry** [comment]
Ist in Version 1.2 behoben.

**Comment by designerin** [comment]
Bei den Terminen block hat es jetzt was zerschossen..Der Fließtext wird in einer falschen Schrift dargestellt. Und auch die Kategorien haben die falsche Schrift jetzt.Der Link auf alle Termine funktioniert nicht mehr

**Comment by codeispoetry** [comment]
Dankeschön. Ist behoben. Der Link geht aber nach wie vor, oder welchen Button meinst Du?

**Comment by designerin** [comment]
ja, der Link ging dann auch wieder
