### ISSUE TITLE
Feature Request: Freier Text auf der Termine-Seite

### ISSUE THREAD

**Issue by andra03** [codeispoetry/sunflower#265]
Hallo Tom, ich wieder: Auf der Seite mit allen Terminen wäre es schön, ein bisschen Text einfügen zu können, um zum Beispiel auf andere Seiten mit Terminen hinzuweisen. Ähnlich den Kategorie-Seiten mit Kategorie-Beschreibung. 

Dank und Gruß, 
Alexandra

**Comment by codeispoetry** [comment]
Dankeschön. Ist ab 1.5.0 eingebaut.
Du kannst in den Sunflower-Einstellungen unter Termine einen Text eingeben.
