### ISSUE TITLE
neuste Beiträge (Sunflower) - Problem mit Umlauten und Leerzeichen

### ISSUE THREAD

**Issue by Digiseb** [codeispoetry/sunflower#267]
Wenn eine Beitrags-Kategorie im "Namen" ein Leerzeichen oder ein Umlaut beinhaltet, wird auf der Seite des eingebauten Blogs der Link für den "zum Blog Archiv" Button nicht mitgeteilt, das href="" bleibt leer, der User wird auf die gleiche Seite verlinkt.

**Comment by codeispoetry** [comment]
Danke für den Report. Ich kann den Fehler bei mir aktuell nicht nochvollziehen. Es gitb die Kategorien "Gegen Rechts" und "Anträge", die beide korrekt angezigt und verlinkt werden.

**Comment by codeispoetry** [comment]
Ich habe den Fehler vermutlich reproduzieren können. Er ist ab Version 1.1.7 behoben
