### ISSUE TITLE
Fallback-Image für Twitter-Cards

### ISSUE THREAD

**Issue by evaris1107** [codeispoetry/sunflower#269]
Hi,

eine Kollegin hatte mich darauf aufmerksam gemacht, dass die Homepage unserer Website gruene-fuerth-land.de auf Discord wie folgt als Preview dargestellt wird:

![WhatsApp Image 2021-05-26 at 13 49 14](https://user-images.githubusercontent.com/72270664/119857990-54546400-bf14-11eb-946c-09eb27dd76ae.jpeg)

Nun hatte ich das JM Twitter Cards WP Plugin von Urwahl-3000-Zeiten mitübernommen, nichts ahnend, dass Sunflower bereits mit den entsprechenden Meta-Tags ausgestattet ist (sunflower/template-parts/open-graph.php). Deshalb gab es einen Conflict, sodass das Twitter-Logo durch das Plugin als Fallback genutzt wurde, da die Homepage kein Beitragsbild enthält.

Nach Entfernung des obsoleten Plugins wird nun im Twitter Card Validator gar kein Vorschaubild mehr gezeigt (auch bei Beiträgen, die natürlich kein Beitragsbild haben). Die entsprechenden HTML-Meta-Tags bleiben dann lehr:
<meta name="twitter:image" content="">

**=> Frage:** Wäre es möglich einzurichten, dass ich Open Graph hier ein Ausweichsbild zuweisen kann, das verwendet wird, falls kein Beitragsbild zur Verfügung steht? Für Homepages wäre das m.E. wichtig. Könnte das z.B. in den Backend-Theme-Einstellungen unter "Social Media" eingerichtet werden?

**Zweitens:** Und ich weiß nicht, ob das überhaupt Sunflower betrifft, aber dass (nur) auf Discord der Beitrags-Autor mit angegeben wird, sollte am besten auch entfernt werden.

Danke im Voraus!

**Comment by codeispoetry** [comment]
Dankeschön. Ist ab 1.5.0 eingebaut.
Du kannst in den Sunflower-Einstellungen unter Social-Media ein Fallbackbild angeben.
