### ISSUE TITLE
Map files missing in console

### ISSUE THREAD

**Issue by markusguenther** [codeispoetry/sunflower#271]
We have switched from Urwahl to Sunflower Version: 1.1.7 and the console is missing some maps.
thanks for the new theme :)

<img width="1283" alt="Screenshot 2021-05-31 at 14 23 29" src="https://user-images.githubusercontent.com/1014126/120192882-0a24f880-c21c-11eb-8aa4-cc5e662f35a7.png">

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Da es nur map-Dateien sind, beeinträchtigt das die Funktion der Seite nicht. Leider kann ich diese Hinweise auch nicht leicht entfernen, weil dsa eingebundener Code von Drittanbietern ist.
