### ISSUE TITLE
Zitat Block: Anführungszeichen folgen nicht der Textausrichtung

### ISSUE THREAD

**Issue by danijoo** [codeispoetry/sunflower#273]
Theme Version: 1.1.7

Die Anführungszeichen am Beginn des Zitatblocks sitzen an der falschen Stelle wenn man die Textausrichtung auf zentriert oder linksbündig einstellt. Sie bleiben an ihrer ursprünglichen Position. Wie könnte man das am besten lösen? Die `"` werden im css definiert - geht das überhaupt ohne php? 

Beispiel:
![zitate](https://user-images.githubusercontent.com/4690162/120479494-4be5a880-c3ae-11eb-8dc8-abea6c3418d1.png)

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Das ist ein Fehler im css, der leicht behoben werden kann. Ich frage mich allerdings, ob die Anführungszeicheichen wirklich automatisch kommen sollen? Dann kann man sie nämlich nicht entfernen. 
Alternativ kann man die ja auch per Hand eintragen und dann leicht selbst entscheiden, ob man sie haben will oder nicht.

**Comment by codeispoetry** [comment]
Note to myseld: quote.scss delete before and after

**Comment by danijoo** [comment]
Hi,
Ja. Das wäre glaube ich auch eine gute Lösung. Fixed das Problem und gibt mehr Freiheit. 

Jun 6, 2021 5:24:07 PM Thomas Rose ***@***.***>:

**Comment by codeispoetry** [comment]
Ist in Version 1.2 behoben.
