### ISSUE TITLE
Warning: sprintf(): Too few arguments in /home/www/kbm/dev/gruene/wp-admin/includes/class-bulk-upgrader-skin.php

### ISSUE THREAD

**Issue by sirVinc** [codeispoetry/sunflower#274]
Ich habe gerade ein aktuelles WordPress (Version 5.7.2) installiert und Sunflower (Version 1.1.7) hochgeladen. Anschließend schlägt WordPress vor, dass ich die Plugins 
- Embed Privacy
- Plugin Free Images
installieren soll. Wenn ich diese dann über den Plug-Installer installiere, kommt eine Meldung:

Warning: sprintf(): Too few arguments in /home/www/kbm/dev/gruene/wp-admin/includes/class-bulk-upgrader-skin.php on line 152

Installation war dennoch erfolgreich.

**Comment by codeispoetry** [comment]
Danke für den Bugreport. Ich kann den Fehler bei mir leider nicht nachstellen, bei mir erscheint der Fehler nicht.  Hast Du ein Procedere, um den Fehler jedes Mal nachstellen zu können?

**Comment by sirVinc** [comment]
Ich hatte die Installation nur einmalig auf einem neuen WordPress durchgeführt.

Hast du eine bestehendes WordPress genommen oder komplett neu?
