### ISSUE TITLE
Preload key requests

### ISSUE THREAD

**Issue by sirVinc** [codeispoetry/sunflower#275]
Die Schriften sollten durch link rel=preload geladen werden. Dies spart beim Seitenaufbaue 3,6 s laut Google Lighthouse ein.

Consider using `<link rel=preload>` to prioritize fetching resources that are currently requested later in page load. Learn more.

Betrifft folgende Schriften.
https://sunflower-theme.de/demo/wp-content/themes/sunflower/assets/vndr/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2
https://sunflower-theme.de/demo/wp-content/themes/sunflower/assets/fonts/Arvo_Gruen_2015_10.woff
https://sunflower-theme.de/demo/wp-content/themes/sunflower/assets/fonts/ptsans_regular.woff
https://sunflower-theme.de/demo/wp-content/themes/sunflower/assets/fonts/ptsans_italic.woff
https://sunflower-theme.de/demo/wp-content/themes/sunflower/assets/fonts/ptsans_bolditalic.woff

**Comment by codeispoetry** [comment]
In meinem Lighthouse-Audit wird das nicht mehr aufgeführt. Die Schriftarten werden auch nicht über ein link-Tag geladen, sondern aus einem CSS-File.
