### ISSUE TITLE
Eliminate render-blocking resources

### ISSUE THREAD

**Issue by sirVinc** [codeispoetry/sunflower#276]
Durch Render-Blocking Resourcen kommt es zu einem verzögerten Seitenaufbau, der bis zu 10 Sekunden kosten kann.

> Resources are blocking the first paint of your page. Consider delivering critical JS/CSS inline and deferring all non-critical JS/styles. Learn more.
> 
> There are a number of WordPress plugins that can help you inline critical assets or defer less important resources. Beware that optimizations provided by these plugins may break features of your theme or plugins, so you will likely need to make code changes.

https://web.dev/render-blocking-resources/?utm_source=lighthouse&utm_medium=lr
https://kinsta.com/de/blog/render-blocking-javascript-css-eliminieren/

**Comment by codeispoetry** [comment]
Ich habe das mit Lighthouse getestet. Das sind leider alles keine Ressourcen, die vom Theme bereit gestellt werden. Mit Ausnahme der CSS-Datei, die zum Rendern notwendig ist. Das sollte man ggf. mit einem Plugin lösen
