### ISSUE TITLE
Plugin embed privacy  blockiert die Blogroll "Aktuelle Beiträge"

### ISSUE THREAD

**Issue by andra03** [codeispoetry/sunflower#277]
Hallo Tom, 
wenn das Plugin "embed privacy" wie empfohlen aktiviert ist, wird nur noch 1 aktueller Beitrag angezeigt und kein Button "Blog-Archiv". 
Viele Grüße
Alexandra

**Comment by codeispoetry** [comment]
Danke für den Bugreport. Ich kann den Fehler bei mir leider nicht nachstellen. Hast Du einen Link für mich, wo ich mir das mal ansehen kann?

**Comment by andra03** [comment]
Du hast ja ein Login zu unserer Website https://gruene-bergamlaim-trudering-riem.de/wp-admin (trose)
