### ISSUE TITLE
Termindarstellung im Block (breite)

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#282]
Ist das strecken des Terminkästchens gewollt?

![image](https://user-images.githubusercontent.com/63392812/121478188-0be37e80-c9c9-11eb-93e9-beff7bd00bb5.png)

**Comment by codeispoetry** [comment]
Nein. Danke für den Hinweis

**Comment by codeispoetry** [comment]
Ab Version 1.3 behoben.
