### ISSUE TITLE
Entfernen des Generator Meta-Tags

### ISSUE THREAD

**Issue by markusguenther** [codeispoetry/sunflower#283]
Hallo,

wir rendern per Default immer das Metatag `generator`.
Es ist kein Schutz direkt, doch man muss nicht unbedingt die Version seines WP rausgeben.

So wäre es für Angreifer einfacher nach Schwachstellen zu schauen.
Auch wenn man angehalten ist es immer aktuell zu halten, wäre das eine Kleinigkeit um es denjenigen zumindest ein wenig schwerer zu machen.

```html
<meta name="generator" content="WordPress 5.7.2" />
```

**Comment by sirVinc** [comment]
Die Frage ist, ob es viel bringt.
a) Die Schwachstellen werden auch gefunden, wenn die Version dort nicht steht.
b) Aktuell halten ist immer noch die beste Lösung.

**Comment by markusguenther** [comment]
Klar ist jemand der bewandert ist, auch in der Lage das so zu finden. Doch so Script Kiddies schreckt es vielleicht ab. Und es kostet einen ja nichts.

**Comment by codeispoetry** [comment]
Ich werde das gerne mergen.
