### ISSUE TITLE
Menüstil an JKB anlehnen

### ISSUE THREAD

**Issue by fmay95** [codeispoetry/sunflower#285]
In Sunflower sind die Menüs alle in PT Sans, Joseph Knows Best nutzt Arvo Gruen. JKB hat einen sehr ansprechenden Sticky-Header-Stil, der mehr Fokus auf das Titelbild erlaubt. Beide Möglichkeiten sollten zumindest als Option eingebaut werden.

Beispiel für den sticky header: gruene-nrw.de

**Comment by codeispoetry** [comment]
Große Bilder sind auch mit Sunflower möglich, z.B. https://hilbrand.nrw/
