### ISSUE TITLE
Hellgrüne Balken/Bereiche oberhalb und unterhalb des eigentlichen Seiteninhalts

### ISSUE THREAD

**Issue by frankelangmach** [codeispoetry/sunflower#286]
<img width="852" alt="Bildschirmfoto 2021-06-18 um 07 40 29" src="https://user-images.githubusercontent.com/86257566/122809798-dd21ae00-d2ce-11eb-8326-12441c3a70c7.png">

Hallo, zwischen dem eigentlichen Seiteninhalt, den man mittels der Blöcke selbst gestalten kann, und dem Fußzeilenmenü entsteht auf allen Seiten immer ein hellgrüner Bereich. Dieser ist auf verschiedenen Seiten unterschiedlich groß und über die Seiten-Bearbeitung nicht editierbar. Wenn ich als untersten Block auf der Seite den Termin-Block setzte, ist er nicht da. Das habe ich ausprobiert, aber bei allen anderen Blöcken ist er da - wenn auch nur sichtbar, wenn man dem letzten Block eine andere Hintergrundfarbe gibt, wie z.B. Weiß. 

Das gleiche Problem ergibt sich auch vor dem ersten Block, den man auf der Seite erstellt. Gibt man so einem Block eine andere Farbe, so fällt dieser nicht veränderbare sehr hellgrüne Bereich ins Auge.

**Comment by codeispoetry** [comment]
Existiert das Problem noch? Ggf. musst Du in den Seiteneinstellungen unter Layout den Haken bei "Layout selbst gestalten" setzen
