### ISSUE TITLE
"Ähnliche Beiträge" unterstrichen

### ISSUE THREAD

**Issue by simonfehr** [codeispoetry/sunflower#287]
Unter Blogbeiträgen werden "Ähnliche Beitrage" angezeigt. Bei diesen ist der komplette Vorschau-Text unterstrichen. Natürlich ist das ein Hyperlink, aber es sieht überhaupt nicht schön aus. 
Hier ein Beispiel (nach unten scrollen): 
https://maria-heubuch.de/hybride-gebaeude-fuer-die-zukunft/

**Comment by codeispoetry** [comment]
Ab Version 1.3 behoben.
