### ISSUE TITLE
Mobile Ansicht Suche verschwindet

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#288]
Die Dinge die in der Kopfleiste sind wandern ans Ende der Seite, ausser die Suche, die ist einfach weg.

Ich fänds am sinnvollsten dass die ins Hamburgermenü geht, aber lass mich gerne von anderen vorschlägen überstimmen.

**Comment by codeispoetry** [comment]
@designerin, wie siehst Du das?

**Comment by designerin** [comment]
ich denke auch, dass sie im Hamburgermenü gut aufgehoben wäre

**Comment by codeispoetry** [comment]
Ab Version 1.3.2 ist die Suche im mobilen Menu enthalten.
