### ISSUE TITLE
Filter auf Termin-Kategorien für nächste Termine

### ISSUE THREAD

**Issue by softmetz** [codeispoetry/sunflower#290]
Der Block "Nächste Termine" sollte die Möglichkeit bieten, nur Termine aus angegebenen Termin-Kategorien anzuzeigen.

**Comment by codeispoetry** [comment]
Hat er: rechts in den Bkockeinstellungen.

**Comment by softmetz** [comment]
Da hab ich nur "Zusätzliche CSS-Klassen". Habe Version 1.2.3, kam das vielleicht danach?

**Comment by codeispoetry** [comment]
ah, sorry. hab das verwechselt mit dem Block "neueste Beiträge".
