### ISSUE TITLE
Termin Archiv Reihenfolge änderbar machen

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#291]
`Es wäre cool, wenn man das Terminarchiv in anderer Reihenfolge hätte (also dass nicht der älteste Termin zuerst, sondern zuerst der Termin, der am kürzesten vorbei ist.`

**Comment by codeispoetry** [comment]
Note to myself https://github.com/codeispoetry/sunflower/blob/main/functions/events.php l294

**Comment by codeispoetry** [comment]
Ab Version 1.3 behoben.
