### ISSUE TITLE
Font BereitBold hinzufügen

### ISSUE THREAD

**Issue by renkekuhlmann** [codeispoetry/sunflower#292]
Wäre es möglich, dass dem Design die Schriftart BereitBold hinzugefügt wird, die aktuell für den Wahlkampf der Grünen genutzt wird? Wenn ich sie dann per CSS Klasse auswählen könnte, wäre es ideal. Oder kennt jemand eine Alternative wie ich die Schrift benutzen könnte?

**Comment by codeispoetry** [comment]
Ab Version 1.3 gibt es nun die Klasse ``bereit``, die die neue Schriftart einsetzt.
Danke für die Idee.

**Comment by renkekuhlmann** [comment]
Funktioniert super. Vielen Dank nochmal!
