### ISSUE TITLE
Peertube Block hinzufügen

### ISSUE THREAD

**Issue by ErwinBehner** [codeispoetry/sunflower#293]
Wordpress bietet leider von Haus aus keinen Peertube-Block. Deshalb fände ich es sinnvoll diesen analog wie das Akkordeon im Theme anzubieten.

**Comment by codeispoetry** [comment]
Wenn man die URL eines Videos von peertube.netzbegruenung.de direkt im Gutenberg-Editor eingibt, wird das Video automatisch eingebunden.
