### ISSUE TITLE
Personen Vorlage Block beim einfügen defekt.

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#294]
`Dieser Block enthält unerwarteten oder ungültigen Inhalt” Klicke ich dann “Versuch der Blockwiederherstellung” scheint das Vorlagen-Bild nicht zu existieren.`

https://chatbegruenung.de/channel/sunflower-wordpress?msg=tQMucAYsgeq4bJD2Q

**Comment by codeispoetry** [comment]
So wie es im Chat aussieht, ist das Problem behoben

**Comment by ErwinBehner** [comment]
Nein. Das Problem ist nach wie vor vorhanden. Auch gerade nochmal unter V1.3.2 gestestet.

**Comment by codeispoetry** [comment]
Danke. Wie ist das genaue Vorgehen, um den Fehler zu reproduzieren?

**Comment by ErwinBehner** [comment]
In der Vorlage die Personen-2 bzw. Personen-3 auswählen. Hat bei mir dann sofort den Block-Fehler angezeigt.

**Comment by codeispoetry** [comment]
Danke. Bisher wurde da tatsächlich auf localhost verwiesen, was natürlich nicht funktionieren kann. Das habe ich nun geändert. "Block wiederherstellen" muss man wohl weiterhin, aber dann geht es.
