### ISSUE TITLE
Hintergrundfarbe über editor palette falsche Klasse

### ISSUE THREAD

**Issue by Alzi** [codeispoetry/sunflower#296]
Ich habe bei einem Spaltenblock über den Farbwähler das dunkle Grün als Hintergrundfarbe eingestellt. Die entstehende CSS Klasse hieß dann 
`has-green-800-b-background-color` und diese existiert nicht.
Binde ich die Klasse manuell als `has-green-800b-background-color` (ohne Bindestrich) ein funktioniert es. :)

**Comment by codeispoetry** [comment]
Ab Version 1.3 behoben.
