### ISSUE TITLE
Warnungen der Block API

### ISSUE THREAD

**Issue by markusguenther** [codeispoetry/sunflower#297]
Die Sunflower Blocks werfen Warnungen, da die Kategorie nicht bekannt ist.
Ich hab schon ein wenig geschaut und im PHP Code wird eine Kategorie angelegt. Das Gutenberg Plugin scheint aber auch noch eine Registrierung zu benötigen. Da im JS Teil die Kategorie nicht bekannt ist.

Ich bin leider kein WordPress Entwickler und muss auch erst rum schauen woran das liegen kann.

<img width="1723" alt="Screenshot 2021-07-21 at 13 09 53" src="https://user-images.githubusercontent.com/1014126/126484087-7b17ee9c-c096-4aaf-a7ce-f85263bd8f1a.png">

**Comment by markusguenther** [comment]
Ok hab einen Fehler gefunden der unserem Entspricht. Müssen als entweder die Imports anpassen oder die Webpack Konfiguration, damit das so geht.

https://github.com/WordPress/gutenberg/issues/13760

Denke die Nutzung von `const { registerBlockType } = wp.blocks;` bereitet weniger Schmerzen :D

**Comment by codeispoetry** [comment]
Dankeschön für den Hinweis.
Leider funktioniert der dort vorgeschlagene Weg nicht. 
Die Kategorie ist ist in sunflower zwar registriert, allerdings als ungültig deklariert. Die Fehlermeldung/der Fehler ist ein bischen anders, derhalb funktioniert die Lösung hier nicht

**Comment by codeispoetry** [comment]
Alle Abhilfen haben bisher nicht geholfen. Insbesondere block_categories_all statt block_categories.
Weil das nur eine Warnung ist, schließe ich das Ticket einstweilen. Vielleicht wird  es sich mit WordPress6 von alleine lösen.
