### ISSUE TITLE
font display nutzen, fonts reduzieren, und 3 Bilder mit width und height ausstatten

### ISSUE THREAD

**Issue by Segelflugpilot** [codeispoetry/sunflower#298]
Wäre es möglich den Text über font-display schon vorher auszugeben? Allgemein frage ich mich, warum das Theme gleich 5 Schriftarten braucht. Ich würde die gerne reduzieren/im Customizer einstellen können.

Pagespeed Insight
> Darauf achten, dass der Text während der Webfont-Ladevorgänge sichtbar bleibt Verwenden Sie die CSS-Funktion font-display, damit der Text für Nutzer sichtbar ist, während Webfonts geladen werden.
Mögliche Einsparungen 
fonts/ptsans_regular.woff 90 ms 
fonts/Arvo_Gruen_2015_10.woff 50 ms
fonts/ptsans_bold.woff 90 ms 
fonts/ptsans_bolditalic.woff70 ms
> 
Auch haben die Bilder sunflower-dark.svg und sunflower.svg  (Sonnenblume - Logo), sowie das Logo Bündnis 90/Die Grünen keine explizite width und height.

**Comment by codeispoetry** [comment]
Ab Version 1.3.2 wird font-display benutzt.
Die Größe der Bilder kann ich leider nicht fest im HTMl angeben, weil die vom CSS variabel gesetzt werden, je nach dem, wie groß das Browserfenster ist (z.B. für mobile Endgeräte).
