### ISSUE TITLE
ICS-Export für alle Termine / abonnierbarer Kalender

### ISSUE THREAD

**Issue by davidfuhr** [codeispoetry/sunflower#299]
Bei uns aus dem KV kam der Wunsch die Termine abonnieren zu können. Ideal wäre natürlich wenn es einen eigenen ICal-Feed pro Kategorie gäbe.

Für einzelne Termine ist ical ja bereits umgesetzt, daher denke ich sollte der Aufwand für einen Komplett-Feed nicht allzu groß sein...

**Comment by HappyLer** [comment]
Besteht die Mölichkeit, den iCals eine Zeitzone via  VTIMEZONE [1] hinzuzufügen. Aktuell werden die icals ohne Zeitzone generiert und bei so manchem Kalender wird dann beim Import UTC angenommen und es gibt keine Möglichkeit, das zu korrigieren (z.B. bei Google Kalender, wenn man per URL abonniert).


[1] https://www.rfc-editor.org/rfc/rfc5545#section-3.6.5

**Comment by codeispoetry** [comment]
Verstehe ich das richtig: es müsste lediglich in der Exportdatei folgender Block eingefügt werden:

BEGIN:VTIMEZONE  
TZID:Europe/Berlin  
X-LIC-LOCATION:Europe/Berlin  
BEGIN:DAYLIGHT  
TZOFFSETFROM:+0100  
TZOFFSETTO:+0200  
TZNAME:CEST  
DTSTART:19700329T020000  
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3  
END:DAYLIGHT  
BEGIN:STANDARD  
TZOFFSETFROM:+0200  
TZOFFSETTO:+0100  
TZNAME:CET  
DTSTART:19701025T030000  
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10  
END:STANDARD  
END:VTIMEZONE

**Comment by HappyLer** [comment]
Ich habe es eben mal mit Google Calendar getestet und da hat es funktioniert.

**Comment by codeispoetry** [comment]
Dankeschön. Ich habe es eingebaut. Ab der Version 1.7.5 ist es enthalten.
