### ISSUE TITLE
Ical Import: alle Termine verschoben

### ISSUE THREAD

**Issue by Michelle-Wells** [codeispoetry/sunflower#300]
Der importierte Kalender funktioniert im Prinzip, nur wird beim Import die Zeitzone ignoriert und ALLE Termine werden mit Beginn 2 Stunden zu früh angezeigt. Bsp.: im Import-Kalender steht Beginn 19:30 Uhr auf der Homepage unter Termine steht 17:30 Uhr.

**Comment by codeispoetry** [comment]
Kannst du mir bitte einen link zum zu importierenden Kale der schicken oder hier posten?

**Comment by Michelle-Wells** [comment]
> Kannst du mir bitte einen link zum zu importierenden Kale der schicken oder hier posten?

https://wolke.netzbegruenung.de/remote.php/dav/public-calendars/YDtwfcXbpDoQjJ2x/?export

**Comment by b90g** [comment]
https://gruene-trier-saarburg.de/

ist auch bei verdigado eingegangen.

**Comment by Michelle-Wells** [comment]
Ja genau, das ist die Seite - lief parallel. Von verdigado wurde hierher verwiesen. Stellen die Veranstaltungen jetzt auf ganztägig um und legen einen "Test" Termin an.

**Comment by codeispoetry** [comment]
Ab der neuesten Version 1.3.2 kann man beim Kalenderimport in den Sunflowereinstellungen einen Haken setzen bei "Zeitzone korrigieren". damit müsste es gehen.

**Comment by Michelle-Wells** [comment]
Klappt jetzt, danke!
