### ISSUE TITLE
E_COMPILE_ERROR Fehler beim Upload nach Wordpress.com (v5.8)

### ISSUE THREAD

**Issue by Chapuisat** [codeispoetry/sunflower#301]
Hallo zusammen,

ich habe heute versucht das Sunflower Template in der Version 1.3.1 nach Wordpress Online (Wordpress v5.8 Tatum) zu laden, und zwar mehrfach, und es verursacht immer einen schwerwiegenden Fehler, so dass das Template sich nicht aktivieren lässt. 

Wordpress verschickt dann eine E-Mail zum Widerherstellen des Admin Dashboard und zeigt dann auch diese detaillierte Fehlermeldung an:

Fehler-Details 
============== 
Ein Fehler vom Typ E_COMPILE_ERROR wurde in der Zeile 4 der Datei /srv/htdocs/wp-content/themes/sunflower/functions/icalimport.php verursacht. Fehlermeldung: require_once(): Failed opening required '/wordpress/core/5.8//wp-content/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/Event.php' (include_path='/:.')

- Wurde das Template mit Wordpress Online getestet?
- Ist das Template mit Wordpress 5.8 Tatumkompatibel?
- Kann der Fehler in einer neuen Version beseitigt werden?

PHP7.3 und PHP7.4 versucht, leider ohne Erfolg. Ich vermute es liegt an der Tatum Kompatibilität. 

Danke im Voraus für Eure Feedback.

**Comment by Chapuisat** [comment]
So, nachdem ich den den Debug Modus aktiviert habe über wp-config.php, habe ich erneut den Hinweis auf das iCal Plugin bekommen:

```
[29-Jul-2021 21:13:40 UTC] PHP Warning:  require_once(functions/icalimport.php): failed to open stream: No such file or directory in /srv/htdocs/wp-content/themes/sunflower/functions.php on line 24
[29-Jul-2021 21:13:40 UTC] PHP Fatal error:  require_once(): Failed opening required 'functions/icalimport.php' (include_path='/:.') in /srv/htdocs/wp-content/themes/sunflower/functions.php on line 24
```

Ich habe es nun über SFTP entfernt und in der functions.php auskommentiert. Und siehe da, es läuft 👍 
Etwas stimmt mit dem ics-parser im Sunflower 1.3.1 Template nicht auf Wordpress online oder Wordpress 5.8.

**Comment by Chapuisat** [comment]
Weitere Fehler entdeckt:

- Im Footer fehlt bei "freie grüne **Theme sunflower** ‐ ein Angebot der verdigado eG." der Teil mit "Theme sunflower"
- Auf Startseite im Editor wird das Cover Modul fehlerhaft angezeigt: "In diesem Block ist ein Fehler aufgetreten und eine Vorschau ist nicht möglich." Es lässt sich nicht editieren.

**Comment by ErwinBehner** [comment]
Bei mir funktioniert das Theme fehlerfrei. Allerdings habe ich das Theme schon etwas länger installiert. Schon mal mit einer älteren Version versucht?
Die bei dir fehlenden johngrogg-Dateien, sind bei mir im Livesystem vorhanden, allerdings sind diese im Theme selbst nicht enthalten. Ich vermute, dass diese bei der Aktivierung nachinstalliert werden.

**Comment by codeispoetry** [comment]
Auf WordPress 5.8 funktioniert sunflower wie gewohnt.
Ist denn die Datei icalimport.php in der zip-Datei enthalten, die Du hochlädst?

**Comment by Chapuisat** [comment]
@ErwinBehner Ich habe es als frische Installation direkt in Wordpress.com v5.8 versucht. Da kommt es zu diesen Fehlern. Evtl. kommt es nicht vor, wenn es vorher schon drauf war. Jedenfalls hilft hinterher nur die gesamte Website Wiederherstellung, denn nichts geht mehr. 

Die johngrogg Dateien (icalimport.php und zusätzliche Funktion) habe ich dann selbst entfernt und das Template über SFTP hochgeladen. So hat es zumindest funkiotniert. Wie gesagt, andere Fehler treten noch auf, aber ich kann arbeiten.

@codeispoetry Geht es bei Dir auf einer v5.8 bei selbst gehostetem Wordpress oder bei Wordpress.com? Hast Du das Template vorher schon drauf gehabt und Upgrade auf v5.8 erst dann durchgeführt?
Ich habe das Sunflower Template 1.3.1 komplett heruntergeladen, alle Dateien sind dabei, auch die icalimport.php. Alles mehrfach geprüft.

**Comment by codeispoetry** [comment]
Ich nutzte WordPress in einer Dockerumgebung und wechsele munter die WordPress-Versionen.

Was mich wundert: Warum findet er die Datei icalimport nicht? Wenn sie im zip-File ist, warum ist sie nicht auf dem Server?

**Comment by ErwinBehner** [comment]
So wie ich Chapuisat verstanden habe, kam zunächst der Fehler mit den fehlenden johngrogg Dateien. Daraufhin hat er via SFTP die Datei icalimport gelöscht und dessen Aufruf in der function.php.

**Comment by ErwinBehner** [comment]
Der eigentliche Fehler sind somit die fehlenden johngrogg Dateien.

**Comment by codeispoetry** [comment]
Die johngropp-Dateien sind im zip-Ordner enhalten. Werden die auf dem Server nicht mit ausgepackt?

**Comment by ErwinBehner** [comment]
In welchem Pfad? In assets/vndr finde ich in der ZIP keinen Ordner johngrogg

**Comment by ErwinBehner** [comment]
OK. Jetzt habe ich's. Man darf nicht die ZIP von code erzeugen! sondern muss die ZIP von https://sunflower-theme.de/ nehmen

**Comment by ErwinBehner** [comment]
@Chapuisat Welche ZIP-Datei hast Du verwendet? Die vom Code oder die auf  https://sunflower-theme.de/ ?

**Comment by Chapuisat** [comment]
Ich habe sie direkt von der https://sunflower-theme.de/ Seite geladen, in der Version 1.3.1. Die Dateien sind nach dem Entdecken alle da, auch auf dem Wordpress.com Server, habe es über SFTP geprüft.

<img width="279" alt="Bildschirmfoto 2021-08-01 um 20 06 07" src="https://user-images.githubusercontent.com/47702103/127781020-405640d7-5278-4693-83ab-3b9c6e13a2ae.png">

**Comment by Chapuisat** [comment]
Und nochmals, der 'fatal error' tritt auf, wenn ich das .zip template direkt in wordepress.com einladen über das frontend oder blanko über SFTP. In beiden Fällen tritt der Fehler beim Aktivieren des Templates auf.

**Comment by Chapuisat** [comment]
Was mir aufgefallen ist, sind die beiden Pfade der erstgenannten Fehlermeldung:

`**/srv/htdocs/**wp-content/themes/sunflower/functions/icalimport.php `
und 
`**/wordpress/core/5.8//**wp-content/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/Event.php'`

Das `wp-content` hat eine völlig andere source. Ausserdem hat der Pfad zu den johngrogg Datei einen doppelten '//'

Keine Ahnung, ob das die Fehlerquelle sein kann.

**Comment by ErwinBehner** [comment]
Ja, ich denke darin liegt dann tatsächlich der Fehler.

**Comment by Chapuisat** [comment]
In der Datei `icalimport.php` wird die `Event.php` wie folgt aufgerufen. Das verursacht den Fehler. Ist ABSPATH die richtige Variable?

```
require_once ABSPATH . '/wp-content/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/Event.php';
require_once ABSPATH . '/wp-content/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/ICal.php';
```

**Comment by Chapuisat** [comment]
Spannend: 
[https://pressable.com/knowledgebase/abspath-and-pressable/](https://pressable.com/knowledgebase/abspath-and-pressable)

**Comment by ErwinBehner** [comment]
Exakt. Versuch mal
require_once WP_CONTENT_DIR . '/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/Event.php';
require_once WP_CONTENT_DIR . '/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/ICal.php';

**Comment by Chapuisat** [comment]
This makes the trick! 

Sehe gerade, es gibt eine neue Version, v1.3.4

Leider ist der Fehler dort immer noch drin.

**Comment by ErwinBehner** [comment]
Ja in V1.3.4 wurden andere Kleinigkeiten behoben. ;-)

**Comment by Chapuisat** [comment]
OK, Upgrade auf v1.3.4 gemacht, direkt online: Danach direkt wider fatal error:
<img width="821" alt="Bildschirmfoto 2021-08-01 um 20 46 40" src="https://user-images.githubusercontent.com/47702103/127782014-bbefd2df-d276-4895-a620-50b018d50b6d.png">

Im Debugger: 

```
[01-Aug-2021 18:44:24 UTC] PHP Warning:  require_once(/wordpress/core/5.8//wp-content/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/Event.php): failed to open stream: No such file or directory in /srv/htdocs/wp-content/themes/sunflower/functions/icalimport.php on line 4
[01-Aug-2021 18:44:24 UTC] PHP Fatal error:  require_once(): Failed opening required '/wordpress/core/5.8//wp-content/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/Event.php' (include_path='/:.') in /srv/htdocs/wp-content/themes/sunflower/functions/icalimport.php on line 4
[01-Aug-2021 18:44:24 UTC] PHP Notice:  Trying to access array offset on value of type bool in /wordpress/core/5.8/wp-includes/class-wp-recovery-mode-email-service.php on line 351
[01-Aug-2021 18:44:24 UTC] PHP Notice:  Trying to access array offset on value of type bool in /wordpress/core/5.8/wp-includes/class-wp-recovery-mode-email-service.php on line 352
```

Ich weiß jetzt was zu tun ist :-)

Wobei der Fehler class-wp-recovery-mode-email-service.php ist neu

**Comment by ErwinBehner** [comment]
class-wp-recovery-mode-email-service.php ist nicht Teil des Theme. 
Sieht für mich nach den Email-Benachrichtigungsdienst aus.

**Comment by Chapuisat** [comment]
OK, es läuft alles wieder, auch mit v1.3.4.

Eine Frage noch: Warum ergibt dieser Code:
<img width="899" alt="Bildschirmfoto 2021-08-01 um 21 00 19" src="https://user-images.githubusercontent.com/47702103/127782361-55fbf841-fa11-4c1a-8f13-df9e57038c3b.png">

diesen Output?

<img width="315" alt="Bildschirmfoto 2021-08-01 um 21 01 49" src="https://user-images.githubusercontent.com/47702103/127782406-71a70e0a-089a-4f91-96ba-a0fac89f361e.png">

bzw:
<img width="515" alt="Bildschirmfoto 2021-08-01 um 21 02 56" src="https://user-images.githubusercontent.com/47702103/127782446-7b1574bb-7ed7-4a7e-9921-18c4f90ccbd6.png">

Der gesamte Teil `<a href="https://sunflower-theme.de" target="_blank">sunflower</a>` fehlt einfach...

**Comment by Chapuisat** [comment]
Und die Seite wirft auch noch zwei 404 Fehler in der Console:

```
bootstrap.min.js.map
popper.min.js.map
```
<img width="1621" alt="Bildschirmfoto 2021-08-01 um 21 05 56" src="https://user-images.githubusercontent.com/47702103/127782542-49ba97a5-e83b-449a-8c76-907c3b32b909.png">

z.B. auch hier
https://filizpolat.de

https://filizpolat.de/wp-content/themes/sunflower/assets/vndr/bootstrap/dist/js/bootstrap.min.js.map
https://filizpolat.de/wp-content/themes/sunflower/assets/vndr/@popperjs/core/dist/umd/popper.min.js.map

**Comment by Chapuisat** [comment]
Es ist verrückt...

Wenn ich das Word des Links `<a href="https://sunflower-theme.de" target="_blank">sunflower</a>` ändere in z.B. **Joe Doe**, dann wird es angezeigt. Wenn ich wieder **sunflower** schreibe, ist es wieder alles weg. Jetzt habe ich vor das **sunflower** noch ein Leerzeichen eingesetzt und es wird angezeigt. What the heck?!

`<a href="https://sunflower-theme.de" target="_blank"> sunflower</a>`

Das ist in mehren Browsern, also kein Cache.

**Comment by ErwinBehner** [comment]
Bezüglich 404-Fehler: Ich finde bei mir nur die Aufrufe ohne das ".map" am Ende.
Die .map sind zwar in den jeweiligen js-Dateien erwähnt aber auskommentiert.

Bezüglich dem Phänomen des Verschwindens von "sunflower":  Kannst Du javascript im Browser mal komplett abschalten? Ist das Problem dann immer noch da?

**Comment by ErwinBehner** [comment]
@codeispoetry Bevor es verloren geht: bitte in der Datei `icalimport.php`

`require_once ABSPATH . '/wp-content/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/Event.php';`
`require_once ABSPATH . '/wp-content/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/ICal.php';`

ändern zu

`require_once WP_CONTENT_DIR . '/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/Event.php';`
`require_once WP_CONTENT_DIR . '/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/ICal.php';`

**Comment by codeispoetry** [comment]
Danke.

Mehr Infos: https://github.com/roots/bedrock/issues/560

Der Fehler wird in der kommenden Version behoben sein. Chapuisat kann dann ohne solche Fehler upgraden.

**Comment by Chapuisat** [comment]
> Bezüglich dem Phänomen des Verschwindens von "sunflower": Kannst Du javascript im Browser mal komplett abschalten? Ist das Problem dann immer noch da?

Hab das nochmals provbiert. Auch wenn ich JS in Safari oder Chrome deaktiviere wird der gesamte content von `Theme <a href="https://sunflower-theme.de" target="_blank"> sunflower</a>` nicht angezeigt. Das ist echt verrückt.

Ich kann demnach vor das `sunfower` ein **Leerzeichen** setzen, dann geht es. Ich kann aber auch das Wort **Theme** zu **Template** ändern und dann geht es ebenfalls. Das Muster `Theme sunflower` scheint ihn irgendwo zu stören.

**Comment by codeispoetry** [comment]
Hast du mal einen Link für uns, wo wir uns das anschauen können?

**Comment by Chapuisat** [comment]
Die Seite ist noch im Aufbau und noch nicht veröffentlicht, ich kann sie nur sehen, wenn ich eingeloggt bin. Wenn es aber public ist, dann teile ich sie gerne, so lange habe ich einen Workaround.
