### ISSUE TITLE
Nach Wechsel auf Sunflower ist die Termine-Seite weg 

### ISSUE THREAD

**Issue by guili2** [codeispoetry/sunflower#302]
Hallo zusammen, 

nachdem ich von Urwahl3000 auf Sunflower umgestiegen bin, ist die Seite 'Termine' aus meinem Dashboard-Menü bei Wordpress verschwunden.  

Wäre super, wenn mir jemand helfen könnte! 

Liebe Grüße!

**Comment by ErwinBehner** [comment]
Werden keine Termine mehr angezeigt oder ist tatsächlich der Menüeintrag auf der linken Seite weg?
![image](https://user-images.githubusercontent.com/87278465/127765935-921e1bd3-f42d-40ba-9cba-cc6de7425d4f.png)

**Comment by guili2** [comment]
Der Menüeintrag 'Termine' ist weg und jetzt ist ein Menüeintrag 'Events' da. Wenn ich da was eintrage, erscheint es aber nicht auf der Seite 'Termine'. Ich habe auch versucht, irgendwie eine neue Seite zu erstellen, die dann die 'Events' anzeigt - war aber erfolglos.

**Comment by codeispoetry** [comment]
Hast Du mal einen Link zu der Seite bitte?

**Comment by guili2** [comment]
https://peter-seimer.de

**Comment by codeispoetry** [comment]
Dass da Events statt Termine steht, könnte daran liegen, die die Sprache von WordPress auf Englisch eingestellt ist statt auf Deutsch. Das kannst du in den WordPress'Einstellungen ändern

**Comment by guili2** [comment]
Es war 'Deutsch' eingestellt. Die Termine, die unter 'Events' eingestellt wurden, werden nicht auf der Seite 'Termine' angezeigt. Es erscheint nur '[wpcalender]'. Kann man das irgendwie ändern? 

Ich hätte auch ein weiteres Problem: Auf der Startseite werden Ausschnitte der letzten vier Beiträge angezeigt. Um den restlichen Beitrag anzuschauen, muss man auf 'Continue Reading' drücken. Kann ich das noch auf Deutsch umändern? 

Es werden allgemein einige Sachen auf Englisch angezeigt, obwohl 'Deutsch' eingestellt ist und auch schon davor war.

**Comment by codeispoetry** [comment]
das "continue reading" sollte nur erscheinen, wenn die Sprache nicht auf Deutsch eingestellt ist. Das ist wirklich sehr unerwaretet.

**Comment by ErwinBehner** [comment]
Irgendwo muss da noch etwas auf englisch eingestellt sein. Siehe https://peter-seimer.de/termine/
Ggf. vielleicht vom Website-Hoster.

**Comment by guili2** [comment]
@ErwinBehner und wie kann man das vom Website-Hoster ändern? Im Dashboard-Menü ist auch ein Menüeintrag 'Sunflower'. Bei diesem Eintrag ist alles auf Englisch - vielleicht hat es damit was zu tun? Obwohl ich da schon gesucht habe, um zu schauen, ob man das auf Deutsch ändern kann, habe aber nichts gefunden. 

@codeispoetry, wie kann ich das mit der Termine-Seite auf die Events umändern, damit nicht mehr [wpcalender] erscheint, sondern die Einträge?

**Comment by ErwinBehner** [comment]
Ich denke, da müsstest Du Deinen Website-Hoster fragen. Vielleicht kann @codeispoetry Dir dazu noch verraten wie Sunflower die Sprache erkennt.
Damit statt [wpcalender] die Terminseite angezeigt wird, müsstest Du den Menüeintrag ändern. Bei mir ist unter "Termine" ein Eintrag "Termine" vorhanden. Ich vermute dass dies bei Dir "Events" heißen wird.

**Comment by guili2** [comment]
@ErwinBehner danke für die Hilfe!
