### ISSUE TITLE
Wenn zu viele Einträge im Menü sind, werden die "Ausklapppfeile" für Untermenüs umgebrochen

### ISSUE THREAD

**Issue by larsschellhas** [codeispoetry/sunflower#304]
Wenn zu viele Einträge im Menü sind, werden die "Ausklapppfeile" für Untermenüs umgebrochen.

![image](https://user-images.githubusercontent.com/14281234/127773963-85b96dd1-cffa-4abb-a8f4-f12079d7c78c.png)

Hier wäre es schöner, wenn die Pfeile innerhalb der <li> Tags nicht umgebrochen werden, sondern die Listenelemente als ganzes.
Entfernt man "flex-wrap: wrap;", ist das Problem gelöst. Nur werden dann Untermenüs im mobilen Menü nicht unterhalb sondern eben neben dem Eintrag dargestellt.

Die eleganteste Lösung wäre es sicherlich, den "submenu-opener" gar nicht erst als eigenes <div> einzufügen, sonder via CSS eine :after property für alles <a class="dropdown-toggle"> Elemente einzufügen.

**Comment by codeispoetry** [comment]
Danke für den Bugreport und auch den Tipp mit dem Pseudo-Element. Das ist tatsächlich die elegantere Lösung. Aber auch mit :after wrappt es noch um. Ich habe deshalb folgenden Code nun 
` flex-wrap: wrap;
            @include media-breakpoint-up(md) { 
                flex-wrap: nowrap;
            }`

**Comment by codeispoetry** [comment]
Und zusätzlich alles als :after-Pseudeoelement

**Comment by larsschellhas** [comment]
Danke für die schnelle Antwort! Gut, wenn du eine passende Lösung gefunden hast :) 
Ich habe vermutlich vergessen, den gesamten Inhalt des <a> Tags mit dem Pseudoelement dann nochmal über display: flex; nebeneinander zu setzen, bzw. kein flex-wrap innerhalb des <a> Tags zu nutzen. 😄

**Comment by codeispoetry** [comment]
Ist in Version 1.3.3 behoben. Das mit dem after musste ich aber wieder rausnehmen, weil es zu anderen Komplikationen führte.
