### ISSUE TITLE
Fußzeilenmenüeinträge mit mehreren Wörtern werden umgebrochen, obwohl Platz da ist

### ISSUE THREAD

**Issue by larsschellhas** [codeispoetry/sunflower#305]
Wenn ein Menüeintrag mehrere Wörter enthält wird er automatisch umgebrochen, weil keine width-Property eingestellt ist. 
![image](https://user-images.githubusercontent.com/14281234/127775711-87e7aee1-f417-4431-9d16-6c7f71d6e404.png)

Mit diesem CSS-Eintrag werden die Menüeinträge korrekt dargestellt:
.site-footer .navbar-nav .nav-link {
    width: max-content;
}

Dann gibt es noch das Problem des Überlaufs, wenn zu viele Menüeinträge vorhanden sind.
Wenn ich das richtig sehe, ist jedem Menü eigentlich eine Drittel-Fußzeile zugewiesen, allerdings ist als flex-direction "row" festgelegt, wodurch die Menüs automatisch aus diesem Drittel herausfließen.

**Comment by larsschellhas** [comment]
Letzteres ist wohl auch eigentlich ein eigenständiges Issue, da es bei zwei Menüs zu diesem Problem hier führt:
![image](https://user-images.githubusercontent.com/14281234/127776367-55002386-d8b1-4c72-8f24-d163bd3a5e8b.png)

**Comment by codeispoetry** [comment]
Vielen Dank für den Hinweis. Ich habe das durch ein ` flex-wrap: wrap;` gefixed. lädt gerade hoch

**Comment by larsschellhas** [comment]
Sieht gut aus! ;)
