### ISSUE TITLE
Blockquote funktioniert nicht

### ISSUE THREAD

**Issue by tmaterna** [codeispoetry/sunflower#306]
In der HTML Bearbeitung funktioniert Blockquote nicht. Das ist sehr ärgerlich. Bitte beheben.

**Comment by codeispoetry** [comment]
Hallo,

schade, dass es Dich ärgert. Das darf natürlich nicht sein. 
Um einen Fehler beheben zu können, brauche ich in der Regel mehr Angaben.

Bei mir im Test funktioniert der WordPress-Block Zitat fehlerfrei, auch in der HTML-Ansicht.

Liebe Grüße und ärgere Dich nicht so sehr,

Tom

**Comment by tmaterna** [comment]
Hi,

was brauchst Du denn noch für Angaben?

Ich rede nicht vom Zitatblock sondern vom <blockquote> Befehl….




--
Mit freundlichen Grüßen,
Torsten Materna
Geschäftsführung / Digitales Marketing



numero2 - Agentur für digitales Marketing GbR
Mozartstrasse 3, 67480 Edenkoben
Tel: (06323) 93 81 86
Web: www.numero2.de
Am 2. Aug. 2021, 11:31 +0200 schrieb Thomas Rose ***@***.***>:

**Comment by codeispoetry** [comment]
Wie ist denn das Vorgehen, um den Fehler zu reproduzieren? Was muss ich wo tun?

**Comment by tmaterna** [comment]
Hi,

Textblock anlegen.
Bearbeitung auf HTML umschalten
<blockquote></blockquote> beim Absatz ergänzen.
Wird nicht akzeptiert...


--
Mit freundlichen Grüßen,
Torsten Materna
Geschäftsführung / Digitales Marketing



numero2 - Agentur für digitales Marketing GbR
Mozartstrasse 3, 67480 Edenkoben
Tel: (06323) 93 81 86
Web: www.numero2.de
Am 2. Aug. 2021, 12:00 +0200 schrieb Thomas Rose ***@***.***>:

**Comment by codeispoetry** [comment]
Dankeschön.
Das ist ein Standardblock von WordPress, der nicht vom Theme stammt. Das Verhalten ist also unabhängig von _sunflower_

Vermutlich musst Du entweder einen HTML-Block nehmen, der erlaubt vielleicht diesen Tag, oder Du nimmst den Block "Zitat".

**Comment by tmaterna** [comment]
Zitat ist nicht hilfreich.

Es geht um die Einrückung bei Nummerierungen.

Also:

1.
2.
3.
	3.1 <— die Einrückung fehlt...
	xxxxx  Textzeile  xxxxx
	xxxxx  Textzeile  xxxxx
	3.2
	xxxxx  Textzeile  xxxxx
	xxxxx  Textzeile  xxxxx
4.

Wie kann ich sowas denn machen? Funktioniert leider überhaupt nicht und ist gerade bei Anträgen etc. zwingend notwendig.


--
Mit freundlichen Grüßen,
Torsten Materna
Geschäftsführung / Digitales Marketing



numero2 - Agentur für digitales Marketing GbR
Mozartstrasse 3, 67480 Edenkoben
Tel: (06323) 93 81 86
Web: www.numero2.de
Am 2. Aug. 2021, 14:25 +0200 schrieb Thomas Rose ***@***.***>:

**Comment by ErwinBehner** [comment]
Blockquote ist nichts andereres als ein Zitat. Siehe https://wiki.selfhtml.org/wiki/HTML/Elemente/blockquote 
Dir geht es um eine Einrückung aufgrund eines nummerierten Listenelements. Da ist Blockquote eigentlich das Falsche auch wenn dies bei manchen Themes das gewünschte Ergebnis bringt. Die Gestaltung der Zitatfunktion ist themeabhängig unterschiedlich.
Ich empfehle Dir hier https://wiki.selfhtml.org/wiki/HTML/Tutorials/Listen/Aufz%C3%A4hlungslisten

**Comment by tmaterna** [comment]
Hi,

schau mal, was ich mache... beruflich Webseiten. Zwar nicht mit WP aber dennoch. Ich habe jeden HTML bzw. CSS Style ausprobiert, keiner funktioniert. Da war meine Vermutung, das es am Theme liegen könnte. CSS Styles gehen genauso wenig, was auch seltsam ist. Ich kenne WP nicht richtig, darum meine Frage, ob das am Theme liegt...


--
Mit freundlichen Grüßen,
Torsten Materna
Geschäftsführung / Digitales Marketing



numero2 - Agentur für digitales Marketing GbR
Mozartstrasse 3, 67480 Edenkoben
Tel: (06323) 93 81 86
Web: www.numero2.de
Am 2. Aug. 2021, 20:38 +0200 schrieb Erwin Behner ***@***.***>:

**Comment by codeispoetry** [comment]
Wie gesagt, es gibt einen Block für freies HTML. Darin kannst du HTML und CSS schreiben, ohne dass es verändert wird.
