### ISSUE TITLE
Zeitzone korrigieren - korrigiert nur die Startzeit

### ISSUE THREAD

**Issue by holloween** [codeispoetry/sunflower#307]
Beim Import des Google Kalender muss die Zeitzone korrigiert werden. Das funktioniert aber nur für die Startzeit, die Endezeit bleibt unverändert. Auch ein neuer Import ändert das nicht.

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Ist aber der aktuellen Version 1.3.5 behoben.
