### ISSUE TITLE
Fehler bei Startseite

### ISSUE THREAD

**Issue by felixharling** [codeispoetry/sunflower#310]
Wenn ich in WP auf der Startseite z.B. einen Block "Neueste Beiträge" einfüge und dann speichere kommt die Fehlermeldung "Aktualisierung fehlgeschlagen. Die Antwort ist keine gültige JSON-Antwort."? Was nun?

**Comment by codeispoetry** [comment]
Tritt der Fehler noch auf? Welche Version von Sunflower und WordPress benutzt du?
