### ISSUE TITLE
Importierte Termine: Uhrzeit falsch

### ISSUE THREAD

**Issue by softmetz** [codeispoetry/sunflower#312]
Ich kann leider nicht sagen, ob es von Anfang an so war, aber die Termine fangen bei uns alle 2h zu früh an, so als würden die Inputs als UTC interpretiert.

Quell-Kalender ist in der Wolke (Zeitzone lt. Nextcloud Europe/Berlin) und in Wordpress ist ebenfalls Europe/Berlin als Zeitzone hinterlegt.

**Comment by ErwinBehner** [comment]
Siehe https://github.com/codeispoetry/sunflower/issues/300

**Comment by softmetz** [comment]
@ErwinBehner Das war's, danke!
