### ISSUE TITLE
Autocomplete bei Termindaten deaktivieren

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#315]
![image](https://user-images.githubusercontent.com/63392812/129522760-a6c783b1-462f-493f-8c14-d0a309cd036b.png)

Weiß nicht obs dafür n Browser schnipsel gibt der sagt dass diese Formdaten nicht gespeichert werden müssen.

**Comment by codeispoetry** [comment]
Ich konnte den Fehler bei mir nicht nachstellen, habe aber mal autocomplete="off" hinzugefügt. Ich schließe das Ticket einstweilen, wenn das Verhalten noch auftritt, öffne es bitte wieder
