### ISSUE TITLE
Theme nicht installierbar unter WordPress 5.8

### ISSUE THREAD

**Issue by gruenemw** [codeispoetry/sunflower#318]
Fehlermeldung:

Installiere Plugin aus hochgeladener Datei: sunflower.zip

Entpacken des Pakets …

Das Plugin wird installiert …

Das Paket konnte nicht installiert werden. Es wurden keine funktionsfähigen Plugins gefunden.

Plugin-Installation fehlgeschlagen.

Weiter zur Plugin-Installation

**Comment by gruenemw** [comment]
Hallo zusammen,
wir wollen unsere alte Homepage auf WordPress umstellen, ich habe WordPress (paket von Bitnami) lokal auf meinem PC unter Windows 10 installiert und mit Urwahl3000 begonnen, die Homepage aufzubauen. 
Jetzt wollte ich "sunflower" installieren, um gleich damit zu starten. Konvertierungsprobleme beim Wechsel von Urwahl3000 zu sunflower intessieren mich nicht, ich habe noch nicht viel eingerichtet.
Viele Grüße
Klaus

**Comment by gruenemw** [comment]
Die Installation beim Provider (1blu, wahrscheinlich Linux) funktioniert auch nicht, WordPress-Version ist ebenfalls 5.8

**Comment by ErwinBehner** [comment]
In welchen Ordner hast Du https://sunflower-theme.de/updateserver/sunflower.zip den abgelegt?

Wenn ich  
> installiere Plugin aus hochgeladener Datei: sunflower.zip
lese, scheint es der Plugin-Ordner gewesen zu sein und nicht der Theme-Ordner.
