### ISSUE TITLE
Startseite

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#32]
- [x] Termine
- [x] Beiträge
- [x] Beiträge auf der Startseite: is_singular -fix

**Comment by codeispoetry** [comment]
@designerin schau mal, auf der Startseite habe ich nun die Termine eingebaut. Es ist derzeit exakt das gleicheLayout wie auch in der Übersicht der Termine.

**Comment by codeispoetry** [comment]
Unter http://localhost/demo/category/antraege/ siehst Du, wie so ein Antrag aussehen könnte

**Comment by codeispoetry** [comment]
Die Beiträge sind nun auch auf der Startseite, die müssen allerdings noch feingetuned werden

**Comment by designerin** [comment]
Hallo Tom, 

danke für die Infos und die Umsetzung. Ich schaue mir das heute mal in Ruhe an und gebe dir Feedback. :)

Liebe Grüße, 
Regina

___________________

Regina Rüttiger
Kommunikationsdesign
Gabelsbergerstraße 6
97080 Würzburg
Telefon 0176 544 182 15
Regina.Ruettiger@gmx.de
