### ISSUE TITLE
Cover mit Text werden nicht korrekt angezeigt

### ISSUE THREAD

**Issue by msbrt** [codeispoetry/sunflower#322]
Ab Wordpress 5.8.1. werden Cover nicht richtig angezeigt:

So soll es aussehen:
![image](https://user-images.githubusercontent.com/91658507/135408398-7b7c7fe0-0c5e-4df9-acd6-9c108d811815.png)

So sieht es aus:
![image](https://user-images.githubusercontent.com/91658507/135408538-b28c5ff6-157d-455c-b055-24012ee1bd7f.png)

Es gibt einen "halben" Workarround, in dem man in den Einstellungen der Blocks: Cover, Medieneinstellungen den Haken bei "Hintergrund fixieren" setzt. Dadurch geht jedoch die Möglichkeit verloren, einen Fokus-Bereich auszuwählen, was aber für die Darstellung auf Smartphones hinderlich ist. 

![image](https://user-images.githubusercontent.com/91658507/135409087-6a146968-3014-434d-a477-3093ca0298f8.png)

Spätestens bei mehreren Covern nebeneinander kommt man damit nicht weiter:

Soll:
![image](https://user-images.githubusercontent.com/91658507/135409668-92d0a9a6-4932-4163-b9a0-3adfcf7fb9e9.png)

Ist:
![image](https://user-images.githubusercontent.com/91658507/135409706-610bb45e-619a-459e-bf41-cbe8c98463c3.png)

Interessanterweise tritt dieser Fehler erst auf, wenn eine Seite nach dem Update auf Wordpress 5.8.1 erstmals verändert wird. 
Mir ist unklar, ob das Problem beim neuen Gutenberg-Editor liegt, oder ob hier auf Theme-Ebene etwas getan werden kann.

Würde mich auf jeden Fall freuen, wenn mir hier jemand weiterhelfen könnte.

**Comment by codeispoetry** [comment]
Hast Du einen Link für mich, wo ich mir das mal ansehen kann?
