### ISSUE TITLE
Fehler bei Umstellung von Urwahl auf Sunflower - Seite nicht mehr errreichbar!

### ISSUE THREAD

**Issue by MareikeForchheim** [codeispoetry/sunflower#325]
Bei der Umstellung von Urwahl auf Sunflower bekomme ich folgende Fehlermeldung:
Fatal error: Uncaught Error: Call to undefined function register_block_type() in /homepages/40/d22196824/htdocs/wordpress/wp-content/themes/sunflower/functions/blocks.php:13 Stack trace: #0 /homepages/40/d22196824/htdocs/wordpress/wp-includes/class-wp-hook.php(286): sunflower_block_enqueue('') #1 /homepages/40/d22196824/htdocs/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /homepages/40/d22196824/htdocs/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /homepages/40/d22196824/htdocs/wordpress/wp-settings.php(450): do_action('init') #4 /homepages/40/d22196824/htdocs/wordpress/wp-config.php(83): require_once('/homepages/40/d...') #5 /homepages/40/d22196824/htdocs/wordpress/wp-load.php(37): require_once('/homepages/40/d...') #6 /homepages/40/d22196824/htdocs/wordpress/wp-blog-header.php(13): require_once('/homepages/40/d...') #7 /homepages/40/d22196824/htdocs/wordpress/index.php(17): require('/homepages/40/d...') #8 {main} thrown in /homepages/40/d22196824/htdocs/wordpress/wp-content/themes/sunflower/functions/blocks.php on line 13

Sie erscheint, wenn man versucht die Seite aufzurufen und ich komme nicht mehr ins Backend bei Wordpress. Was kann ich tun? Danke!

**Comment by codeispoetry** [comment]
Welche WordPress-Version verwendest Du?

**Comment by MareikeForchheim** [comment]
Ich bin nicht ganz sicher, aber ich denke 5.8.2.

**Comment by codeispoetry** [comment]
Kannst du per FTP auf den Server und das Verzeichnis themes/sunflower löschen?

**Comment by MareikeForchheim** [comment]
Hat geklappt. Wir konnten die Seite immerhin wieder herstellen, haben jetzt aber erst einmal Urwahl wieder aktiviert. Was müssen wir denn beachten, wenn wir auf Sunflower umstellen wollen?

**Comment by codeispoetry** [comment]
Kannst du mir mal bitte posten, welche WordPress-Version und welche php Version ihr nutzt? 
Damit ich den Fehler mal nachbauen kann.

**Comment by MareikeForchheim** [comment]
WordPress 4.9.18... Ich würde das mal aktualisieren. Meinst du das reicht dann um es umzustellen?

**Comment by codeispoetry** [comment]
Ja, wenn du auf die neuste Version upgradest, müsste sunflower laufen.

**Comment by MareikeForchheim** [comment]
Vielen Dank!!
