### ISSUE TITLE
 Ausklappmenüs Mobile

### ISSUE THREAD

**Issue by Julime** [codeispoetry/sunflower#326]
Ich habe mobile ein Problem, dass sich an #211 anschließt.
Bei uns kommt noch dazu, dass die Hauptmenüpunke nur Platzhalter für das Untermenü sind (Link auf #). Beim klicken auf den Link passiert also nichts. 
Es wäre eine Option nötig, den Klick auf den Link genau so funktionieren zu lassen wie ein Klick auf den Pfeil.

**Comment by codeispoetry** [comment]
Hast Du einen Link, wo ich mir das ganze mal konkret anschauen kann?

**Comment by Julime** [comment]
https://gruene-leer.de/

**Comment by codeispoetry** [comment]
Ab der nun aktuellen Version 1.4.0 gibt es in den Sunflower-Einstellungen die Möglichkeit, das einzustellen.
Damit werden im Menü alle Einträge auch mobil klickbar, die als Verweisziel eine Raute # haben.
