### ISSUE TITLE
Fehlermeldung Loginseite limitieren

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#327]
Die Login-Seite gibt zu detailierte Fehlermeldungen aus. Ob ein Account existiert ist für Anwenderinnen meist nicht interessant.

```
function no_wordpress_errors(){
return ‘Sie konnten nicht eingeloggt werden. Bitte prüfen Sie Ihre Angaben.’;
}
add_filter( ‘login_errors’, ‘no_wordpress_errors’ );
```

Vorschlag von Parteimitglied: https://chatbegruenung.de/channel/sunflower-wordpress?msg=X3GrarbvQK4HSDv3y

**Comment by codeispoetry** [comment]
Dankeschön. Ist ab 1.5.0 eingebaut.
