### ISSUE TITLE
Sticky menu verschwindet hinter der Adminleiste, wenn man eingeloggt ist

### ISSUE THREAD

**Issue by larsschellhas** [codeispoetry/sunflower#329]
Sticky menu verschwindet hinter der Adminleiste, wenn man eingeloggt ist. Da das Menü anscheinend durch JS sticky gemacht wird, könnte man in der entsprechenden Funktion prüfen, ob es ein Element #wpadminbar gibt und falls ja, "top" auf 32px und margin-top des Contents auf 81px (49+32) setzen.

Alternativ könnte man beim Laden der Seite einmalig prüfen, ob die Adminbar existiert, dem Body eine entsprechende Klasse hinzufügen und die unterschiedlichen Stylings über CSS umsetzen.

Oder das Menü/den ganzen Header via "position: sticky; top: XX px" positionieren.

**Comment by codeispoetry** [comment]
Danke für den HInweis und den Lösungsvorschlag. Das werde ich gerne so einbauen.
Es wird ja body_class() verwendet, das baut auch schon einen Klassennamen 'admin-bar' ein, über den man das gut regeln kann.

Interessanterweise fehlt der Klassenname auf der Startseite, sonst ist er überall mit dabei

**Comment by larsschellhas** [comment]
Ja, ich hatte mich auch gewundert, dass sie da fehlte und ging dadurch davon aus, dass sie überall fehlt :D

--
Lars Schellhas, M.Sc.

Graf-von-Schwerin-Straße 15
14469 Potsdam
Germany

***@***.***
+4915739621504
________________________________

**Comment by codeispoetry** [comment]
sunflower hat die Klassenname auf der Startseite überschrieben, deshalb fehlt dort das admin-bar. Im nächsten Release wird das behoben sein. Danke für den Hinweis

**Comment by codeispoetry** [comment]
Dankeschön. Ist ab 1.5.0 eingebaut.
