### ISSUE TITLE
Kritischer Fehler mit ics-parser - Website nicht mehr verfügbar

### ISSUE THREAD

**Issue by dammhannes** [codeispoetry/sunflower#331]
Hi,

ich habe eben versucht auf meiner website (hannes-damm.de) von Version 1.3.5 auf 1.5.1 zu wechseln. Nach der Installation wurde das Theme mit folgendem Fehler gestoppt:

Ein Fehler vom Typ E_COMPILE_ERROR wurde in der Zeile 4 der Datei /home/sites/site100018497/web/hannes-damm.de/wp-content/themes/sunflower1/functions/icalimport.php verursacht. Fehlermeldung: require_once(): Failed opening required '/home/sites/site100018497/web/hannes-damm.de/wp-content/themes/sunflower/assets/vndr/johngrogg/ics-parser/src/ICal/Event.php' (include_path='.:/usr/share/php7:/usr/share/php')

Die Website war nicht mehr zu erreichen, bis ich auf 1.3.5 zurück gegangen bin.

Folgendes habe ich in 1.5.1 noch versucht: deaktivieren und später deinstallieren meines Kalender-Plugins "Simple Calendar". Leider ohne Erfolg, selbst bei nochmaliger Installation von 1.5.1 danach.

Ich bin jetzt erstmal zurück auf 1.3.5 und zufrieden damit, aber das Problem sollte man ja ergründen.

viele Grüße,
Hannes

-----------------------------------------

Ich bin auf WordPress 5.8.3

Folgende Plugins sind intalliert:
Akismet Anti-Spam Version 4.2.1 (Deaktiviert)
Collapse-O-Matic Version 1.8.2
Download Free Images Version 1.4.0
Embed Privacy Version 1.3.6 
Embedly Version 4.9.2
Hello Dolly Version 1.7.2 (Deaktiviert)
Simple Calendar Version 3.1.36
UpdraftPlus – Sichern/Wiederherstellen Version 1.16.69
WP Event Aggregator Version 1.6.3 (Deaktiviert)
WP Super Cache

**Comment by codeispoetry** [comment]
Danke für die Fehlermeldung. Da war ein veraltetes zip-File als 1.5.1 markiert. Das habe ich jetzt behoben. Ich hoffe, es geht jetzt. Die fehlende Datei ist auf jeden Fall im zip-File enthalten.

Bitte entschuldige die Unannehmlickeiten.

**Comment by dammhannes** [comment]
Das hat geklappt, danke!
