### ISSUE TITLE
Update WordPress 5.9: JavaScript Errors editing Posts & Pages

### ISSUE THREAD

**Issue by cubehrends** [codeispoetry/sunflower#334]
Update WordPress 5.9:
Staging at MITTWALD. Sunflower with recommended Plugins (Download Free Images, Embed Privacy) only.

Theme Sunflower active (Brave Developer Tools):
![image](https://user-images.githubusercontent.com/19872314/152155160-3dcf3d7e-59c7-45b9-b248-30ea6a7f635b.png)

Theme Twenty Twenty-Two active (Brave Developer Tools):
![image](https://user-images.githubusercontent.com/19872314/152155463-9b329327-5b91-4445-b74d-c62978653f3f.png)

These errors prevent Gutenberg Blocks from working properly.

**Comment by cubehrends** [comment]
Hallo Tom, das Problem besteht leider immer noch. Gerade getestet auf einem nackten WordPress 5.9.1 mit ausschließlich Sunflower 1.6.1 aktiv.

**Comment by codeispoetry** [comment]
Der Fehler ist behoben und wird ab der kommenden Version 1.7.1 gefixed sein. Diese neue Version wird Anfang der Woche veröffentlicht

**Comment by codeispoetry** [comment]
Danke für den Bugreport
