### ISSUE TITLE
Schlagworte/Keywords Overflow 

### ISSUE THREAD

**Issue by danijoo** [codeispoetry/sunflower#337]
Wordpress Version: 5.9
Sunflower: 1.5.1

Das Layout im "Neuste Beiträge" Block scheint Probleme damit zu haben, wenn man viele Keywords/Schlagworte auswählt und diese in einer für das Layout ungünstigen Reihenfolge kommen. Die Wörter ragen dann über die Grenzen des Beitrags hinaus. Siehe Beispiel.

![overflow](https://user-images.githubusercontent.com/4690162/151966154-2946b04f-6d54-4853-9a68-18d9af5ebe94.png)

**Comment by codeispoetry** [comment]
Danke für den Bugreport. Das wird in den nächsten Tagen gefixed.

**Comment by codeispoetry** [comment]
Hast Du einen Link für mich? Ich kann den Fehler bei mir lokal nicht nahstellen, bei mir wird richtig umgebrochen.

**Comment by danijoo** [comment]
Habe zum testen eine Seite ohne Zusätzliche Layout blocks erstellt: https://www.gruene-griesheim.de/test-seite/

Bei den Posts "Planlos, Ambitionslos und ohne Weitblick" und "Ein DadiLiner ist kein Stadtbus(Ersatz)" kann man beobachten dass der div für  Keywords und Kategorien größer ist als der Textbereich.

**Comment by codeispoetry** [comment]
Danke. Ich hatte zwar viele Schlagwörter, aber die hatten Leerzeichen oder Minus-Zeichen, deshalb ging es bei mir. In der eben veröffentlichten Version 1.5.2 ist der Fehler behoben.
