### ISSUE TITLE
Termine werden nicht angezeigt

### ISSUE THREAD

**Issue by seytr** [codeispoetry/sunflower#340]
Unter Events habe ich einige Termine eingetragen. Unter Design -> Menüs finde ich unter "Menüeinträge hinzufügen" Seiten, Beiträge, Events usw., aber unter Events wieder die einzelnen Eventseiten. Die könnte ich zwar "Zum Menü hinzufügen", aber das ist ja nicht Sinn der Sache. Einen Eintrag "Termine" finde ich nirgendwo, auch das Zahnrad rechts oben gibt es nicht. "Permalinkstruktur neu einlesen" hat auch nicht geholfen.
Ich habe jetzt einen individuellen Link nach http://xxx.de/termine angelegt und den einem Menü hinzugefügt. Das geht. Ich frage mich aber, warum die eigentliche Vorgehensweise nicht funktioniert und was ich falsch mache.

Josef

**Comment by codeispoetry** [comment]
Hallo,

kennst Du die Dokumentation unter https://sunflower-theme.de/documentation/events/#ubersichtsseite-im-menu-einfugen
Bist Du diesem Vorgehen gefolgt:

- Design > Menüs
- Termine > alle anzeigen
- Den obersten Eintrag zum Menü hinzufügen

Wenn Du keine "Termine" siehst, klicke rechts oben auf das Zahnrad und blende Termine ein.

**Comment by seytr** [comment]
Hallo,
das habe ich alles gelesen. Bei mir steht statt "Termine" "Events". Das habe ich angeklickt und dann leider nicht auf "alle" gedrückt. Ich habe nach "alle anzeigen" gesucht und nicht gefunden, auch nicht das Zahnrad. Wenn ich "alle" drücke erscheint als erster Eintrag "Events". Und von ich das markiere und ins Menü einfüge geht alles wunderbar. Sorry, war ein dummer Fehler von mir.
Aber, eine weitere dumme Frage, wie ersetze ich "Events" durch "Termine"?
Vielen Dank
Josef

**Comment by seytr** [comment]
Auch das ist gelöst. Ich hatte die Webseite übernommen und als Sprache war eingestellt Deutsch(Sie). Ich habe umgestellt auf "Deutsch" und jetzt steht auch "Termine" da.

**Comment by codeispoetry** [comment]
Danke für die Info. Das mit Deutsch (Sie) ist mir neu. Das schaue ich mir noch mal an.
