### ISSUE TITLE
Menü in der Kopfzeile fehlt auf Mobilgeräten

### ISSUE THREAD

**Issue by grueneedv** [codeispoetry/sunflower#342]
Hallo, 
auf Mobilgeräten wird das Menü in der Kopfzeile aktuell nicht dargestellt. Da dort oft auf das Impressum und Datenschutz verwiesen wird, fehlen diese Links auf Mobilgeräten. Man verstößt auf diesen Geräten somit unwissentlich gegen die DSGVO.

**Comment by codeispoetry** [comment]
Hallo,

das Menü rutscht mobil ans untere Seitenende und ist weiterhin erreichbar. Dass das Impresum am Seitenende steht, ist erlaubt.

**Comment by grueneedv** [comment]
Danke für die Info. Ich hatte das von einem Mitglied per E-Mail erhalten und bei einem kurzen Check am iPhone ist mir nicht aufgefallen, dass das am Seitenende angezeigt wird. Nach deinem Hinweis hab ich es dort finden können. Danke!
