### ISSUE TITLE
Zeitzone fehlt bei Online-Veranstaltungen

### ISSUE THREAD

**Issue by BaGerhard** [codeispoetry/sunflower#344]
Wird ein Termin als Online-Veranstaltung angelegt, fehlt die Information bzgl. Zeitzone. Dadurch ist die Start- und Endzeit beim schema.org identisch:

startDate | 2022-02-24T19:00:00
-- | --
endDate | 2022-02-24T19:00:00

Eine Eingabe   2022-02-24T19:00:00+01:00 ist nicht möglich.

**Comment by codeispoetry** [comment]
Danke für den Bugreport. Statt das Enddatum wurde das Startdatum doppelt angezeigt. Ab der aktuellen Version 1.6.1 ist der Fehler behoben.
