### ISSUE TITLE
Problem beim Archivieren von Terminen aus externen Quellen

### ISSUE THREAD

**Issue by smnvdl** [codeispoetry/sunflower#348]
Es scheint ein Problem zu geben beim Archivieren von vergangenen Veranstaltungen, welche aus externen Kalendern (z.B. der Grünen Wolke) synchronisiert werden. Diese Termine verschwinden im Backend aus der Terminliste, sobald der Termin in der Vergangenheit liegt und der Kalender neu synchronisiert wird. Dementsprechend werden sie im Frontend auch nicht bei den vergangenen Terminen angezeigt. Die entsprechende Option in den Sunflower-EInstellungen zum Archivieren der Termine ist natürlich aktiviert. Bei manuell erstellten Terminen tritt dieses Problem nicht auf.

**Comment by codeispoetry** [comment]
Es gibt nun einen nightly-build, den kannst Du per ab sofort per Hand bei Dir installieren. Du findest ihn unter
https://sunflower-theme.de/updateserver/nightly/sunflower.zip

In der nächsten Version wird diese Funktion enthalten sein, Du bist also updatesicher.

Aus der Doku unter https://sunflower-theme.de/documentation/events/#anzahl-der-zu-importierenden-termine-festlegen

`Von Haus aus werden vergangene Termine nicht mehr importiert. Um das zu ändern, kann Du in der wp-config.php folgendes eintragen:

define('SUNFLOWER_EVENT_TIME_RANGE_BACK', '3 months');`

**Comment by smnvdl** [comment]
@codeispoetry perfekt, vielen Dank für das schnelle Handeln und die Umsetzung! Ich selbst bin auch gar kein großer Fan der Anzeige von vergangenen Terminen, aber andere Leute im OV und KV bei uns sehen das anders und hätten es gerne.
Dankeschön 😊
