### ISSUE TITLE
Designänderungen

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#350]
- [ ]  Social Media Buttons an prominenterer Stelle
- [ ] Farbkontraste

**Comment by rittmeier** [comment]
Wie ist denn hier der weitere Plan? Im Wurzelwerk ist der Style-Guide des Übergangsdesign schon eine Weile verfügbar. Das sorgt für Irritationen, wenn Print-Publikationen nach dem Übergangsdesign gemacht werden, Sun Flower-Websites hier aber noch einen älteren Stand umsetzen.

**Comment by codeispoetry** [comment]
Spätestens wenn vom Bundesverband das neue Design festgelegt wird, wird es ein Update geben. Aktuell ist das ja ein sog. "Übergangsstleguide"
