### ISSUE TITLE
Coverbild ausschalten

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#351]
Button einbauen, der Coverbilder in der Einzelansicht ausblendet. (damit sie in der Übersicht erscheinen)

**Comment by ErwinBehner** [comment]
Das ist jetzt aber falsch herum. Es geht darum das Beitragsbild in der Einzelansicht auszuschalten.

**Comment by codeispoetry** [comment]
Richtig. Danke.
