### ISSUE TITLE
Keine Sidebar auf Kategorie- und Terminübersichts-Seite

### ISSUE THREAD

**Issue by ErwinBehner** [codeispoetry/sunflower#353]
Ist es Absicht, dass auf Kategorie-Seiten wie z.B, https://sunflower-theme.de/demo/category/aktuelles/ und der Terminübersicht https://sunflower-theme.de/demo/termine/ keine Sidebar angezeigt wird?

**Comment by codeispoetry** [comment]
Ja, bisher wohl schon. Ich könnte in Sunflower 2 einen entsprechenden Schalter einbauen, um die Sidebar ein- bzw. auszuschalten.

**Comment by VILLAN3LL3** [comment]
In unserem KV wird die Sidebar vom Urwahl3000 Theme schmerzlich vermisst. Es wäre großartig, wenn es zukünftig wieder eine Möglichkeit gäbe, eine Sidebar zu konfigurieren

**Comment by KleinTommy** [comment]
Habe ich das falsch verstanden, oder sollten beim Umstieg von Urwahl nicht die Seitenleisten mitgenommen werden?
Das hat bei unserer Seite jedenfalls nicht geklappt.
Die Elemente der (Urwahl-)Sidebar erscheinen nun unter den Seiten des Fußleisten-Menüs.
Da sollen sie ja nun gar nicht erscheinen.
Leider bin ich zu unsicher, um das per Hand rauszucoden.

**Comment by ErwinBehner** [comment]
Das ist tatsächlich die beabsichtige Umsetzung, Die Seitenliste von Urwahl wird bei Sunflower in eine Fußleiste umgewandelt.

**Comment by VILLAN3LL3** [comment]
Warum wurde der Issue als completed markiert? Ist die Seitenleiste inzwischen verfügbar in Sunflower?

**Comment by codeispoetry** [comment]
Siehe Kommenatr vom 23. August.

**Comment by VILLAN3LL3** [comment]
Ich verstehe, dass das bisher so gewollt war. Aber noch im April hattest du vorgeschlagen, einen Schalte einzubauen, um das konfigurierbar zu machen. Im Rocket Chat habe ich schon etliche Posts gelesen, die die Sidebar gerne zurückhaben wollen. Was spricht denn dagegen?

**Comment by ErwinBehner** [comment]
Das mit dem Schalter bezog sich, so meine Wahrnehmung, auf die "Sidebar" genannte Fußleiste, welche bei den Kategorie. und Terminübersicht nicht angezeigt wirde.

**Comment by VILLAN3LL3** [comment]
Ich kann es nach wie vor nicht nachvollziehen, warum die Sidebar weggefallen ist. Sinnvoll natürlich für kleine Devices. Aber gerade bei Desktop-Größe fallen die Dinge einfach viel mehr ins Auge, wenn sie in der Sidebar auftauchen, als wenn man ganz nach unten scrollen muss, um sie zu sehen. Das machen viele Menschen einfach nicht. Und Platz genug ist bei größeren Devices auch.

**Comment by codeispoetry** [comment]
Ich habe das komplett missverstanden. Tut mit leid. Die Sidebars werden auf den beiden Archivseiten in der kommenden Version eingeblendet.

**Comment by codeispoetry** [comment]
Version 1.8.0 ist eben online gegangen. Darin ist es behoben
