### ISSUE TITLE
404 bei Aufruf von Unterseiten

### ISSUE THREAD

**Issue by BaGerhard** [codeispoetry/sunflower#356]
Ich habe Unterseiten im Sunflower-Theme angelegt. Rufe ich die Seiten auf, wird für die jeweilige Unterseite die 404-Seite von Sunflower ausgespielt.

Beispiel: https://gruene-oberfranken.de/partei/mandatstraegerinnen/

Eine Anfrage beim Hoster hat ergeben, dass der Server keine 404-Meldung verursacht.

**Comment by ErwinBehner** [comment]
Das ist kein Problem von Sunflower. In dem Fall wurde ein Unterseite mit Doppelpunkt erzeugt. Punk, Komma, Doppelpunkt, Sternchen, Schrägstrich, etc. sind hier keine erlaubte Zeichen.
