### ISSUE TITLE
Termintag: OV Traunreuth nicht benutzbar.

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#361]
zwei Personen mit unterschiedlichen Installationen berichten dass sie im Terminkalender das Tag `OV Traunreuth` nicht verwenden können. Also es wird in Termine eingetragen, aber in der Darstellung auf einer Seite lässt es sich im Terminblock nicht auswählen:

https://chatbegruenung.de/channel/sunflower-wordpress?msg=bhcLHBao7zfw2CqDM

**Comment by codeispoetry** [comment]
Ab 1.7.6 behoben.
