### ISSUE TITLE
Zeilenumbruch funktioniert nicht bei mehreren Elementen nebeneinander

### ISSUE THREAD

**Issue by hnmnn** [codeispoetry/sunflower#362]
Ich habe ein Problem mit neu aufgesetzten Kandidierenden-Websites. Wenn in einem Block zwei Elemente sind wie _Quote_ und _Absatz,_ funktioniert der Zeilenumbruch trotz angeschaltetem **"Zeilenumbruch auf mehrere Zeilen erlauben"** nicht. Sprich bei einem schmaleren Viewport gibt es keinen Umbruch und Elemente verschwinden rechts. Mobil funktioniert daher überhaupt nicht. Beispiele zu finden unter: https://christiangailus.de/ und https://nicole-van-der-made.de/. Muss ich hier customizen oder stimmt etwas mit dem Theme nicht?

<img width="875" alt="Bildschirmfoto 2022-07-28 um 11 22 28" src="https://user-images.githubusercontent.com/110164301/181470841-81893aa4-5ec4-4def-89ab-69b6acc98710.png">

**Comment by codeispoetry** [comment]
Ist das Problem noch aktuell? dann kannst du das Ticket gerne wieder öffnen.
