### ISSUE TITLE
Falsche Schriftart im Theme integriert?

### ISSUE THREAD

**Issue by hnmnn** [codeispoetry/sunflower#363]
Die PT Sans wird als Fließtextschrift nicht angezeigt auf allen neuen Kandidierenden-Seiten – es gibt scheinbar einen Fallback auf die Systemschrift Roboto. Liegt das an meinem System oder gibt es ein globales Problem? https://christiangailus.de/

**Comment by codeispoetry** [comment]
Ich habe da gerade ein Childtheme gesehen. Besteht das Problem noch (mit dem Elterntheme)?
