### ISSUE TITLE
Mobil-Menü nicht scrollbar

### ISSUE THREAD

**Issue by evaris1107** [codeispoetry/sunflower#364]
Navigiert man auf einem Mobilgerät durch das Hauptmenü der Website, ist es nicht möglich, alle Untermenüpunkte anzuklicken, wenn das Menü etwas länger ist.

Beispiel unsere Website [gruene-fuerth-land.de](https://www.gruene-fuerth-land.de/): Von 11 Ortsverbänden sind bspw. auf einem Galaxy S6 nur 9 sichtbar, die anderen beiden sehen Besucher der Website nicht und können sie auch nicht erreichen, da beim Scrollen bzw. Wischen nur die Page hinter dem Menü bewegt wird, das Menü selbst bleibt "starr".

![Screenshot (227)](https://user-images.githubusercontent.com/72270664/197404970-7637cecd-d58b-4186-a975-886c1bf1d2b5.png)
![Screenshot (226)](https://user-images.githubusercontent.com/72270664/197404973-13d4c0a8-e2c5-4122-8515-1e61ac834efd.png)

**Comment by codeispoetry** [comment]
Danke für die Fehlermeldung. 
Das ist ein sehr spezieller Fall. Du kannst in den individuellen CSS-Einstellungen folgendes Eintragen:

```
.dropdown-menu ul li a {
    padding-top: 0;
    padding-bottom: 0;
}
```

Damit sind alle Unterpunkte etwas näher beieinander und alle passen drauf.

**Comment by evaris1107** [comment]
Hat funktioniert, danke, aber ich verstehe nicht ganz, warum das ein spezieller Fall sein soll, der nur mich betrifft. Das gilt doch für jede Sunflower-Website, die mehr als 7 oder 8 Untermenüpunkte hat? Dass das Menü auf Mobil-Geräten nicht scrollbar ist, ist nach wie vor der Fall.

**Comment by tretkowski** [comment]
@albig wie besprochen...
