### ISSUE TITLE
Alte Wolke-Termine werden gelöscht

### ISSUE THREAD

**Issue by ErwinBehner** [codeispoetry/sunflower#365]
Ich habe verwende (teilweise) einen Wolke-Kalender zum Einstellen der Termine. Dabei wollte ich auch die Funktion "Vergangene Veranstaltungen anzeigen" nutzen. Es sieht für mich jedoch so aus als würden alte Termine von der Wolke aktiv gelöscht würden. Die Termine die ich nicht über die Wolke eingespielt habe, sind noch da, die von der Wolke alle alten Termine verschwunden. 

Lässt sich das Problem beheben oder ist dies technisch bedingt nicht anders machbar?

**Comment by codeispoetry** [comment]
Der Importer synchronisiert sich mit der Wolke. Wenn dort ein Termin geändert wurde, ändert er den Termin auch. Der Importer weiß nicht, warum ein Termin geändert oder gelöscht wurde und hält sich an dessen Vorgabe. Du müsstest also in der Wolke schauen, ob man das nicht doch dort einstellen kann.

**Comment by ErwinBehner** [comment]
In der Wolke sind alle Termine noch vorhanden. Das Problem ist, dass via iCal nur Termine abgefragt werden können die noch nicht vorbei sind.
