### ISSUE TITLE
Besuchter Button-Link nicht lesbar grün auf grün

### ISSUE THREAD

**Issue by fbthb** [codeispoetry/sunflower#366]
a:visited sieht als Schriftfarbe grün vor, was bei den grünen Buttons dafür sorgt, dass die Links zu bereits aufgerufenen Seiten nicht mehr lesbar sind.

Ergänzung: Problem scheint ab WordPress 6.1 aufzutreten, vermutlich im Zusammenhang mit der WordPress-Datei classic-themes.min.css

**Comment by b90g** [comment]
Dieses Verhalten melden einige Kund*innen vor allem wen sie eingeloggt sind.

**Comment by fbthb** [comment]
Bis das offiziell behoben wird, kann ich folgende Methode empfehlen:
`.wp-block-button__link {
color:white!important;
}`
im individuellen CSS von WordPress eingeben.

**Comment by b90g** [comment]
https://chatbegruenung.de/channel/sunflower-wordpress?msg=BEFZrNr39Eb2qyJx5 - hier eine diskussion mit Fehlerbeschreibungen verschiedenster Browser.

**Comment by codeispoetry** [comment]
Wird in der nächsten Version behoben sein

**Comment by SamuelBlickle** [comment]
Das selbe Problem scheint jetzt wieder aufzutreten, nur dieses mal weiß auf weiß.
Temporärer Workaround:
```
.wp-block-button__link:visited {
  color: #000;
}

.wp-block-button__link:hover {
  color: #fff;
}
```
