### ISSUE TITLE
Fehler tritt beim Umzug von Urwahl3000 auf

### ISSUE THREAD

**Issue by B-MdL-BF** [codeispoetry/sunflower#368]
Fatal Error beim Umzug von Urwahl3000 auf Sunflower. Zugriff auf das Dashboard nur noch über den Wiederherstellungsmodus möglich.

WordPress-Version 6.0.3
Aktives Theme: sunflower (Version 1.7.6) Aktuelles Plugin:  (Version ) PHP-Version 8.0.24

Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 19 der Datei /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-content/themes/sunflower/functions/activation.php verursacht. 

Fehlermeldung: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-content/themes/sunflower/functions/activation.php:19

Stack trace:
#0 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-content/themes/sunflower/functions/activation.php(19): array_merge()
#1 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-content/themes/sunflower/functions/activation.php(7): sunflower_import_widgets()
#2 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-includes/class-wp-hook.php(307): sunflower_activate_theme()
#3 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-includes/plugin.php(476): WP_Hook->do_action()
#5 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-includes/theme.php(3377): do_action()
#6 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-includes/class-wp-hook.php(307): check_theme_switched()
#7 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#8 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-includes/plugin.php(476): WP_Hook->do_action()
#9 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-settings.php(598): do_action()
#10 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-config.php(94): require_once('...')
#11 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-load.php(50): require_once('...')
#12 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-admin/admin.php(34): require_once('...')
#13 /mnt/web214/a1/46/58490646/htdocs/WordPress_02/wp-admin/themes.php(10): require_once('...')
#14 {main}
  thrown

**Comment by codeispoetry** [comment]
Dankeschön. Wird in der kommenden Version berhoben sein.
