### ISSUE TITLE
Ausklappmenüs in mobiler Ansicht klappen nicht aus.

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sunflower#379]
Menüs sind mobil nicht ausklappbar.

vgl: https://gruene-jena.de/ (version 1.8.1)

## Desktopansicht:

![grafik](https://user-images.githubusercontent.com/63392812/209105196-7ef859ae-8b3d-4dbe-8e1d-7fced3750cec.png)

## mobile Ansicht:
![grafik](https://user-images.githubusercontent.com/63392812/209104328-9324ab31-a877-4e39-ade9-1aff2122da35.png)

**Comment by ErwinBehner** [comment]
Problem scheint in der Datei assets/vndr/bootstrap/dist/js/bootstrap.min.js zu liegen.

**Comment by codeispoetry** [comment]
Der Fehler ist mit der Version 1.8.2.behoben. Die Datei popper.js muss neuerdings vor jquery geladen werden, vorher was das genau anders herum.
