### ISSUE TITLE
Font Arvo ist veraltet

### ISSUE THREAD

**Issue by Movm** [codeispoetry/sunflower#380]
Sehr stylisches Theme, aber leider mit alter grüner Font. Wäre es möglich, auf die BereitBold umzustellen?

**Comment by b90g** [comment]
Der Bundesverband hat zwar einen [Übergangsstyleguide veröffentlicht](https://wissenswerk.gruene.de/group/wissenswerk/home/-/artikel/u5DFhPGHusYg/14470638) aber kündigt auch an dass es ein neues Corporate Design (CD) geben wird. Momentan ist es nicht gut beide Designs zu vermischen und die Arbeit das Übergangsdeisgn als Theme entsprechend einzubinden müsste auch bezahlt werden. Das CD von 2017 ist auch weiterhin gültig. Sobald der Bundesverband ein finales Design bereit gestellt hat wird natürlich auch das Theme entsprechend angepasst.

**Comment by Movm** [comment]
Vielen Dank für die Antwort!
