### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#42]
"Sonstige Inhalte, die aktuell in der Fußleiste angezeigt werden"

Was soll da hin kommen und wie soll das bearbeitet werden?

**Comment by designerin** [comment]
Auf den aktuellen Urwahlseiten gibt es ja eine Fußleiste, ich dachte, diese Inhalte dürfen ja nicht verloren gehen. 

Daher würde ich diese bereits bestehenden Inhalte hier vorsehen.. bei meiner Recherche sah es so aus dass es ein Fußleistenmenü gibt (das wäre der Bereich über dem Strich) und dann gab es aber auch noch die Möglichkeit in der Fußleiste Widgets in 4 Spalten zu verwenden. Kann das Theme diese Wideget-Inhalte hier übernehmen? Verstehst du, was ich meine und macht das deiner Meinung nach Sinn?
