### ISSUE TITLE
Verwandte Artikel

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#44]
Verwandte Artikel sind kein Standard in WordPress. Sollen wir die Funktion einbauen? Worauf gründet sich dann "Verwandte Artikel"?

**Comment by designerin** [comment]
Ok.. das wusste ich nicht. ich habe das auch nur übernommen, da es im Urwahl verwendet wird.. ich denke es kann schon Sinn machen, die Besucher zum Weiterlesen zu animieren, aber wenn es zu Aufwendig ist hat es für mich auch keine oberste Priorität..
Sinn machen würde ja, Artikel mit möglcihst vielen gleichen Kategorien oder Schlagworten zu zeigen.

**Comment by codeispoetry** [comment]
siehe Urwahl3000

**Comment by codeispoetry** [comment]
Bei Urwahl3000 in theme_functions.php  kr8_related_posts

andere aus der gleichen Kategorie, sonst fallback zu allen posts
