### ISSUE TITLE
Testseite Login

### ISSUE THREAD

**Issue by gaschicht** [codeispoetry/sunflower#46]
Hi Tom,
momentan funktioniert das Login auf der Testseite nicht. https://wordpress.tom-rose.de/test/wp-admin/ gibt eine Fehlermeldung. Kannst du dir das Gelegenheit ansehen? Ich habe das Theme installiert, etwas damit rumgespielt und würde mir gerne das ein oder andere im Backend ansehen :-)
Danke & liebe Grüße
Gabi

**Comment by codeispoetry** [comment]
Liebe Gabi,

danke für den Hinweis. Ich wieder gefixet.
