### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#61]
- [x] oberster dunkler Menübalken schmaler (30px)

- [x] Logobalken schmaler (ca 80px)
- [x] Sonnenblume 60px groß
- [x] Sonnenblume margin-right 7px (so dass Logo-Schrift mit 1.Menüpunkt auf einer Linie sitzt)
- [x] Typo Logo Versalien (beide Zeilen)
- [x] 1.Zeile ArvoGruen 20px, letter-spacing: 1px
- [x] 2. Zeile: PT Sans 18px, Versalien, letterspacing 0.2px, 
- [x] Beide Logo-Text-Zeilen etwas näher zusammenrücken (siehe letzte Layout-Vorlage)

- [x] weiße Menüleiste etwas schmaler (55px)
- [x] Menüpunkte 18px, Farbe #363636
- [x] hover Textfarbe grün, aktiver aktueller Menüpunkt bleibt grün
- [x] Menüpunkte etwas weiter auseinander
- [x] schwarze Linie am unteren Rand des Menüs durch einen leichten Schlagschatten ersetzen (oder die Linie blassgrau machen wenn das für den Moment zu viel Aufwand ist mit dem Schatten)

weitere Infos zum Menü folgen.

**Comment by codeispoetry** [comment]
alles umgesetzt. Wenn das erst mal passt, kannst du das ticket gerne schließen.

**Comment by designerin** [comment]
Kannst du bitte noch folgendes anpassen:

- [ ] Subhead Logo font-weight: normal
- [ ] Menüpunkte font-size: 18px
- [ ] box-shadow: 0 6px 6px -6px lightgray
- [ ] "Suche"Feld dezenter (nur 1px border, Feld dann wie Hintergrundfarbe des Balkens, Typo wie nebenstehende Menüpunkte, Typo aktiv dann heller – genauso wie hover nebenstehende Menüpunkte)

**Comment by designerin** [comment]
- [ ] Suche-Feld ohne Radius, Kontur gleiche Farbe wie Schrift der obersten Menüpunkte, dicke grüne Kontur bei aktivieren raus nehmen

**Comment by codeispoetry** [comment]
Ich schließe das hier mal, damit wir den Überblick über die vielen Abstandsänderungen behalten :)
