### ISSUE TITLE
FAQ Layout/Seiteninhalt

### ISSUE THREAD

**Issue by tgcreative** [codeispoetry/sunflower#65]

**Comment by codeispoetry** [comment]
Danke dür das Ticket. Was genau ist denn damit gemeint?

**Comment by tgcreative** [comment]
![Faq_Beispiel](https://user-images.githubusercontent.com/55945067/108603080-fd377400-73a5-11eb-81d6-2e5ac23b3502.PNG)

Eine Art ausklappbares Frage-Antwort System wäre sehr nützlich, ähnlich gruene.de. Anbei ein Screenshot.

**Comment by codeispoetry** [comment]
Ist als Block Akkordeon eingebaut.
