### ISSUE TITLE
Abstände generell

### ISSUE THREAD

**Issue by designerin** [codeispoetry/sunflower#67]
- [x] Auf Unterseiten Abstand Headline zu  Menü 100px, Bei Dachzeile Abstand Dachzeile Menü 80px
- [x] Abstand Dachzeile Headline 30px
- [x] Abstand Headline zu Datum/Autor 50px
- [x] Abstand Datum/Autor zu Bild 65px
- [x] Abstand Bild zu Fließtext 60px

**Comment by designerin** [comment]
Die Abstände stimmen leider noch nicht.. kannst du das bitte noch mal prüfen?

**Comment by codeispoetry** [comment]
Die Abstände sind vergrößert. Hast Du mit Shift-Reload die neueste CSS-Datei geladen?

**Comment by designerin** [comment]
Die Abstände wurden glaube um meinen genannten Wert vergrößert und sind jetzt zu groß. Ich wollte eigentlich dass der tatsächliche Abstand zwischen den Elementen der genannte ist. Werde dir noch mal neue Werte errechnen und exakte marginwerte nennen, damit es passt.

**Comment by designerin** [comment]
- [ ] Bei Unterseiten Headlines "Aktuelles" "Termine" "Anträge" etc. margin 80px nach oben
- [ ] Unterhalb der "Subline" dann auch 80px nach unten 

- [ ] Bei den Masonry Feldern in der Beitragsübersicht bitte Padding ringsum 34px .p-4 {
    padding: 34px !important;
- [ ] Abstand zwischen den Feldern vertikal und horizontal 35px (--bs-gutter-x: 35px;
--bs-gutter-y: 35px;)
- [ ]
