### ISSUE TITLE
Theme-Downloadlinks broken

### ISSUE THREAD

**Issue by gaschicht** [codeispoetry/sunflower#68]
Lieber Tom,
ich habe aktuell Sunflower 0.1.7 installiert; die automatische Update-Benachrichtigung in Wordpress funktioniert noch nicht. Deshalb wollte ich mir 0.1.8 manuell von hier herunterladen https://wordpress.tom-rose.de/, allerdings funktionieren die Download-Links nicht (mehr). Kannst du dir das bei Gelegenheit ansehen?
Danke dir, liebe Grüße
Gabi

**Comment by codeispoetry** [comment]
Hi

gehe bitte auf https://sunflower-theme.de

Eigtl ist auf wordpress.tom-rose eine Weiterleitung eingerichtet.
