### ISSUE TITLE
Theme Vorschaubild

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#69]
Könntest Du ein passendes Theme-Vorschaubild erstellen?
Größe: 1200×900 Pixel, 
- [x]  Vorschaubild Theme
- [x] Vorschaubild für Child-Theme

Das bisherigen sehen so aus, es sollte imho keine Person darauf zu sehen sein:

![screenshot](https://user-images.githubusercontent.com/6557858/108595597-124ddc00-7381-11eb-921d-1abd7585cbbe.png)

![screenshot](https://user-images.githubusercontent.com/6557858/108595611-1f6acb00-7381-11eb-99d7-89ee1f64232a.png)

**Comment by designerin** [comment]
Klar, darum kümmere ich mich gerne morgen
