### ISSUE TITLE
Blaues X im Suchfeld über Footer

### ISSUE THREAD

**Issue by tgcreative** [codeispoetry/sunflower#77]
![bluex](https://user-images.githubusercontent.com/55945067/108620680-08ce7d80-742e-11eb-9bd0-e830466ee90b.PNG)
Reproduzierbar nur, wenn ausgewählt + value

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Wird ab 0.7.2 behoben sein. Daher closed
