### ISSUE TITLE
header-personal: Grüner Hintergrund der Sonnenblume nicht mehr quadratisch

### ISSUE THREAD

**Issue by FloJuh** [codeispoetry/sunflower#770]
## Describe the bug
In Version 2.2.3 des Themes ist der grüne Hintergrund der Sonnenblume im `header-personal` nicht mehr quadratisch und wirkt dadurch verzerrt. Im mobilen Menü des `standard header` ist der Hintergrund hingegen weiterhin proportional und unverzerrt dargestellt. In der vorherigen Version 2.2.2 war die Darstellung im `header-personal` ebenfalls korrekt und entsprach der des `standard header`.

### Website or Screenshots
2.2.3:
![2 2 3](https://github.com/user-attachments/assets/99b28115-b792-4725-ac9d-d5396d26c4b7)
2.2.2:
![2 2 2](https://github.com/user-attachments/assets/ed3bac9c-cf27-4a96-9399-e4c5c4b75796)

### Environment
 - Devise: Desktop and Smartphone
 - Browser: Firefox
 - Version of the sunflower theme: 2.2.3
 - WordPress version: 6.7
 - PHP version: 8.2.25

## Additional context
Eingeführt mit https://github.com/verdigado/sunflower/releases/tag/v2.2.3

**Comment by FloJuh** [comment]
Auf dem Smartphone sieht es tatsächlich gut aus und sollte vielleicht beibehalten werden

**Comment by albig** [comment]
Vermutlich durch https://github.com/verdigado/sunflower/pull/767 verursacht. Ich hätte gerne auf Beschränkungen für das `custom-logo` verzichtet, aber es sind zu viele Seiten im Umlauf, die mal eben 3000px breite "Logos" im Einsatz haben und die Seite komplett zerstören.
Das `sunflower-logo` hätte es nicht betreffen dürfen.
