### ISSUE TITLE
Gruppierungen auf der Startseite rutschen links aus dem sichtbaren Bereich 

### ISSUE THREAD

**Issue by andra03** [codeispoetry/sunflower#79]
Version 0.7.1, Chrome und Edge desktop, mobile Chrome und Brave

Wenn ich auf der Startseite Blöcke gruppiere, um sie farbig zu hinterlegen, rutschen sie links aus dem sichtbaren Bereich. 
Das passiert bei einfachen Gruppierungen wie Überschrift + Absatz und bei komplexeren mit Spalten und Bildern.
Der Teil der fehlt scheint etwa das Drittel zu sein, was auf der rechten Seite nicht für Content genutzt wird. 
Effekt bei Zoom Level 100 % und größer. 

Selber Effekt bei der Blockart *Cover*.

 Viele Grüße, Alexandra
![2021-02-21 Sunflower bug](https://user-images.githubusercontent.com/74626015/108621274-0c640380-7432-11eb-9e37-e6d1ef46340b.png)

**Comment by codeispoetry** [comment]
Bitte wähle bei den Seiteeinstellung "breites Layout". Dann müsste es gehen. Breites Layout ist ab Verion .7.0 default.

**Comment by codeispoetry** [comment]
Wenn es das war, kannst Du das Ticket gerne schließen

**Comment by andra03** [comment]
Das wars! Danke.
