### ISSUE TITLE
Zwei Hamburger im Kopf 

### ISSUE THREAD

**Issue by andra03** [codeispoetry/sunflower#80]
Auf Mobile devices und auf kleinen Bildschirmen zeigt das Theme zwei Hamburger-Menüs im Kopfbereich: Eines oben links in der dunklen Leiste und eines weiter unten rechts. Ich weiß wo, das herkommt, aber es gibt Leute, die sich daran stoßen.

![image](https://user-images.githubusercontent.com/74626015/108621396-adeb5500-7432-11eb-9dfa-ae1289b450d5.png)
 

Viele Grüße
Alexandra

**Comment by codeispoetry** [comment]
Ich werde mal das obere Menü nicht collapsen lassen

**Comment by codeispoetry** [comment]
Ich hab die oberen Hamburger mal rausgenommen, aber dann ist nicht genügend Platz für alle Items. Das ist auch keine Lösung.

**Comment by codeispoetry** [comment]
@designerin Was hälst Du davon?

**Comment by designerin** [comment]
Die Mobilvariante muss noch ausgearbeitet werden. Ich denke hier würde ich gerne beide Menüs in einem Hamburger zusammennehmen wenn das geht..  Untereinanderstehend aufgeklappt dann erst weiß hinterlegt das Main Menu und dann dunkel hinterlegt die externen Links. 
Oder wir machen es wie beim Vorgänger und stellen die Menüpunkte aus der obersten Leiste mit in den Footer. Ist vielleicht die elegantere Lösung und scheinbar hat sich ja bislang auch niemand daran gestört

**Comment by codeispoetry** [comment]
Das topmenü wird auf Handys nun unten im Footer angezeigt.
