### ISSUE TITLE
Abstände

### ISSUE THREAD

**Issue by tgcreative** [codeispoetry/sunflower#81]
- [x] zwischen einzelnen Terminen 
![termin h1](https://user-images.githubusercontent.com/55945067/108621549-a1b3c780-7433-11eb-9fd4-b6ae7727ef46.PNG)
Tritt nur bei Skalierung unter 1000x850 auf.

- [x] Abstand unter neuem Akkordion Sunflower Block
![akkordion](https://user-images.githubusercontent.com/55945067/108622622-551fba80-743a-11eb-86ef-3cf8115c2695.PNG)

Übrigens vielen Dank für die schnelle Implementation

- [x] Termine:
`.entry-content {
    margin-top: 60px;
}`

**Comment by codeispoetry** [comment]
Die generellen Abstäde auf den Seiten müssen noch erarbeitet werden. Problem ist, wenn man als letztes einen mit Hintergrundfarbe einfügt, wie auf der Startseite, dann darf es keinen unteren margin geben. Sonst sollte er da sein. Aber wie kann das autoamtisch erkannt werden?

**Comment by codeispoetry** [comment]
Hab es jetzt doch mit :last-of-type gelöst, unter dem letzten Akkordeon-Punkt gibt es jetzt immer 50px Abstand.
Vielen dank für die Rückmeldung.

**Comment by andra03** [comment]
Das betrifft auch die Abstände zwischen Beiträgen auf einer Kategorie-Sammelseite (Eine Seite, die alle Beiträge einer Kategorie listet. Hier sind die Abstände nach unten zu eng bzw. nicht vorhanden. Zur Seite ist es OK. 
Version 0.7.4

**Comment by codeispoetry** [comment]
Dankeschön. Das ganze Thema Abstände wird noch mal gesondert angegangen.
