### ISSUE TITLE
Fontsize für Zitate sehr groß

### ISSUE THREAD

**Issue by andra03** [codeispoetry/sunflower#82]
Bei längeren Zitaten, i.e. 10 Wörter und mehr ist die Schriftgröße zu groß. Bei richtig langen Zitaten von zwei oder drei Sätzen ist der Block eigentlich nicht mehr zu gebrauchen, weil er eine ganze Bildschirmseite einnimmt (auf meinem Laptop).

Idee: Die Redezeichen in der Fontgröße lassen und den Text kleiner und damit weniger raumgreifend setzen.

**Comment by designerin** [comment]
Danke dir für dein Feedback, ich gebe dir da absolut Recht. Ich arbeite hier noch an einer Alternative

**Comment by designerin** [comment]
- [ ] Zitattext 23px

**Comment by codeispoetry** [comment]
Wird ab 0.7.2 behoben sein. Daher closed. 
Danke fürs Feedback.
