### ISSUE TITLE
Mobile Layout (Diverses)

### ISSUE THREAD

**Issue by Nachtmensch87** [codeispoetry/sunflower#83]
Im mobile Layout sind mir noch kleinere Dinge aufgefallen:
- [ ] Auf der Startseite (und ggfs auch woanders) kann man 'horizontal' scrollen, und man sieht nur einen schmalen Streifen mit der Hintergrundfarbe. Das war bei Urwahl3000 auch schon so, hing dort aber damit zusammen, dass ggfs. zu lange Titel über den Anzeigebereich hinaus gingen. Ich hatte das dort mit CustomCSS gelöst, dass die Titel dann kleiner skaliert werden.
- [x] die Kategorien im Footer überlappen sich mit den Pfeilen, sobald die Zeichenanzahl etwas größer ist (ggfs kleiner skalieren)?
- [x] ebenfalls im Footer werden die SocialMedia Links und die Verweise auf die anderen Seiten etwas unschön umgebrochen. Hier wäre es schöner, wenn die Textlinks in einer Ebene wären und die Social Media darunter oder darüber.

![Screenshot_20210221-114854.png](https://user-images.githubusercontent.com/10704700/108622900-230f5800-743c-11eb-900d-8535a9f47db8.png)![Screenshot_20210221-111634.png](https://user-images.githubusercontent.com/10704700/108622902-24d91b80-743c-11eb-8d64-0523423ca7c5.png)![Screenshot_20210221-111626.png](https://user-images.githubusercontent.com/10704700/108622908-2a366600-743c-11eb-9035-5ea584d56db8.png)

**Comment by codeispoetry** [comment]
Danke für Dein Feedback.
Zu 1: den Fehler sehe ich bei mir nicht. Welches Handy benutzt Du? ein iPhone? Auf Android sehe ich den Fehler nicht
Zu 2: @designerin kannst Du dir das mal anschauen?
Zu 3: Ist ab 0.7.2 behoben.

**Comment by designerin** [comment]
zu 1.: Die Headline-Schrift müsste für Mobile noch kleiner skaliert werden. 
zu 2.: Die Widgets sollten in der kleinen Mobilversion umbrechen und nicht zweispaltig gezeigt werden. Und dann muss der Text in eine zweite Zeile umbrechen, bevor er den Pfeil schneidet.

**Comment by designerin** [comment]
zu 1.: Die Startseite ist noch nicht durch und durch Smartphone optimiert.. ich hoffe, das können wir noch beheben

**Comment by codeispoetry** [comment]
Das mit den Widgets ist nun auch behoben. Da die mobile-Ansicht eh noch angepasst wird, kann dieses Ticket hier erst mal geschlossen werden. Danke fürs Feedback

**Comment by codeispoetry** [comment]
Quatsch, das Thema horizontales Scrollen ist ja noch offen.

**Comment by Nachtmensch87** [comment]
Zu 1 und dem kleinen Rand am rechten Bildschirmrand. Ich nutze auch Android (11). Chrome 88.  Das tritt aber auch nur auf sunflower-theme.de/demo auf. Auf sunflower-theme.de ist dieser kleine Rand nicht vorhanden.

**Comment by designerin** [comment]
Sämtliche Elemente der Startseite sollten nach rechts und links noch einen kleinen Abstand zum Rand bekommen (wie bei der Beitragsübersicht zB). Vielleicht hilft es schon, wenn das schmaler skaliert wird

**Comment by codeispoetry** [comment]
Die Elemente haben an Version 0.7.5 Abstände zum Rand und das scrollen nach links oder rechts auf dem Handy dürfte auch nicht mehr vorkommen.

Danke für den Bugreport.
Ich schließe das Ticket, falls das Problem doch noch auftritt, gerne wieder öffnen oder ein neues anlegen.

**Comment by codeispoetry** [comment]
Das mit dem horizontalen Scrollen kann wieder drin sein. Ich kann meine Lösung mit overflow-x:hidden nicht verwenden, weil sonst der sticky header nicht mehr sticky ist....

**Comment by codeispoetry** [comment]
Ich habe dazu ein neues Ticket #89 aufgemacht und schließe deshalb hier.
