### ISSUE TITLE
zusätzlicher Tabs-Block 

### ISSUE THREAD

**Issue by Nachtmensch87** [codeispoetry/sunflower#84]
Gestaltungstechnisch wäre es schön, wenn es ähnlich zum Akkordion-Block, einen Tab-Block geben würde.

**Comment by codeispoetry** [comment]
Danke für den Feature-Request. In der Version 1, die bis Ostern rauskommen soll, schaffen wir das leider nicht mehr. Deshalb setze ich ein passenden Label (for future release), schließe aber das Ticket einstweilen.

**Comment by TheAbbay** [comment]
Freue mich, dass dieses Feature in der Mache ist. Hätte mich im worst-case zum Sommer sonst selber drum kümmern müssen. ;)
Es gibt dieses tolle Feature im anderen Grünen Theme "Joseph knows best", an dem ich mich orientiert hätte. Man sollte lediglich die Responsiveness bedenken. Die Tabs waren mobile zwar entsprechend passend, aber ist am Desktop zu wenig Platz, haben die Tabs ganz hässlich gebrochen.

**Comment by codeispoetry** [comment]
In der nächsten Version wird es das Feature leider nicht geben. Das ist wohl besser Aufgabe für ein Third-Party-Plugin. Das kann man dann ggf. stylen.
