### ISSUE TITLE
Horizontales Scrollen

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sunflower#89]
Verhindere horizontales Scrollen. Ist ab 0.8.5 unterbunden

**Comment by Nachtmensch87** [comment]
Hey, in der 0.85 sieht das wieder etwas komisch aus. Da scheint der Header und Footer in der mobilen Ansicht aber auch etwas breiter zu sein als der Content. 

Ich habe auf der Testseite zudem mal einen Titel geändert (Seitentitel von 'Deine Meinung ist gefragt' zu 'DeineMeinungIstGefragt'). Klar, das Wort ergibt keinen Sinn. Aber: Die Mobile Ansicht ist dadurch mehr oder weniger vollkommen kaputt. Links ist etwas abgeschnitten und gar nicht sichtbar, rechts ragt das Wort über den eigentlichen Content-Bereich weit hinaus. Dies passiert, wenn die Zeichenanzahl eines Wortes zu groß wird, was ja durchaus aber mal passieren kann.
Dies ist in Urwahl3000 auch so. Ich habe es dort behelfsweise so gelöst:
`h1 {
  font-size: calc(21px + (64 - 21) * ((100vw - 300px) / (1920 - 300)));
  line-height: calc(1.3em + (1.5 - 1.2) * ((100vw - 300px)/(1920 - 300)));
}`

**Comment by codeispoetry** [comment]
danke für die Info. Das mit dem langen Titel habe ich nun mit
``    word-break: break-all;``
für den body gelöst.

**Comment by codeispoetry** [comment]
In 0.8.6 sollte lange Wörter erzwungen umgebrochen werden. Als Autor*in hat man die Möglichkeit, die Bruchstelle zu definieren, indem man die die gewünschte Stelle ein `&shy;` einträgt. Ich schreib das mal in die Doku
Zum horizontalen Scrollen habe ich auch mal was ausprobiert.

**Comment by codeispoetry** [comment]
https://sunflower-theme.de/documentation/faq/#manche-begriffe-sind-auf-handys-zu-lang

**Comment by Nachtmensch87** [comment]
> In 0.8.6 sollte lange Wörter erzwungen umgebrochen werden. Als Autor*in hat man die Möglichkeit, die Bruchstelle zu definieren, indem man die die gewünschte Stelle ein `&shy;` einträgt. Ich schreib das mal in die Doku
> Zum horizontalen Scrollen habe ich auch mal was ausprobiert.

Das horizontale Scrollen ist nicht mehr da. Nur ist der Inhaltsbereich noch etwas schmaler als der Header.

Das ist ein guter Hinweis. Danke, das kannte ich noch nicht. Ist das auch so möglich, dass man optional ein Bindestrich hinzufügen kann? Bundestagskandidaten wenn genügend Platz und Bundestags-kandidaten, wenn weniger Platz?

**Comment by codeispoetry** [comment]
Genau dieser Bindestrich wird mit ``&shy;`` gemacht. Und an ihm wird dann die Zeile umgebrochen

**Comment by codeispoetry** [comment]
Ich schließe das Ticket mal und wir schauen, als wie störend der etwas schmalere Bereich von anderen empfunden wird.

**Comment by Nachtmensch87** [comment]
Alles klar. Ich muss gestehen, dass es da vorher fast besser war🙈 Der automatisch bzw manuelle Umbruch bei zu langen Wörtern ist natürlich super. 

Aber durch irgendwelche Änderungen ist der Inhalt auf der Startseite nun ja nicht mehr zentriert dargestellt. Klickt man dann auf Aktuelles, dann ist hingegen alles so wie es sein sollte:) Trotzdem ein riesen Lob für die Arbeit! Sieht soweit sonst Klasse aus!

**Comment by codeispoetry** [comment]
Das müsste in der Version 0.10.0 nun endlich korrekt sein.
